SEMS: AmUtils.h File Reference
AmUtils.h File Reference
#include <stdio.h>
#include <sys/stat.h>
#include <errno.h>
#include <sys/types.h>
#include <regex.h>
#include <sys/socket.h>
#include <string>
#include <vector>
#include <utility>
#include <map>
#include "md5.h"
Defines
#define HASHLEN 16
#define HASHHEXLEN 32
#define PARAM_HDR "P-App-Param"
#define APPNAME_HDR "P-App-Name"
#define sleep_us(nusecs)
microseconds sleep using select
Typedefs
typedef unsigned char HASH [HASHLEN]
typedef unsigned char HASHHEX [HASHHEXLEN+1]
typedef std::vector< std::pair
< regex_t, string > > RegexMappingVector
Functions
string int2str (int val)
string int2str (unsigned int val)
string long2str (long int val)
string longlong2str (long long int val)
string char2hex (unsigned char val, bool lowercase=false)
string int2hex (unsigned int val, bool lowercase=false)
string long2hex (unsigned long val)
bool reverse_hex2int (const string &str, unsigned int &result)
string double2str (double val)
bool str2i (const string &str, unsigned int &result)
bool str2i (char *&str, unsigned int &result, char sep= ' ')
bool str2int (const string &str, int &result)
bool str2int (char *&str, int &result, char sep= ' ')
bool str2long (const string &str, long &result)
bool str2long (char *&str, long &result, char sep= ' ')
bool str2bool (const string &s, bool &dst)
std::string URL_decode (const std::string &s)
std::string URL_encode (const std::string &s)
int parse_return_code (const char *lbuf, unsigned int &res_code, string &res_msg)
bool file_exists (const string &name)
string filename_from_fullpath (const string &path)
string file_extension (const string &path)
string add2path (const string &path, int n_suffix,...)
string get_addr_str (const sockaddr_storage *addr)
string get_addr_str_sip (const sockaddr_storage *addr)
int get_local_addr_for_dest (sockaddr_storage *remote_ip, sockaddr_storage *local)
int get_local_addr_for_dest (const string &remote_ip, string &local)
string extract_tag (const string &addr)
bool key_in_list (const string &s_list, const string &key, char list_delim= ',')
string strip_header_params (const string &hdr_string)
string get_header_param (const string &hdr_string, const string &param_name)
string get_header_keyvalue (const string &param_hdr, const string &name)
string get_header_keyvalue_single (const string &param_hdr, const string &name)
string get_header_keyvalue (const string &param_hdr, const string &short_name, const string &name)
string get_session_param (const string &hdrs, const string &name)
void parse_app_params (const string &hdrs, std::map< string, string > &app_params)
void init_random ()
unsigned int get_random ()
std::vector< string > explode (const string &s, const string &delim, const bool keep_empty=false)
std::string trim (std::string const &str, char const *sepSet)
void add_env_path (const char *name, const string &path)
size_t skip_to_end_of_brackets (const string &s, size_t start)
bool read_regex_mapping (const string &fname, const char *sep, const char *dbg_type, RegexMappingVector &result)
bool run_regex_mapping (const RegexMappingVector &mapping, const char *test_s, string &result)
void cvt_hex (HASH bin, HASHHEX hex)
string calculateMD5 (const string &input)
Detailed Description
Define Documentation
#define sleep_us (nusecs)
Value:
{ \
        struct timeval tval; \
        tval.tv_sec=nusecs/1000000; \
        tval.tv_usec=nusecs%1000000; \
        select(0, NULL, NULL, NULL, &tval ); \
        }
microseconds sleep using select
Function Documentation
string add2path (const string & path, int n_suffix, ...)
Returns:
new path resulting from the concatanation of path, suffix and eventually a slash between them
Referenced by AnswerMachineFactory::onInvite(), PySemsFactory::onLoad(), AnswerMachineFactory::onLoad(), IvrFactory::onLoad(), and AnswerMachineDialog::onSessionStart().
void add_env_path (const char * name, const string & path)
add a directory to an environement variable
string calculateMD5 (const string & input)
get an MD5 hash of a string
References cvt_hex().
string char2hex (unsigned char val, bool lowercase = false)
Convert a a byte to a string using hexdecimal representation.
Referenced by AmConfigReader::getMD5().
void cvt_hex (HASH bin, HASHHEX hex)
convert a binary MD5 hash to hex representation
Referenced by UACAuth::calcNonce(), calculateMD5(), and UACAuth::checkNonce().
string double2str (double val)
Convert a double to a string.
Convert a double to a string. (from jsoncpp)
std::vector<string> explode (const string & s, const string & delim, const bool keep_empty = false)
Explode string by a separator to a vector
Referenced by get_header_keyvalue(), AmPlugIn::load(), DIDialFactory::onLoad(), VoiceboxFactory::onLoad(), AnswerMachineFactory::onLoad(), SBCFactory::onLoad(), DSMFactory::onLoad(), AmPrecodedFile::open(), read_regex_mapping(), and AmConfig::readConfiguration().
bool file_exists (const string & name)
Tells if a file exists.
Parameters:
name file name.
Returns:
true if file could be openned.
Referenced by AnnounceB2BFactory::onInvite(), AnnounceTransferFactory::onInvite(), ServiceLineFactory::onInvite(), EarlyAnnounceFactory::onInvite(), AnnounceAuthFactory::onInvite(), AnswerMachineFactory::onInvite(), ConferenceDialog::onInvite(), MyConfigurableAppFactory::onLoad(), MyAnnounceAppFactory::onLoad(), AnnounceB2BFactory::onLoad(), AnnounceTransferFactory::onLoad(), DtmfTesterFactory::onLoad(), AnnouncementFactory::onLoad(), CacheAnnounceFactory::onLoad(), Click2DialFactory::onLoad(), ServiceLineFactory::onLoad(), EarlyAnnounceFactory::onLoad(), AnnounceAuthFactory::onLoad(), ConferenceFactory::onLoad(), and AmPromptCollection::setPrompt().
string file_extension (const string & path)
Returns:
A file extension extracted from the given full path file name.
Referenced by AmAudioFile::fileName2Fmt().
string filename_from_fullpath (const string & path)
Returns:
A file name extracted from the given full path file name.
string get_header_keyvalue (const string & param_hdr, const string & name)
get the value of key
Parameters:
name from the list param_hdr
get value from parameter header with the name
Parameters:
name while skipping escaped values
References explode(), and get_header_keyvalue_single().
string get_header_keyvalue (const string & param_hdr, const string & short_name, const string & name)
get the value of key
Parameters:
short_name or
name or from the list param_hdr
References get_header_keyvalue().
Referenced by get_header_keyvalue(), get_session_param(), EarlyAnnounceFactory::onInvite(), VoiceboxFactory::onInvite(), AnswerMachineFactory::onInvite(), ConferenceDialog::onInvite(), ConferenceDialog::onSipRequest(), and EarlyAnnounceDialog::process().
string get_header_keyvalue_single (const string & param_hdr, const string & name)
get the value of key
Parameters:
name from the list param_hdr, no comma separated values
Referenced by get_header_keyvalue().
string get_header_param (const string & hdr_string, const string & param_name)
get a header parameter value
Referenced by AmPlugIn::findSessionFactory(), AmSipSubscription::matchSubscription(), WebConferenceDialog::onInvite(), SubscriptionDialog::onSipRequest(), and AmB2BSession::onSipRequest().
unsigned int get_random ()
support for thread-safe pseudo-random numbers - make a random number function
Referenced by AmRtpStream::AmRtpStream(), AmSession::getNewId(), AmSipDialog::onRxReqSanity(), and AmContentType::resetBoundary().
string get_session_param (const string & hdrs, const string & name)
get the value of key
Parameters:
name from P-Iptel-Param header in hdrs
get the value of key
Parameters:
name from PARAM_HDR header in hdrs
References get_header_keyvalue().
Referenced by AnnounceTransferDialog::onInvite().
void init_random ()
support for thread-safe pseudo-random numbers - init function
string int2hex (unsigned int val, bool lowercase = false)
Convert an unsigned int to a string using hexdecimal representation.
Referenced by UACAuth::calcNonce(), AmSession::getNewId(), and AmContentType::resetBoundary().
string int2str (int val)
Convert an int to a string.
string int2str (unsigned int val)
Convert an unsigned int to a string.
Referenced by SdpMedia::debugPrint(), AmConferenceChannel::get(), AmBasicSipDialog::getContactUri(), WCCCallStats::getSummary(), JsonrpcNetstringsConnection::netstringsBlockingWrite(), MyJukeboxDialog::onDtmf(), MyCCDialog::onDtmf(), JukecallSession::onDtmf(), DtmfTesterDialog::onDtmf(), DSMCall::onDtmf(), PinAuthConferenceDialog::onDtmf(), VoiceboxDialog::onDtmf(), CallBackDialog::onDtmf(), WebConferenceDialog::onDtmf(), DIDialFactory::onLoad(), ServiceLineFactory::onLoad(), PinAuthConferenceFactory::onLoad(), RegistrationAgentFactory::onLoad(), CallBackFactory::onLoad(), DSMCall::onOtherReply(), DSMCall::onRemoteDisappeared(), DSMCall::onRinging(), AmSipDialog::onRxReqSanity(), AmBasicSipDialog::onRxRequest(), CallGenDialog::onSessionStart(), RegisterDialog::onSipReply(), SubscriptionDialog::onSipReply(), DSMCall::onSipReply(), WebConferenceDialog::onSipReply(), AmB2BSession::onSipReply(), SubscriptionDialog::onSipRequest(), DSMCall::onSipRequest(), AmB2BSession::onSipRequest(), AmSipDialog::prack(), AmSdp::print(), DSMCall::process(), AmConferenceChannel::put(), AmSipDialog::refer(), AmB2BSession::relaySip(), AmB2BMedia::replaceConnectionAddress(), SBCCallProfile::retarget(), run_regex_mapping(), _RegisterCache::saveSingleContact(), _SipCtrlInterface::send(), _trans_layer::send_reply(), _trans_layer::send_sl_reply(), AmSession::sid4dbg(), and AmBasicSipDialog::updateDialogTarget().
bool key_in_list (const string & s_list, const string & key, char list_delim = ',')
returns true if key is in s_list, a list of items delimited by list_delim skips whitespaces, too
Referenced by AmSession::updateRefreshMethod().
string long2hex (unsigned long val)
Convert an unsigned long to a string using hexdecimal representation.
string long2str (long int val)
Convert a long to a string.
Referenced by _RegisterCache::throttleRegister().
string longlong2str (long long int val)
Convert a long long to a string.
void parse_app_params (const string & hdrs, std::map< string, string > & app_params)
parse the P-App-Param header and extracts the parameters into a map
Referenced by AmSessionContainer::createSession().
int parse_return_code (const char * lbuf, unsigned int & res_code, string & res_msg)
Parse code/reason line. Syntax: "code reason"
Parameters:
lbuf line buffer to parse.
res_code_str char[4]; Syntax: xxxx whereby each x is a between 0 and 9.
res_code where to store the resulting integer 'code'.
res_msg where to store the 'reason'.
Referenced by AnnounceTransferDialog::onSipRequest().
bool read_regex_mapping (const string & fname, const char * sep, const char * dbg_type, RegexMappingVector & result)
read a regex=>string mapping from file
Returns:
true on success
References explode().
Referenced by SBCFactory::onLoad(), and AmConfig::readConfiguration().
bool reverse_hex2int (const string & str, unsigned int & result)
Convert a reversed hex string to uint.
Parameters:
str [in] string to convert.
result [out] result integer.
Returns:
true if failed.
bool run_regex_mapping (const RegexMappingVector & mapping, const char * test_s, string & result)
run a regex mapping - result is the first matching entry
Returns:
true if matched
References int2str().
Referenced by AmPlugIn::findSessionFactory().
size_t skip_to_end_of_brackets (const string & s, size_t start)
skip to the end of a string enclosed in round brackets, skipping more bracketed items, too
bool str2i (const string & str, unsigned int & result)
Convert a string to an uint.
Parameters:
str [in] string to convert.
result [out] result integer.
Returns:
true if failed (!!!)
References str2i().
Referenced by JsonrpcNetstringsConnection::netstringsRead(), VoiceboxFactory::onLoad(), ConferenceFactory::onLoad(), RegisterDialog::onSipReply(), AmSIPRegistration::onSipReply(), EarlyAnnounceDialog::process(), AmConfig::readConfiguration(), _RegisterCache::saveSingleContact(), and str2i().
bool str2i (char *& str, unsigned int & result, char sep = ' ')
Internal version of preceeding 'str2i' method.
Parameters:
str [in,out] gets incremented until sep char or error occurs
result [out] result of the function
sep [in] character seprating the number to convert and the next token
Returns:
true if failed (!!!)
bool str2int (const string & str, int & result)
Convert a string to an int.
Parameters:
str [in] string to convert.
result [out] result integer.
Returns:
true on success (!!!)
References str2int().
Referenced by SubscriptionDialog::onSipRequest(), AmB2BSession::onSipRequest(), and str2int().
bool str2int (char *& str, int & result, char sep = ' ')
Internal version of preceeding 'str2int' method.
Parameters:
str [in,out] gets incremented until sep char or error occurs
result [out] result of the function
sep [in] character seprating the number to convert and the next token
Returns:
true on success (!!!)
bool str2long (const string & str, long & result)
Convert a string to a long int. On many systems nowadays this could be the same as str2int.
Parameters:
str [in] string to convert.
result [out] result integer.
Returns:
true if on success (!!!).
References str2long().
Referenced by str2long(), and _RegisterCache::throttleRegister().
bool str2long (char *& str, long & result, char sep = ' ')
Internal version of preceeding 'str2long' method.
Parameters:
str [in,out] gets incremented until sep char or error occurs
result [out] result of the function
sep [in] character seprating the number to convert and the next token
Returns:
true on success
string strip_header_params (const string & hdr_string)
return string with trailing spaces and everything after ; including ; itself removed
Referenced by AmSipSubscription::matchSubscription(), SubscriptionDialog::onSipRequest(), AnnounceTransferDialog::onSipRequest(), and AmB2BSession::onSipRequest().
std::string trim (std::string const & str, char const * sepSet) [inline]
remove chars in sepSet from beginning and end of str