SEMS: ConferenceFactory Class Reference
ConferenceFactory Class Reference
Factory for conference sessions.
#include <Conference.h>
Public Member Functions
ConferenceFactory (const string &_app_name)
virtual AmSession * onInvite (const AmSipRequest &, const string &app_name, const map< string, string > &app_params)
virtual AmSession * onRefer (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
virtual int onLoad ()
Static Public Member Functions
static void setupSessionTimer (AmSession *s)
Static Public Attributes
static string AudioPath
static string LonelyUserFile
static string JoinSound
static string DropSound
static string DialoutSuffix
static PlayoutType m_PlayoutType = ADAPTIVE_PLAYOUT
static unsigned int MaxParticipants
static bool UseRFC4240Rooms
Detailed Description
Factory for conference sessions.
Member Function Documentation
AmSession * ConferenceFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
int ConferenceFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AmSessionFactory::configureModule(), file_exists(), AmPlugIn::getFactory4Seh(), AmConfig::ModConfigPath, and str2i().
AmSession * ConferenceFactory::onRefer (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new REFER with local-tag.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Reimplemented from AmSessionFactory.
The documentation for this class was generated from the following files:
Conference.h
Conference.cpp