SEMS: RtmpSession Class Reference
RtmpSession Class Reference
Public Member Functions
RtmpSession (RtmpConnection *c)
void onSessionStart ()
void onBye (const AmSipRequest &req)
void onBeforeDestroy ()
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
void onInvite (const AmSipRequest &req)
void process (AmEvent *)
void bufferPacket (const RTMPPacket &p)
void setConnectionPtr (RtmpConnection *c)
void setPlayStreamID (unsigned int stream_id)
void disconnect ()
void accept ()
Member Function Documentation
void RtmpSession::onBeforeDestroy () [virtual]
called in the session thread before the session is destroyed, i.e. after the main event loop has finished
Reimplemented from AmSession.
void RtmpSession::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
void RtmpSession::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmSession.
References AmBasicSipDialog::getStatus(), and AmBasicSipDialog::reply().
void RtmpSession::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmSession::setStopped().
void RtmpSession::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_dlg_status) [virtual]
Entry point for SIP Replies
Reimplemented from AmSession.
References AmBasicSipDialog::getStatus(), and AmSession::setStopped().
void RtmpSession::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmSipDialog::bye(), AmSipDialog::getUASPendingInv(), AmBasicSipDialog::reply(), and AmSession::setStopped().
The documentation for this class was generated from the following files:
RtmpSession.h
RtmpSession.cpp