SEMS: tcp_trsp Class Reference
tcp_trsp Class Reference
Public Member Functions
tcp_trsp (tcp_server_socket *sock)
Protected Member Functions
void run ()
void on_stop ()
Constructor & Destructor Documentation
tcp_trsp::tcp_trsp (tcp_server_socket * sock)
See also:
transport
Member Function Documentation
void tcp_trsp::on_stop (void) [protected, virtual]
See also:
AmThread
Implements AmThread.
void tcp_trsp::run () [protected, virtual]
See also:
AmThread
Implements AmThread.
References trsp_socket::get_ip(), trsp_socket::get_port(), and trsp_socket::get_sd().
The documentation for this class was generated from the following files:
tcp_trsp.h
tcp_trsp.cpp