SEMS: AmPromptCollection Class Reference
AmPromptCollection Class Reference
manages AmAudioFiles with name for a session.
#include <AmPromptCollection.h>
Public Member Functions
int configureModule (AmConfigReader &cfg, vector< std::pair< string, string > > &announcements, const char *mod_name)
int setPrompt (const string &name, const string &filename, const char *mod_name)
bool hasPrompt (const string &name)
int addToPlaylist (const string &name, long sess_id, AmPlaylist &list, bool front=false, bool loop=false)
void cleanup (long sess_id)
Detailed Description
manages AmAudioFiles with name for a session.
Member Function Documentation
int AmPromptCollection::addToPlaylist (const string & name, long sess_id, AmPlaylist & list, bool front = false, bool loop = false)
add the announcement identified with
Parameters:
name to the playlist
References AmCachedAudioFile::loop.
Referenced by PinAuthConferenceDialog::onDtmf(), VoiceboxDialog::onDtmf(), CallBackDialog::onDtmf(), WebConferenceDialog::onDtmf(), AnnRecorderDialog::onDtmf(), PinAuthConferenceDialog::onSessionStart(), WebConferenceDialog::onSessionStart(), CallBackDialog::onSessionStart(), AnnRecorderDialog::onSessionStart(), CallGenDialog::onSessionStart(), PinAuthConferenceDialog::process(), WebConferenceDialog::process(), and AnnRecorderDialog::process().
void AmPromptCollection::cleanup (long sess_id)
cleanup allocated object of sess_id
int AmPromptCollection::configureModule (AmConfigReader & cfg, vector< std::pair< string, string > > & announcements, const char * mod_name)
get configuration for announcements from cfg, check for file existence
Parameters:
announcements : name, default file for announcement
References setPrompt().
bool AmPromptCollection::hasPrompt (const string & name)
check whether prompt exists
int AmPromptCollection::setPrompt (const string & name, const string & filename, const char * mod_name)
add a prompt with explicit filename
References file_exists().
Referenced by configureModule(), PinAuthConferenceFactory::onLoad(), and CallBackFactory::onLoad().
The documentation for this class was generated from the following files:
AmPromptCollection.h
AmPromptCollection.cpp