SEMS: AudioStreamData Class Reference
AudioStreamData Class Reference
Storage for several data items required to be held with one RTP stream for B2B media processing.
#include <AmB2BMedia.h>
Public Member Functions
AudioStreamData (AmB2BSession *session)
void changeSession (AmB2BSession *session)
void setDtmfSink (AmDtmfSink *dtmf_sink)
void clear ()
void stopStreamProcessing ()
void resumeStreamProcessing ()
void setRelayStream (AmRtpStream *other)
void setRelayPayloads (const SdpMedia &m, RelayController *ctrl)
void setRelayDestination (const string &connection_address, int port)
void setRelayPaused (bool paused)
bool initStream (PlayoutType playout_type, AmSdp &local_sdp, AmSdp &remote_sdp, int media_idx)
void processDtmfEvents ()
void sendDtmf (int event, unsigned int duration_ms)
int writeStream (unsigned long long ts, unsigned char *buffer, AudioStreamData &src)
void clearRTPTimeout ()
int getLocalPort ()
int getLocalRtcpPort ()
void setLocalIP (const string &ip)
AmRtpAudio * getStream ()
bool isInitialized ()
void getSdpOffer (int media_idx, SdpMedia &m)
void getSdpAnswer (int media_idx, const SdpMedia &offer, SdpMedia &answer)
void mute (bool set_mute)
void setReceiving (bool r)
void setInput (AmAudio *_in)
AmAudio * getInput ()
void setLogger (msg_logger *logger)
void debug ()
Detailed Description
Storage for several data items required to be held with one RTP stream for B2B media processing.
It has shown that there are more items to be remembered with one RTP stream so this class is an attempt to encapsulate them together and make the code better manageable (less duplicates - the same things were often done for A leg stuff and then for B leg stuff).
Constructor & Destructor Documentation
AudioStreamData::AudioStreamData (AmB2BSession * session)
Creates data based on associated signaling leg data.
Member Function Documentation
void AudioStreamData::changeSession (AmB2BSession * session)
we want to preserve existing streams (relay streams already set, ports already used in outgoing SDP
References AmRtpStream::changeSession(), and clear().
void AudioStreamData::clear ()
Frees all allocated data.
Stream and its peer (relay stream) must be removed from processing before calling this method! This method doesn't call stopStreamProcessing() itself because of the stream here is used as relay stream in the other leg. Before freeing current stream the other one has to be removed from processing as well.
Please note that the "in" member is freed - this need not to be the right thing but this will show once it will be really used.
Referenced by changeSession().
bool AudioStreamData::initStream (PlayoutType playout_type, AmSdp & local_sdp, AmSdp & remote_sdp, int media_idx)
initialize given stream for transcoding & regular audio processing
Returns false if the initialization failed (might happen for example if we are not able to handle the remote payloads by ourselves; anyway relaying could be still available in this case).
References AmRtpAudio::init(), AmRtpStream::setOnHold(), and AmRtpStream::setReceiving().
void AudioStreamData::processDtmfEvents () [inline]
Processes raw DTMF events in own queue.
References AmDtmfEventQueue::processEvents().
void AudioStreamData::resumeStreamProcessing ()
Returns stream from processing by AmRtpReceiver if it was already there.
References AmRtpStream::resumeReceiving().
void AudioStreamData::sendDtmf (int event, unsigned int duration_ms)
Sends DTMF
References AmRtpStream::sendDtmf().
void AudioStreamData::setDtmfSink (AmDtmfSink * dtmf_sink)
release old and store new DTMF sink
void AudioStreamData::setRelayPaused (bool paused)
set relay temporarily to paused (stream relation may still be up)
References AmRtpStream::disableRtpRelay(), and AmRtpStream::enableRtpRelay().
void AudioStreamData::setRelayPayloads (const SdpMedia & m, RelayController * ctrl)
computes and stores payloads that can be relayed based on the corresponding 'peer session' remote media line (i.e. what accepts the other remote end directly)
void AudioStreamData::setRelayStream (AmRtpStream * other)
Set relay stream and payload IDs to be relayed.
Removes the stream from AmRtpReceiver before updating and returns it back once done.
References AmRtpStream::disableRtpRelay(), AmRtpStream::enableRtpRelay(), AmRtpStream::setRAddr(), AmRtpStream::setRelayPayloads(), and AmRtpStream::setRelayStream().
void AudioStreamData::stopStreamProcessing ()
Removes stream from processing by AmRtpReceiver.
References AmRtpStream::stopReceiving().
int AudioStreamData::writeStream (unsigned long long ts, unsigned char * buffer, AudioStreamData & src)
Writes data to won stream. Data are read either from local alternative input (in) or from stream given by src parameter.
Buffer is just space used to read data before writing them, AmMediaProcessor buffer should be propagated here (see AmMediaSession)
References AmRtpAudio::get(), AmAudio::get(), AmRtpStream::getOnHold(), and AmRtpAudio::put().
The documentation for this class was generated from the following files:
AmB2BMedia.h
AmB2BMedia.cpp