SEMS: AmPlaylist Class Reference
AmPlaylist Class Reference
AmAudio component that plays entries serially.
#include <AmPlaylist.h>
Public Member Functions
AmPlaylist (AmEventQueue *q=NULL)
bool isEmpty ()
void addToPlaylist (AmPlaylistItem *item)
void addToPlayListFront (AmPlaylistItem *item)
void flush ()
Protected Member Functions
int read (unsigned int user_ts, unsigned int size)
int write (unsigned int user_ts, unsigned int size)
int get (unsigned long long system_ts, unsigned char *buffer, int output_sample_rate, unsigned int nb_samples)
int put (unsigned long long system_ts, unsigned char *buffer, int input_sample_rate, unsigned int size)
void close ()
Detailed Description
AmAudio component that plays entries serially.
This class can be plugged to the Input or Output of a session. Entries can be added or removed from the playlist, and the current entry is played until it is finished, then the next entry is played.
Member Function Documentation
void AmPlaylist::close () [protected, virtual]
from AmAudio
Reimplemented from AmAudio.
Referenced by SimpleConferenceDialog::onBye().
int AmPlaylist::get (unsigned long long system_ts, unsigned char * buffer, int output_sample_rate, unsigned int nb_samples) [protected, virtual]
override AmAudio
Reimplemented from AmAudio.
Reimplemented in AmAudioFrontlist.
References AmAudio::calcBytesToRead(), and AmAudio::get().
int AmPlaylist::put (unsigned long long system_ts, unsigned char * buffer, int input_sample_rate, unsigned int size) [protected, virtual]
Put some samples to the output stream.
Warning:
For packet based payloads / file formats, use:
           nb_sample = input buffer size / sample size of the reference format
whereby the format with/from which the codec works is the reference one.
Returns:
# bytes written, else -1 if error (0 is OK)
Reimplemented from AmAudio.
Reimplemented in AmAudioFrontlist.
References AmAudio::put().
int AmPlaylist::read (unsigned int user_ts, unsigned int size) [inline, protected, virtual]
Fake implement AmAudio's pure virtual methods
Implements AmAudio.
int AmPlaylist::write (unsigned int user_ts, unsigned int size) [inline, protected, virtual]
Puts 'size' bytes directly from stream (Write,Push).
Implements AmAudio.
The documentation for this class was generated from the following files:
AmPlaylist.h
AmPlaylist.cpp