SEMS: JukecallSession Class Reference
JukecallSession Class Reference
Public Types
enum JukeLeg1_state { JC_none = 0, JC_initial_announcement, JC_connect, JC_juke }
Public Member Functions
void onSessionStart ()
void process (AmEvent *event)
void onDtmf (int event, int duration_msec)
Protected Member Functions
AmB2ABCalleeSession * createCalleeSession ()
Member Function Documentation
void JukecallSession::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References int2str(), and AmB2ABCallerSession::relayEvent().
void JukecallSession::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmSipDialog::bye(), and AmAudioFile::open().
void JukecallSession::process (AmEvent * event) [virtual]
See also:
AmEventQueue
Reimplemented from AmB2ABSession.
References AmB2ABSession::connectSession().
The documentation for this class was generated from the following files:
Jukecall.h
Jukecall.cpp