SEMS: AmAudioFile Class Reference
AmAudioFile Class Reference
AmAudio implementation for file access.
#include <AmAudioFile.h>
Public Types
enum OpenMode { Read = 1, Write = 2 }
Public Member Functions
int open (const string &filename, OpenMode mode, bool is_tmp=false)
int fpopen (const string &filename, OpenMode mode, FILE *n_fp)
void rewind ()
void rewind (unsigned int msec)
void forward (unsigned int msec)
void close ()
void on_close ()
FILE * getfp ()
OpenMode getMode ()
int getDataSize ()
int getLength ()
string getMimeType ()
void setCloseOnDestroy (bool cod)
Data Fields
AmSharedVar< bool > loop
AmSharedVar< bool > autorewind
Protected Member Functions
int read (unsigned int user_ts, unsigned int size)
int write (unsigned int user_ts, unsigned int size)
virtual AmAudioFileFormat * fileName2Fmt (const string &name, const string &subtype)
string getSubtype (string &filename)
int fpopen_int (const string &filename, OpenMode mode, FILE *n_fp, const string &subtype)
Protected Attributes
FILE * fp
long begin
amci_inoutfmt_t * iofmt
int open_mode
int data_size
bool on_close_done
bool close_on_exit
Detailed Description
AmAudio implementation for file access.
Member Enumeration Documentation
enum AmAudioFile::OpenMode
Open mode.
Member Function Documentation
void AmAudioFile::close () [virtual]
Closes the file.
Reimplemented from AmAudio.
References fp, and on_close().
Referenced by fpopen_int(), AnnRecorderDialog::onDtmf(), EarlyRecordDialog::onSessionStart(), and open().
AmAudioFileFormat * AmAudioFile::fileName2Fmt (const string & name, const string & subtype) [protected, virtual]
Returns:
a file format from file name. (ex: '1234.wav')
Reimplemented in AmPrecodedFileInstance.
References file_extension(), AmPlugIn::fileFormat(), iofmt, amci_inoutfmt_t::name, AmPlugIn::subtype(), and amci_subtype_t::type.
Referenced by fpopen_int().
void AmAudioFile::forward (unsigned int msec)
skip forward some milliseconds.
References data_size, AmAudio::fmt, and fp.
int AmAudioFile::fpopen_int (const string & filename, OpenMode mode, FILE * n_fp, const string & subtype) [protected]
internal function for opening the file
References amci_file_desc_t::buffer_full_thresh, amci_file_desc_t::buffer_size, amci_file_desc_t::buffer_thresh, amci_file_desc_t::channels, AmAudioFormat::channels, close(), data_size, amci_file_desc_t::data_size, fileName2Fmt(), AmAudio::fmt, fp, AmAudioFormat::getRate(), AmAudioFileFormat::getSubtypeId(), iofmt, amci_inoutfmt_t::open, open_mode, amci_file_desc_t::rate, AmAudioFormat::setRate(), and amci_file_desc_t::subtype.
Referenced by open().
int AmAudioFile::getDataSize () [inline]
Gets data size in the current file
References data_size.
FILE* AmAudioFile::getfp () [inline]
be carefull with this one ;-)
References fp.
int AmAudioFile::getLength ()
Gets length of the current file in ms
References data_size, and AmAudio::fmt.
string AmAudioFile::getMimeType ()
Returns:
MIME type corresponding to the audio file.
References amci_inoutfmt_t::email_content_type, and iofmt.
string AmAudioFile::getSubtype (string & filename) [protected]
Returns:
subtype ID and trim filename if subtype embedded
Referenced by open().
void AmAudioFile::on_close ()
Executes the handler's on_close.
References AmAudioFormat::channels, data_size, AmAudio::fmt, fp, AmAudioFormat::getRate(), AmAudioFileFormat::getSubtypeId(), iofmt, amci_inoutfmt_t::on_close, and open_mode.
Referenced by close().
int AmAudioFile::open (const string & filename, OpenMode mode, bool is_tmp = false)
Opens a file.
In read mode: sets input format.
In write mode:
needs output format set.
If file name already exists, the file will be overwritten.
Parameters:
filename Name of the file.
mode Open mode.
Returns:
0 if everything's OK
See also:
OpenMode
References close(), fpopen_int(), and getSubtype().
Referenced by MyJukeboxDialog::onDtmf(), DtmfTesterDialog::onDtmf(), AnnRecorderDialog::onDtmf(), EarlyRecordDialog::onEarlySessionStart(), EarlyAnnounceDialog::onEarlySessionStart(), MyAnnounceAppDialog::onSessionStart(), EarlyRecordDialog::onSessionStart(), AnnounceCallerDialog::onSessionStart(), AnnouncementDialog::onSessionStart(), C2DCallerDialog::onSessionStart(), JukecallSession::onSessionStart(), ServiceLineCallerDialog::onSessionStart(), and AnswerMachineDialog::onSessionStart().
int AmAudioFile::read (unsigned int user_ts, unsigned int size) [protected, virtual]
See also:
AmAudio::read
Implements AmAudio.
References data_size, fp, rewind(), and AmAudio::samples.
void AmAudioFile::rewind ()
Rewind the file to beginning.
References fp.
Referenced by AmAudioMixIn::get(), and read().
void AmAudioFile::rewind (unsigned int msec)
Rewind the file some milliseconds.
References AmAudio::fmt, and fp.
int AmAudioFile::write (unsigned int user_ts, unsigned int size) [protected, virtual]
See also:
AmAudio::write
Implements AmAudio.
References data_size, fp, and AmAudio::samples.
Field Documentation
int AmAudioFile::data_size [protected]
Size of datas having been read/written until now.
Referenced by forward(), fpopen_int(), getDataSize(), getLength(), on_close(), read(), and write().
FILE* AmAudioFile::fp [protected]
Pointer to the file opened as last.
Referenced by close(), forward(), fpopen_int(), getfp(), on_close(), read(), rewind(), and write().
amci_inoutfmt_t* AmAudioFile::iofmt [protected]
Format of that file.
See also:
fp, open().
Referenced by fileName2Fmt(), fpopen_int(), getMimeType(), and on_close().
int AmAudioFile::open_mode [protected]
Open mode.
Referenced by fpopen_int(), and on_close().
The documentation for this class was generated from the following files:
AmAudioFile.h
AmAudioFile.cpp