SEMS: AmB2BSession Class Reference
AmB2BSession Class Reference
Base class for Sessions in B2BUA mode.
#include <AmB2BSession.h>
Public Types
enum RTPRelayMode { RTP_Direct, RTP_Relay, RTP_Transcoding }
Public Member Functions
void relayError (const string &method, unsigned cseq, bool forward, int sip_code, const char *reason)
void relayError (const string &method, unsigned cseq, bool forward, int err_code)
virtual void setOtherId (const string &n_other_id)
virtual const string & getOtherId () const
virtual int relayEvent (AmEvent *ev)
void set_sip_relay_only (bool r)
virtual void setRtpRelayMode (RTPRelayMode mode)
RTPRelayMode getRtpRelayMode () const
bool getRtpRelayForceSymmetricRtp () const
bool getEnableDtmfTranscoding () const
bool getEnableDtmfRtpFiltering () const
bool getEnableDtmfRtpDetection () const
void getLowFiPLs (vector< SdpPayload > &lowfi_payloads) const
virtual void setRtpInterface (int relay_interface)
virtual void setRtpRelayForceSymmetricRtp (bool force_symmetric)
void setRtpRelayTransparentSeqno (bool transparent)
void setRtpRelayTransparentSSRC (bool transparent)
void setEnableDtmfTranscoding (bool enable)
void setEnableDtmfRtpFiltering (bool enable)
void setEnableDtmfRtpDetection (bool enable)
void setLowFiPLs (const vector< SdpPayload > &lowfi_payloads)
bool getRtpRelayTransparentSeqno ()
bool getRtpRelayTransparentSSRC ()
virtual void setMediaSession (AmB2BMedia *new_session)
AmB2BMedia * getMediaSession ()
virtual void computeRelayMask (const SdpMedia &m, bool &enable, PayloadMask &mask)
Protected Member Functions
virtual bool saveSessionDescription (const AmMimeBody &body)
virtual bool updateSessionDescription (const AmMimeBody &body)
virtual void clear_other ()
int relaySip (const AmSipRequest &req)
int relaySip (const AmSipRequest &orig, const AmSipReply &reply)
virtual void terminateLeg ()
virtual void terminateOtherLeg ()
virtual void updateUACTransCSeq (unsigned int old_cseq, unsigned int new_cseq)
void onSipRequest (const AmSipRequest &req)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
void onRequestSent (const AmSipRequest &req)
void onReplySent (const AmSipRequest &req, const AmSipReply &reply)
void onInvite2xx (const AmSipReply &reply)
int onSdpCompleted (const AmSdp &local_sdp, const AmSdp &remote_sdp)
void onRemoteDisappeared (const AmSipReply &reply)
void onRtpTimeout ()
void onSessionTimeout ()
void onNoAck (unsigned int cseq)
int sendEstablishedReInvite ()
bool refresh (int flags=0)
void process (AmEvent *event)
void finalize ()
virtual void onB2BEvent (B2BEvent *ev)
virtual void onOtherBye (const AmSipRequest &req)
virtual bool onOtherReply (const AmSipReply &reply)
AmB2BSession (const string &other_local_tag="", AmSipDialog *p_dlg=NULL, AmSipSubscription *p_subs=NULL)
void clearRtpReceiverRelay ()
void updateRelayStreams (const AmMimeBody &body, AmSdp &parser_sdp)
void updateLocalBody (AmMimeBody &body)
virtual void updateLocalSdp (AmSdp &sdp)
bool getMappedReferID (unsigned int refer_id, unsigned int &mapped_id) const
virtual void insertMappedReferID (unsigned int refer_id, unsigned int mapped_id)
Protected Attributes
bool sip_relay_only
bool a_leg
TransMap relayed_req
TransMap recvd_req
unsigned int est_invite_cseq
unsigned int est_invite_other_cseq
AmSipSubscription * subs
AmMimeBody established_body
uint32_t body_hash
RTPRelayMode rtp_relay_mode
bool rtp_relay_force_symmetric_rtp
bool rtp_relay_transparent_seqno
bool rtp_relay_transparent_ssrc
bool enable_dtmf_transcoding
bool enable_dtmf_rtp_filtering
bool enable_dtmf_rtp_detection
vector< SdpPayload > lowfi_payloads
Detailed Description
Base class for Sessions in B2BUA mode.
It has two legs as independent sessions: Callee- and caller-leg.
Member Function Documentation
void AmB2BSession::clear_other () [protected, virtual]
reset relation with other leg
void AmB2BSession::clearRtpReceiverRelay () [protected]
clear our and the other side's RTP streams from RTPReceiver
References AmB2BMedia::releaseReference(), rtp_relay_mode, and AmB2BMedia::stop().
Referenced by CallLeg::changeRtpMode(), CallLeg::disconnect(), DSMCall::onBye(), CallLeg::onBye(), AmB2BCallerSession::onBye(), CallLeg::onRemoteDisappeared(), AmB2BCallerSession::onRemoteDisappeared(), and terminateLeg().
void AmB2BSession::finalize () [protected, virtual]
See also:
AmEventQueue
Reimplemented from AmSession.
References relayed_req.
bool AmB2BSession::getMappedReferID (unsigned int refer_id, unsigned int & mapped_id) const [protected]
Returns true and sets mapped_id if refer_id corresponds to an existing refer event subscription which has been relayed.
Referenced by onSipRequest().
RTPRelayMode AmB2BSession::getRtpRelayMode () const [inline]
link RTP streams of other_session to our streams
References rtp_relay_mode.
Referenced by CallLeg::CallLeg(), CallLeg::disconnect(), SBCCallLeg::onDtmf(), CallLeg::readStreams(), and CallLeg::writeStreams().
void AmB2BSession::onB2BEvent (B2BEvent * ev) [protected, virtual]
B2BEvent handler
Reimplemented in AmB2BCalleeSession, AmB2BCallerSession, CallLeg, and C2DCallerDialog.
References AmMimeBody::empty(), est_invite_cseq, AmMimeBody::getCTStr(), AmBasicSipDialog::getStatus(), AmSipDialog::getUACInvTransPending(), onOtherBye(), recvd_req, relaySip(), sendEstablishedReInvite(), terminateLeg(), terminateOtherLeg(), and updateSessionDescription().
Referenced by process().
void AmB2BSession::onInvite2xx (const AmSipReply & reply) [protected, virtual]
2xx reply has been received for an INVITE transaction
Reimplemented from AmSession.
Reimplemented in AmB2BCallerSession, CallLeg, and C2DCallerDialog.
References relayed_req.
void AmB2BSession::onNoAck (unsigned int ack_cseq) [protected, virtual]
Hook called when a UAS INVITE transaction did not receive the ACK
Reimplemented from AmSession.
Reimplemented in CallLeg, and DSMCall.
References terminateOtherLeg().
void AmB2BSession::onOtherBye (const AmSipRequest & req) [protected, virtual]
handle BYE on other leg
Reimplemented in CallLeg, SBCCallLeg, IvrDialog, DSMCall, and MyCCDialog.
References terminateLeg().
Referenced by onB2BEvent().
bool AmB2BSession::onOtherReply (const AmSipReply & reply) [protected, virtual]
Reply received from other leg has been replied
Returns:
true if reply was processed (should be absorbed)
false if reply was not processed
Reimplemented in IvrDialog, DSMCall, and MyCCDialog.
References AmSession::setStopped().
Referenced by AmB2BCallerSession::onB2BEvent().
void AmB2BSession::onRemoteDisappeared (const AmSipReply &) [protected, virtual]
remote side is unreachable - 408/481 reply received
Reimplemented from AmSession.
Reimplemented in AmB2BCallerSession, CallLeg, SBCCallLeg, and DSMCall.
References AmBasicSipDialog::getStatus(), and terminateOtherLeg().
void AmB2BSession::onReplySent (const AmSipRequest & req, const AmSipReply & reply) [protected, virtual]
Hook called after a reply has been sent
Reimplemented from AmBasicSipEventHandler.
References recvd_req, and subs.
void AmB2BSession::onRequestSent (const AmSipRequest & req) [protected, virtual]
Hook called after a request has been sent
Reimplemented from AmBasicSipEventHandler.
References subs.
void AmB2BSession::onRtpTimeout () [protected, virtual]
This callback is called if RTP timeout encountered
Reimplemented from AmSession.
Reimplemented in CallLeg, IvrDialog, and DSMCall.
References terminateOtherLeg().
int AmB2BSession::onSdpCompleted (const AmSdp & offer, const AmSdp & answer) [protected, virtual]
Hook called when an SDP OA transaction has been completed
Reimplemented from AmSession.
Reimplemented in CallLeg, IvrDialog, and DSMCall.
References rtp_relay_mode, sip_relay_only, and AmB2BMedia::updateStreams().
void AmB2BSession::onSessionTimeout () [protected, virtual]
This callback is called if session timeout encountered (session timers)
Reimplemented from AmSession.
Reimplemented in CallLeg, and DSMCall.
References terminateOtherLeg().
void AmB2BSession::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_dlg_status) [protected, virtual]
Entry point for SIP Replies
Reimplemented from AmSession.
Reimplemented in CallLeg, SBCCallLeg, DSMCallCalleeSession, IvrDialog, and DSMCall.
References est_invite_cseq, AmMimeBody::getCTStr(), AmSession::getLocalTag(), int2str(), relayed_req, relayEvent(), subs, AmSipSubscription::subscriptionExists(), and AmSession::updateRefreshMethod().
void AmB2BSession::onSipRequest (const AmSipRequest & req) [protected, virtual]
Entry point for SIP Requests
Reimplemented from AmSession.
Reimplemented in CallLeg, SBCCallLeg, IvrDialog, and DSMCall.
References get_header_param(), getMappedReferID(), int2str(), AmSession::onBye(), recvd_req, relayEvent(), AmBasicSipDialog::reply(), sip_relay_only, str2int(), strip_header_params(), subs, and AmSession::updateRefreshMethod().
void AmB2BSession::process (AmEvent * event) [protected, virtual]
See also:
AmEventQueue
Reimplemented from AmSession.
Reimplemented in SBCCallLeg, DSMCall, EarlyAnnounceDialog, C2DCallerDialog, AnnounceCallerDialog, MyCCDialog, and PySemsB2BDialog.
References onB2BEvent(), and subs.
bool AmB2BSession::refresh (int flags = 0) [protected, virtual]
do session refresh
Reimplemented from AmSession.
References AmBasicSipDialog::getStatus(), AmSipDialog::getUACInvTransPending(), AmSession::refresh_method, and sendEstablishedReInvite().
int AmB2BSession::relayEvent (AmEvent * ev) [virtual]
Relay one event to the other side.
Returns:
0 on success
Reimplemented in AmB2BCallerSession, and SBCCallLeg.
References AmSessionContainer::postEvent().
Referenced by CallLeg::changeRtpMode(), onSipReply(), onSipRequest(), and terminateOtherLeg().
int AmB2BSession::relaySip (const AmSipRequest & req) [protected]
send a relayed SIP Request
References AmMimeBody::empty(), int2str(), relayed_req, saveSessionDescription(), AmSipDialog::send_200_ack(), AmBasicSipDialog::sendRequest(), and updateLocalBody().
Referenced by onB2BEvent().
int AmB2BSession::relaySip (const AmSipRequest & orig, const AmSipReply & reply) [protected]
send a relayed SIP Reply
References AmMimeBody::empty(), int2str(), AmBasicSipDialog::reply(), saveSessionDescription(), and updateLocalBody().
bool AmB2BSession::saveSessionDescription (const AmMimeBody & body) [protected, virtual]
save current session description (SDP)
References body_hash, established_body, AmMimeBody::getCTStr(), AmMimeBody::getLen(), AmMimeBody::getPayload(), and AmMimeBody::hasContentType().
Referenced by AmB2BCalleeSession::onB2BEvent(), and relaySip().
int AmB2BSession::sendEstablishedReInvite () [protected]
send re-INVITE with established session description
Returns:
0 on success
References AmMimeBody::empty(), established_body, AmSipDialog::reinvite(), and updateLocalBody().
Referenced by onB2BEvent(), and refresh().
void AmB2BSession::setRtpRelayMode (RTPRelayMode mode) [virtual]
set RTP relay mode (possibly initiaze by given INVITE)
References AmSession::getLocalTag(), and rtp_relay_mode.
Referenced by CallLeg::CallLeg(), CallLeg::changeRtpMode(), and AmB2BCallerSession::initializeRTPRelay().
void AmB2BSession::terminateLeg () [protected, virtual]
Terminate our leg and forget the other.
Reimplemented in AmB2BCallerSession, and CallLeg.
References AmSipDialog::bye(), clearRtpReceiverRelay(), and AmSession::setStopped().
Referenced by onB2BEvent(), and onOtherBye().
void AmB2BSession::terminateOtherLeg () [protected, virtual]
Terminate the other leg and forget it.
Reimplemented in AmB2BCallerSession, and CallLeg.
References relayEvent().
Referenced by onB2BEvent(), onNoAck(), onRemoteDisappeared(), onRtpTimeout(), and onSessionTimeout().
void AmB2BSession::updateLocalBody (AmMimeBody & body) [protected]
replace connection with our address
References AmMimeBody::getCTStr(), AmMimeBody::getPayload(), AmMimeBody::hasContentType(), AmMimeBody::parse(), AmSdp::parse(), AmSdp::print(), and updateLocalSdp().
Referenced by AmB2BCalleeSession::onB2BEvent(), relaySip(), and sendEstablishedReInvite().
void AmB2BSession::updateLocalSdp (AmSdp & sdp) [protected, virtual]
Called when SDP relayed from other leg should be sent to the remote party. Default implementation updates connection address and ports.
Reimplemented in CallLeg, and SBCCallLeg.
References AmB2BMedia::replaceConnectionAddress(), and rtp_relay_mode.
Referenced by updateLocalBody().
void AmB2BSession::updateRelayStreams (const AmMimeBody & body, AmSdp & parser_sdp) [protected]
update remote connection in relay_streams
bool AmB2BSession::updateSessionDescription (const AmMimeBody & body) [protected, virtual]
Returns:
whether session description (SDP) has changed
References body_hash, established_body, AmMimeBody::getCTStr(), AmMimeBody::getLen(), AmMimeBody::getPayload(), and AmMimeBody::hasContentType().
Referenced by onB2BEvent(), and AmB2BCallerSession::onB2BEvent().
void AmB2BSession::updateUACTransCSeq (unsigned int old_cseq, unsigned int new_cseq) [protected, virtual]
See also:
AmSession
Reimplemented from AmSession.
Reimplemented in C2DCallerDialog.
References est_invite_cseq, and relayed_req.
Referenced by DSMCallCalleeSession::onSipReply(), and SBCCallLeg::onSipReply().
Field Documentation
uint32_t AmB2BSession::body_hash [protected]
hash of body (from o-line)
Referenced by saveSessionDescription(), and updateSessionDescription().
bool AmB2BSession::enable_dtmf_rtp_detection [protected]
detect DTMF through RTP DTMF (2833 / 4733) packets
Referenced by AmB2BCallerSession::initializeRTPRelay().
bool AmB2BSession::enable_dtmf_rtp_filtering [protected]
filter RTP DTMF (2833 / 4733) packets
Referenced by AmB2BCallerSession::initializeRTPRelay().
bool AmB2BSession::enable_dtmf_transcoding [protected]
If true, transcoded audio is injected into the inband DTMF detector
Referenced by AmB2BCallerSession::initializeRTPRelay().
unsigned int AmB2BSession::est_invite_cseq [protected]
CSeq of the INVITE that established this call
Referenced by CallLeg::disconnect(), onB2BEvent(), AmB2BCalleeSession::onB2BEvent(), SBCCallLeg::onInvite(), CallLeg::onInvite(), AmB2BCallerSession::onInvite(), C2DCallerDialog::onInvite2xx(), AmB2BCallerSession::onInvite2xx(), onSipReply(), CallLeg::onSipReply(), C2DCallerDialog::updateUACTransCSeq(), and updateUACTransCSeq().
AmMimeBody AmB2BSession::established_body [protected]
body of established session
Referenced by CallLeg::addCallee(), AmB2BCallerSession::onB2BEvent(), saveSessionDescription(), sendEstablishedReInvite(), and updateSessionDescription().
vector<SdpPayload> AmB2BSession::lowfi_payloads [protected]
Low fidelity payloads for which inband DTMF transcoding should be used
Referenced by CallLeg::CallLeg(), and AmB2BCallerSession::initializeRTPRelay().
TransMap AmB2BSession::recvd_req [protected]
Requests received for relaying
Referenced by DSMCall::B2BaddReceivedRequest(), onB2BEvent(), CallLeg::onInvite(), onReplySent(), onSipRequest(), and EarlyAnnounceDialog::process().
TransMap AmB2BSession::relayed_req [protected]
Requests which have been relayed from the other leg and sent as SIP
Referenced by CallLeg::disconnect(), finalize(), AmB2BCalleeSession::onB2BEvent(), onInvite2xx(), DSMCallCalleeSession::onSipReply(), SBCCallLeg::onSipReply(), onSipReply(), CallLeg::onSipReply(), relaySip(), and updateUACTransCSeq().
bool AmB2BSession::rtp_relay_force_symmetric_rtp [protected]
force symmetric RTP
RTPRelayMode AmB2BSession::rtp_relay_mode [protected]
flag to enable RTP relay mode
Referenced by CallLeg::changeRtpMode(), clearRtpReceiverRelay(), CallLeg::debug(), getRtpRelayMode(), AmB2BCallerSession::initializeRTPRelay(), onSdpCompleted(), CallLeg::replaceExistingLeg(), setRtpRelayMode(), and updateLocalSdp().
bool AmB2BSession::rtp_relay_transparent_seqno [protected]
transparent seqno for RTP relay
bool AmB2BSession::rtp_relay_transparent_ssrc [protected]
transparent SSRC for RTP relay
bool AmB2BSession::sip_relay_only [protected]
Tell if the session should process SIP request itself or only relay them (B2B mode).
Referenced by CallLeg::onB2BEvent(), AmB2BCallerSession::onB2BEvent(), onSdpCompleted(), SBCCallLeg::onSipRequest(), and onSipRequest().
AmSipSubscription* AmB2BSession::subs [protected]
SUBSCRIBE/NOTIFY handling
Referenced by SBCCallLeg::onInvite(), onReplySent(), onRequestSent(), onSipReply(), onSipRequest(), and process().
The documentation for this class was generated from the following files:
AmB2BSession.h
AmB2BSession.cpp