SEMS: PinAuthConferenceFactory Class Reference
PinAuthConferenceFactory Class Reference
Public Member Functions
PinAuthConferenceFactory (const string &_app_name)
AmSession * onInvite (const AmSipRequest &, const string &app_name, const map< string, string > &app_params)
AmSession * onInvite (const AmSipRequest &req, const string &app_name, AmArg &session_params)
int onLoad ()
Static Public Attributes
static string DigitsDir
static PlayoutType m_PlayoutType = ADAPTIVE_PLAYOUT
Member Function Documentation
AmSession * PinAuthConferenceFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
AmSession * PinAuthConferenceFactory::onInvite (const AmSipRequest & req, const string & app_name, AmArg & session_params) [virtual]
Creates a dialog state on new UAC request.
Parameters:
session_params parameters passed to the new session by the caller.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Reimplemented from AmSessionFactory.
int PinAuthConferenceFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AM_PROMPT_START, AmSessionFactory::configureModule(), int2str(), AmConfig::ModConfigPath, and AmPromptCollection::setPrompt().
The documentation for this class was generated from the following files:
PinAuthConference.h
PinAuthConference.cpp