SEMS: AmMimeBody Class Reference
AmMimeBody Class Reference
Public Types
typedef list< AmMimeBody * > Parts
Public Member Functions
AmMimeBody ()
AmMimeBody (const AmMimeBody &body)
~AmMimeBody ()
const AmMimeBody & operator= (const AmMimeBody &r_body)
int parse (const string &content_type, const unsigned char *buf, unsigned int len)
void setPayload (const unsigned char *buf, unsigned int len)
void setHeaders (const string &hdrs)
AmMimeBody * addPart (const string &content_type)
int deletePart (const string &content_type)
string getCTStr () const
string getCTHdr () const
const Parts & getParts () const
const string & getHeaders () const
const unsigned char * getPayload () const
unsigned int getLen () const
bool empty () const
bool isContentType (const string &content_type) const
AmMimeBody * hasContentType (const string &content_type)
const AmMimeBody * hasContentType (const string &content_type) const
void print (string &buf) const
const AmContentType & getContentType ()
void setContentType (const AmContentType &_ct)
void addPart (const AmMimeBody &part)
Constructor & Destructor Documentation
AmMimeBody::AmMimeBody ()
Empty constructor
Referenced by AmMimeBody(), and operator=().
AmMimeBody::AmMimeBody (const AmMimeBody & body)
Deep-copy constructor
References AmMimeBody(), and setPayload().
AmMimeBody::~AmMimeBody ()
Destuctor
Member Function Documentation
AmMimeBody * AmMimeBody::addPart (const string & content_type)
Add a new part to this body, possibly converting to multi-part if necessary.
Returns:
a pointer to the new empty part.
Referenced by EarlyAnnounceDialog::onInvite(), DSMCall::onSdpCompleted(), IvrDialog::onSdpCompleted(), AmSession::sendInvite(), and AmSession::sendReinvite().
int AmMimeBody::deletePart (const string & content_type)
Delete a body part, converting resulting body to single-part if necessary.
bool AmMimeBody::empty () const
Returns:
true if no payload assigned and no sub-parts available
Referenced by AmB2BSession::onB2BEvent(), AmB2BCallerSession::onB2BEvent(), AmSipSubscriptionDialog::onNotify(), AmOfferAnswer::onRequestIn(), DSMCall::onRinging(), AmB2BSession::relaySip(), _SipCtrlInterface::send(), and AmB2BSession::sendEstablishedReInvite().
string AmMimeBody::getCTHdr () const [inline]
Get content-type with parameters
References AmContentType::getHdr().
Referenced by _SipCtrlInterface::send().
string AmMimeBody::getCTStr () const [inline]
Get content-type without any parameters
References AmContentType::getStr().
Referenced by _SipCtrlInterface::handle_sip_request(), AmB2BSession::onB2BEvent(), DSMCallCalleeSession::onSipReply(), SBCCallLeg::onSipReply(), AmB2BSession::onSipReply(), SBCCallLeg::relayEvent(), AmB2BSession::saveSessionDescription(), AmB2BSession::updateLocalBody(), and AmB2BSession::updateSessionDescription().
const string& AmMimeBody::getHeaders () const [inline]
Returns:
the sub-part headers
unsigned int AmMimeBody::getLen () const [inline]
Returns:
the payload length of this part. in case of multi-part, 0 is returned.
Referenced by AnnounceTransferDialog::onSipRequest(), AmSession::onSipRequest(), AmB2BSession::saveSessionDescription(), and AmB2BSession::updateSessionDescription().
const Parts& AmMimeBody::getParts () const [inline]
Returns:
the list of sub-parts
const unsigned char* AmMimeBody::getPayload () const [inline]
Returns:
a pointer to the payload of this part. in case of multi-part, NULL is returned.
Referenced by CallLeg::onSipReply(), AnnounceTransferDialog::onSipRequest(), AmSession::onSipRequest(), AmB2BSession::saveSessionDescription(), AmB2BSession::updateLocalBody(), and AmB2BSession::updateSessionDescription().
AmMimeBody * AmMimeBody::hasContentType (const string & content_type)
Returns:
a pointer to a part of the coresponding content-type (if available). This could be a pointer to this body.
Referenced by AmOfferAnswer::onRequestIn(), DSMCall::onSdpCompleted(), IvrDialog::onSdpCompleted(), CallLeg::onSipReply(), AmSession::onSipRequest(), AmB2BSession::saveSessionDescription(), AmB2BSession::updateLocalBody(), and AmB2BSession::updateSessionDescription().
const AmMimeBody * AmMimeBody::hasContentType (const string & content_type) const
Returns:
a const pointer to a part of the coresponding content-type (if available). This could be a pointer to this body.
bool AmMimeBody::isContentType (const string & content_type) const
Returns:
true if this part has the provided content-type
Referenced by AnnounceTransferDialog::onSipRequest().
const AmMimeBody & AmMimeBody::operator= (const AmMimeBody & r_body)
Deep copy operator
References AmMimeBody(), and setPayload().
int AmMimeBody::parse (const string & content_type, const unsigned char * buf, unsigned int len)
Parse a body (single & multi-part)
Referenced by AmB2BSession::updateLocalBody().
void AmMimeBody::print (string & buf) const
Print the body including sub-parts suitable for sending within the body of a SIP message.
Referenced by _SipCtrlInterface::send().
void AmMimeBody::setHeaders (const string & hdrs)
Set part headers (intended for sub-parts)
void AmMimeBody::setPayload (const unsigned char * buf, unsigned int len)
Set the payload of this body
Referenced by AmMimeBody(), DSMCall::onSdpCompleted(), IvrDialog::onSdpCompleted(), and operator=().
The documentation for this class was generated from the following files:
AmMimeBody.h
AmMimeBody.cpp