SEMS: AmSIPRegistration Class Reference
AmSIPRegistration Class Reference
Public Types
enum RegistrationState { RegisterPending = 0, RegisterActive, RegisterExpired }
Public Member Functions
AmSIPRegistration (const string &handle, const SIPRegistrationInfo &info, const string &sess_link)
void setRegistrationInfo (const SIPRegistrationInfo &_info)
void setSessionEventHandler (AmSessionEventHandler *new_seh)
void setExpiresInterval (unsigned int desired_expires)
bool doRegistration ()
bool doUnregister ()
bool timeToReregister (time_t now_sec)
bool registerExpired (time_t now_sec)
void onRegisterExpired ()
void onRegisterSendTimeout ()
bool registerSendTimeout (time_t now_sec)
void onSendRequest (AmSipRequest &req, int &flags)
void onSendReply (const AmSipRequest &req, AmSipReply &reply, int &flags)
AmBasicSipDialog * getDlg ()
UACAuthCred * getCredentials ()
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
RegistrationState getState ()
unsigned int getExpiresLeft ()
time_t getExpiresTS ()
bool getUnregistering ()
SIPRegistrationInfo & getInfo ()
const string & getEventSink ()
const string & getHandle ()
Data Fields
bool active
bool remove
bool waiting_result
bool unregistering
Member Function Documentation
unsigned int AmSIPRegistration::getExpiresLeft ()
return the expires left for the registration
time_t AmSIPRegistration::getExpiresTS ()
return the expires TS for the registration
AmSIPRegistration::RegistrationState AmSIPRegistration::getState ()
return the state of the registration
References active, and waiting_result.
void AmSIPRegistration::onSendReply (const AmSipRequest & req, AmSipReply & reply, int & flags) [virtual]
Hook called before a reply is sent
Reimplemented from AmBasicSipEventHandler.
void AmSIPRegistration::onSendRequest (AmSipRequest & req, int & flags) [virtual]
Hook called before a request is sent
Reimplemented from AmBasicSipEventHandler.
void AmSIPRegistration::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_status) [virtual]
Hook called when a reply has been received
Reimplemented from AmBasicSipEventHandler.
References active, AmBasicSipDialog::getContactUri(), AmUriParser::parse_contact(), str2i(), unregistering, and waiting_result.
Field Documentation
bool AmSIPRegistration::active
is this registration registered?
Referenced by getState(), and onSipReply().
bool AmSIPRegistration::remove
should this registration be removed from container?
bool AmSIPRegistration::unregistering
are we unregistering?
Referenced by onSipReply().
bool AmSIPRegistration::waiting_result
are we waiting for the response to a register?
Referenced by getState(), and onSipReply().
The documentation for this class was generated from the following files:
AmSipRegistration.h
AmSipRegistration.cpp