SEMS: AnnounceCallerDialog Class Reference
AnnounceCallerDialog Class Reference
Session logic implementation of A leg in announce_b2b sessions.
#include <AnnounceB2B.h>
Public Member Functions
AnnounceCallerDialog (const string &filename)
void process (AmEvent *event)
void onInvite (const AmSipRequest &req)
void onSessionStart ()
Detailed Description
Session logic implementation of A leg in announce_b2b sessions.
Member Function Documentation
void AnnounceCallerDialog::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmB2BCallerSession.
void AnnounceCallerDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmAudioFile::open(), and AmSession::setReceiving().
void AnnounceCallerDialog::process (AmEvent * event) [virtual]
See also:
AmEventQueue
Reimplemented from AmB2BSession.
References AmMediaProcessor::removeSession().
The documentation for this class was generated from the following files:
AnnounceB2B.h
AnnounceB2B.cpp