SEMS: _SipCtrlInterface Class Reference
_SipCtrlInterface Class Reference
Public Member Functions
int load ()
int run ()
void stop ()
void cleanup ()
void handle_sip_request (const trans_ticket &tt, sip_msg *msg)
void handle_sip_reply (const string &dialog_id, sip_msg *msg)
void handle_reply_timeout (AmSipTimeoutEvent::EvType evt, sip_trans *tr, trans_bucket *buk=0)
Static Public Member Functions
static int send (AmSipRequest &req, const string &dialog_id, const string &next_hop="", int outbound_interface=-1, unsigned int flags=0, msg_logger *logger=NULL)
static int send (const AmSipReply &rep, const string &dialog_id, msg_logger *logger=NULL)
static int cancel (trans_ticket *tt, const string &dialog_id, unsigned int inv_cseq, const string &hdrs)
Static Public Attributes
static string outbound_host
static unsigned int outbound_port
static bool log_parsed_messages = true
static int udp_rcvbuf = -1
Friends
class udp_trsp
Member Function Documentation
int _SipCtrlInterface::cancel (trans_ticket * tt, const string & dialog_id, unsigned int inv_cseq, const string & hdrs) [static]
CANCELs an INVITE transaction.
Parameters:
tt transaction ticket of the request to cancel.
Referenced by send().
void _SipCtrlInterface::handle_sip_request (const trans_ticket & tt, sip_msg * msg) [virtual]
From sip_ua
Implements sip_ua.
References AmMimeBody::getCTStr().
int _SipCtrlInterface::send (AmSipRequest & req, const string & dialog_id, const string & next_hop = "", int outbound_interface = -1, unsigned int flags = 0, msg_logger * logger = NULL) [static]
Sends a SIP request.
Parameters:
req The request to send. If the request creates a transaction, its ticket is written into req.tt.
References cancel(), AmMimeBody::empty(), AmMimeBody::getCTHdr(), int2str(), AmConfig::MaxForwards, and AmMimeBody::print().
int _SipCtrlInterface::send (const AmSipReply & rep, const string & dialog_id, msg_logger * logger = NULL) [static]
Sends a SIP reply.
Parameters:
rep The reply to be sent. 'rep.tt' should be set to transaction ticket included in the SIP request.
References AmMimeBody::empty(), AmMimeBody::getCTHdr(), and AmMimeBody::print().
The documentation for this class was generated from the following files:
SipCtrlInterface.h
SipCtrlInterface.cpp