SEMS: AmThread Class Reference
AmThread Class Reference
C++ Wrapper class for pthread.
#include <AmThread.h>
Public Member Functions
virtual void onIdle ()
void start ()
void stop ()
bool is_stopped ()
void join ()
void cancel ()
int setRealtime ()
Data Fields
unsigned long _pid
Protected Member Functions
virtual void run ()=0
virtual void on_stop ()=0
Detailed Description
C++ Wrapper class for pthread.
Member Function Documentation
void AmThread::cancel ()
kill the thread (if pthread_setcancelstate(PTHREAD_CANCEL_ENABLED) has been set)
bool AmThread::is_stopped () [inline]
Returns:
true if this thread doesn't run.
Referenced by join(), and stop().
void AmThread::join ()
Wait for this thread to finish
References is_stopped().
void AmThread::start ()
Start it !
Reimplemented in _async_file_writer.
Referenced by AnnounceAuthFactory::onLoad(), RegistrationAgentFactory::onLoad(), RtmpFactory::onLoad(), CallBackFactory::onLoad(), SIPRegistrarClient::onLoad(), and AnswerMachineFactory::onLoad().
void AmThread::stop ()
Stop it !
References is_stopped().
The documentation for this class was generated from the following files:
AmThread.h
AmThread.cpp