SEMS: AmAudio Class Reference
AmAudio Class Reference
base for classes that input or output audio.
#include <AmAudio.h>
Public Types
enum ResamplingImplementationType { LIBSAMPLERATE, INTERNAL_RESAMPLER, UNAVAILABLE }
Public Member Functions
virtual ~AmAudio ()
virtual void close ()
virtual int get (unsigned long long system_ts, unsigned char *buffer, int output_sample_rate, unsigned int nb_samples)
virtual int put (unsigned long long system_ts, unsigned char *buffer, int input_sample_rate, unsigned int size)
int getSampleRate ()
void setRecordTime (unsigned int ms)
int incRecordTime (unsigned int samples)
void setBufferedOutput (unsigned int buffer_size)
void setFormat (AmAudioFormat *new_fmt)
Protected Member Functions
AmAudio (AmAudioFormat *)
virtual int read (unsigned int user_ts, unsigned int size)=0
virtual int write (unsigned int user_ts, unsigned int size)=0
void stereo2mono (unsigned char *out_buf, unsigned char *in_buf, unsigned int &size)
int decode (unsigned int size)
int encode (unsigned int size)
unsigned int downMix (unsigned int size)
unsigned int resampleInput (unsigned char *buffer, unsigned int size, int input_sample_rate, int output_sample_rate)
unsigned int resampleOutput (unsigned char *buffer, unsigned int size, int input_sample_rate, int output_sample_rate)
unsigned int resample (AmResamplingState &rstate, unsigned char *buffer, unsigned int size, int input_sample_rate, int output_sample_rate)
unsigned int calcBytesToRead (unsigned int needed_samples) const
unsigned int bytes2samples (unsigned int bytes) const
unsigned int scaleSystemTS (unsigned long long system_ts)
Protected Attributes
DblBuffer samples
auto_ptr< AmAudioFormat > fmt
auto_ptr< AmResamplingState > input_resampling_state
auto_ptr< AmResamplingState > output_resampling_state
Detailed Description
base for classes that input or output audio.
AmAudio binds a format and converts the samples if needed.
Internal Format: PCM signed 16 bit (mono | stereo).
Constructor & Destructor Documentation
AmAudio::~AmAudio () [virtual]
Destructor
References close().
Member Function Documentation
unsigned int AmAudio::bytes2samples (unsigned int bytes) const [protected]
Convert the size from bytes to samples, depending on the format.
Reimplemented in AmRtpAudio.
References fmt.
Referenced by put().
unsigned int AmAudio::calcBytesToRead (unsigned int needed_samples) const [protected]
Get the number of bytes to read from encoded, depending on the format.
References fmt.
Referenced by AmPlaylist::get(), and get().
void AmAudio::close () [virtual]
Closes the audio pipe.
Reimplemented in AmAudioFile, AmCachedAudioFile, and AmPlaylist.
Referenced by WebConferenceDialog::clearAudio(), AmSession::clearAudio(), and ~AmAudio().
int AmAudio::decode (unsigned int size) [protected]
Converts from the input format to the internal format.
input = front buffer
output = back buffer
Parameters:
size [in] size in bytes
Returns:
new size in bytes
References amci_codec_t::decode, fmt, and samples.
Referenced by get().
unsigned int AmAudio::downMix (unsigned int size) [protected]
Converts to mono depending on the format.
Returns:
new size in bytes
References fmt, and stereo2mono().
Referenced by get().
int AmAudio::encode (unsigned int size) [protected]
Converts from the internal format to the output format.
input = front buffer
output = back buffer
Parameters:
size [in] size in bytes
Returns:
new size in bytes
References amci_codec_t::encode, fmt, and samples.
Referenced by RtmpAudio::put(), AmRtpAudio::put(), and put().
int AmAudio::get (unsigned long long system_ts, unsigned char * buffer, int output_sample_rate, unsigned int nb_samples) [virtual]
Get some samples from input stream.
Warning:
For packet based payloads / file formats, use:
           nb_sample = input buffer size / sample size of the reference format
whereby the format with/from which the codec works is the reference one.
Returns:
# bytes read, else -1 if error (0 is OK)
Reimplemented in AmNullAudio, AmRtpAudio, AmAudioFrontlist, AmAudioQueue, AmAudioMixIn, AmAudioMixerConnector, AmPlaylist, AmConferenceChannel, RtmpAudio, and AmBufferedAudio.
References calcBytesToRead(), decode(), downMix(), read(), resampleOutput(), and scaleSystemTS().
Referenced by AmPlaylist::get(), AmAudioMixIn::get(), AmAudioFrontlist::get(), AmAudioMixerConnector::put(), WebConferenceDialog::readStreams(), AudioStreamData::writeStream(), and AmSession::writeStreams().
int AmAudio::put (unsigned long long system_ts, unsigned char * buffer, int input_sample_rate, unsigned int size) [virtual]
Put some samples to the output stream.
Warning:
For packet based payloads / file formats, use:
           nb_sample = input buffer size / sample size of the reference format
whereby the format with/from which the codec works is the reference one.
Returns:
# bytes written, else -1 if error (0 is OK)
Reimplemented in AmNullAudio, AmRtpAudio, AmAudioFrontlist, AmAudioQueue, AmAudioMixIn, AmAudioMixerConnector, AmPlaylist, AmConferenceChannel, and RtmpAudio.
References bytes2samples(), encode(), resampleInput(), scaleSystemTS(), and write().
Referenced by AmPlaylist::put(), AmAudioFrontlist::put(), WebConferenceDialog::readStreams(), and AmSession::readStreams().
virtual int AmAudio::read (unsigned int user_ts, unsigned int size) [protected, pure virtual]
Gets 'size' bytes directly from stream (Read,Pull).
Implemented in AmNullAudio, AmRtpAudio, AmAudioDelay, AmAudioBridge, AmPlaylistSeparator, AmAudioFile, AmAudioQueue, RtmpAudio, AmAudioMixerConnector, AmAudioMixIn, AmPlaylist, AmConferenceChannel, AmRingTone, and mISDNChannel.
Referenced by get().
unsigned int AmAudio::resample (AmResamplingState & rstate, unsigned char * buffer, unsigned int size, int input_sample_rate, int output_sample_rate) [protected]
Resamples from the given input sample rate to the given output sample rate using the given resampling state.
input = front buffer
output = back buffer
Parameters:
rstate resampling state to be used
size [in] size in bytes
output_sample_rate desired output sample rate
Returns:
new size in bytes
Referenced by resampleInput(), and resampleOutput().
unsigned int AmAudio::resampleInput (unsigned char * buffer, unsigned int size, int input_sample_rate, int output_sample_rate) [protected]
Resamples from the given input sample rate to the given output sample rate using the input resampling state. The input resampling state is created if it does not exist.
References input_resampling_state, and resample().
Referenced by RtmpAudio::put(), AmConferenceChannel::put(), AmRtpAudio::put(), and put().
unsigned int AmAudio::resampleOutput (unsigned char * buffer, unsigned int size, int input_sample_rate, int output_sample_rate) [protected]
Resamples from the given input sample rate to the given output sample rate using the output resampling state. The output resampling state is created if it does not exist.
References resample().
Referenced by AmBufferedAudio::get(), RtmpAudio::get(), AmConferenceChannel::get(), AmRtpAudio::get(), and get().
unsigned int AmAudio::scaleSystemTS (unsigned long long system_ts) [protected]
Scale a system timestamp down dependent on the sample rate.
Referenced by RtmpAudio::get(), AmRtpAudio::get(), get(), RtmpAudio::put(), and put().
void AmAudio::stereo2mono (unsigned char * out_buf, unsigned char * in_buf, unsigned int & size) [protected]
Converts a buffer from stereo to mono.
Parameters:
size [in,out] size in bytes
Before call is size = input size
After the call is size = output size
Referenced by downMix().
virtual int AmAudio::write (unsigned int user_ts, unsigned int size) [protected, pure virtual]
Puts 'size' bytes directly from stream (Write,Push).
Implemented in AmNullAudio, AmRtpAudio, AmAudioDelay, AmAudioBridge, AmPlaylistSeparator, AmAudioFile, RtmpAudio, AmAudioQueue, AmAudioMixerConnector, AmAudioMixIn, AmPlaylist, AmConferenceChannel, AmRingTone, and mISDNChannel.
Referenced by put().
Field Documentation
auto_ptr<AmAudioFormat> AmAudio::fmt [protected]
Audio format.
See also:
AmAudioFormat
Referenced by bytes2samples(), calcBytesToRead(), decode(), downMix(), encode(), AmAudioFile::forward(), AmAudioFile::fpopen_int(), AmAudioFile::getLength(), AmRtpAudio::init(), AmAudioFile::on_close(), AmRtpAudio::put(), and AmAudioFile::rewind().
auto_ptr<AmResamplingState> AmAudio::input_resampling_state [protected]
Resampling states.
See also:
AmResamplingState
Referenced by resampleInput().
DblBuffer AmAudio::samples [protected]
Sample buffer.
Referenced by decode(), encode(), AmBufferedAudio::get(), RtmpAudio::get(), AmAudioQueue::get(), AmNullAudio::get(), RtmpAudio::put(), AmConferenceChannel::put(), AmRingTone::read(), AmAudioFile::read(), AmAudioBridge::read(), AmAudioDelay::read(), AmAudioFile::write(), AmAudioBridge::write(), and AmAudioDelay::write().
The documentation for this class was generated from the following files:
AmAudio.h
AmAudio.cpp