SEMS: AmSessionContainer Class Reference
AmSessionContainer Class Reference
Centralized session container.
#include <AmSessionContainer.h>
Public Types
enum AddSessionStatus { ShutDown, Inserted, AlreadyExist }
Public Member Functions
AmSession * createSession (const AmSipRequest &req, string &app_name, AmArg *session_params=NULL)
AddSessionStatus addSession (const string &callid, const string &remote_tag, const string &local_tag, const string &via_branch, AmSession *session)
AddSessionStatus addSession (const string &local_tag, AmSession *session)
void startSessionUAS (AmSipRequest &req)
string startSessionUAC (const AmSipRequest &req, string &app_name, AmArg *session_params=NULL)
void destroySession (AmSession *s)
bool postEvent (const string &callid, const string &remote_tag, const string &via_branch, AmEvent *event)
bool postEvent (const string &local_tag, AmEvent *event)
void broadcastShutdown ()
void enableUncleanShutdown ()
void setCPSLimit (unsigned int limit)
void setCPSSoftLimit (unsigned int percent)
pair< unsigned int, unsigned int > getCPSLimit ()
unsigned int getAvgCPS ()
unsigned int getMaxCPS ()
void initMonitoring ()
Static Public Member Functions
static AmSessionContainer * instance ()
static void dispose ()
Data Fields
_MONITORING_DEFINE_INTERFACE
Detailed Description
Centralized session container.
This is the register for all active and dead sessions. If has a deamon which wakes up only if it has work. Then, it kills all dead sessions and try to go to bed (it cannot sleep if one or more sessions are still alive).
Member Function Documentation
AmSessionContainer::AddSessionStatus AmSessionContainer::addSession (const string & callid, const string & remote_tag, const string & local_tag, const string & via_branch, AmSession * session)
Adds a session to the container (UAS only).
Returns:
true if the session is new within the container.
Referenced by startSessionUAC(), and startSessionUAS().
AmSessionContainer::AddSessionStatus AmSessionContainer::addSession (const string & local_tag, AmSession * session)
Adds a session to the container.
Returns:
true if the session is new within the container.
void AmSessionContainer::broadcastShutdown ()
broadcasts a server shutdown system event to all sessions
References AmSession::getSessionNum().
AmSession * AmSessionContainer::createSession (const AmSipRequest & req, string & app_name, AmArg * session_params = NULL)
Creates a new session.
Parameters:
req local request
Returns:
a new session or NULL on error.
References AmPlugIn::findSessionFactory(), AmPlugIn::getFactory4App(), AmSessionFactory::onInvite(), AmSessionFactory::onRefer(), parse_app_params(), AmBasicSipDialog::reply_error(), and AmCondition< T >::set().
Referenced by startSessionUAC(), and startSessionUAS().
void AmSessionContainer::destroySession (AmSession * s)
Detroys a session.
References AmSession::getLocalTag().
Referenced by AmSession::destroy().
void AmSessionContainer::enableUncleanShutdown ()
enable unclean shutdown (will not broadcastShutdown event)
unsigned int AmSessionContainer::getAvgCPS ()
Gets the timeaverage of calls per second in the last CPS_SAMPLERATE sec window
pair< unsigned int, unsigned int > AmSessionContainer::getCPSLimit ()
Return the maximum number of calls per second to be accepted
unsigned int AmSessionContainer::getMaxCPS ()
Gets the maximum of calls per second since last query
bool AmSessionContainer::postEvent (const string & callid, const string & remote_tag, const string & via_branch, AmEvent * event)
post an event into the event queue of the identified dialog.
Returns:
false if session doesn't exist
Referenced by ConferenceDialog::onDtmf(), AmSipSubscriptionDialog::onNotify(), ConferenceDialog::onSessionStart(), ConferenceDialog::onSipReply(), AmB2ABSession::relayEvent(), AmB2BSession::relayEvent(), and AmSession::setStopped().
bool AmSessionContainer::postEvent (const string & local_tag, AmEvent * event)
post a generic event into the event queue of the identified dialog. sess_key is local_tag (to_tag) note: if hash_str is known, use postGenericEvent(hash_str,sess_key,event); for better performance.
Returns:
false if session doesn't exist
void AmSessionContainer::setCPSLimit (unsigned int limit)
Set the maximum number of calls per second to be accepted
Referenced by AmConfig::readConfiguration().
void AmSessionContainer::setCPSSoftLimit (unsigned int percent)
Set the maximum number of calls per second to be accepted as a percent of the current CPS. Intented to be used by the components. 0 means turning off the soft limit.
string AmSessionContainer::startSessionUAC (const AmSipRequest & req, string & app_name, AmArg * session_params = NULL)
Constructs a new session and adds it to the active session container.
Parameters:
req client's request
References addSession(), and createSession().
void AmSessionContainer::startSessionUAS (AmSipRequest & req)
Constructs a new session and adds it to the active session container.
Parameters:
req client's request
References addSession(), createSession(), and AmBasicSipDialog::reply_error().
The documentation for this class was generated from the following files:
AmSessionContainer.h
AmSessionContainer.cpp