SEMS: EchoFactory Class Reference
EchoFactory Class Reference
Factory for echo sessions.
#include <Echo.h>
Public Member Functions
EchoFactory (const string &_app_name)
virtual int onLoad ()
virtual AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
Detailed Description
Factory for echo sessions.
Member Function Documentation
AmSession * EchoFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
References AmSession::addHandler(), AmSessionEventHandler::configure(), and AmSessionEventHandlerFactory::onInvite().
int EchoFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AmPlugIn::getFactory4Seh(), and AmConfig::ModConfigPath.
The documentation for this class was generated from the following files:
Echo.h
Echo.cpp