SEMS: AmSession Class Reference
AmSession Class Reference
Implements the default behavior of one session.
#include <AmSession.h>
Data Structures
struct Exception
Exception occured in a Session.
Public Types
enum SessionRefreshMethod { REFRESH_REINVITE = 0, REFRESH_UPDATE, REFRESH_UPDATE_FB_REINV }
Public Member Functions
void updateRefreshMethod (const string &headers)
AmRtpAudio * RTPStream ()
bool hasRtpStream ()
AmSession (AmSipDialog *dlg=NULL)
virtual void process (AmEvent *)
void addHandler (AmSessionEventHandler *)
void startMediaProcessing ()
void stopMediaProcessing ()
void setCallgroup (const string &cg)
string getCallgroup ()
void changeCallgroup (const string &cg)
void lockAudio ()
void unlockAudio ()
AmAudio * getInput ()
AmAudio * getOutput ()
void setInput (AmAudio *in)
void setOutput (AmAudio *out)
void setInOut (AmAudio *in, AmAudio *out)
virtual bool isAudioSet ()
virtual void clearAudio ()
void setMute (bool mute)
void setReceiving (bool receive)
void setForceDtmfReceiving (bool receive)
const string & getCallID () const
const string & getRemoteTag () const
const string & getLocalTag () const
const string & getFirstBranch () const
void setLocalTag ()
void setLocalTag (const string &tag)
void setUri (const string &uri)
const vector< SdpPayload * > & getPayloads ()
int getRPort ()
virtual bool refresh (int flags=0)
virtual int sendUpdate (const AmMimeBody *body, const string &hdrs)
virtual int sendReinvite (bool updateSDP=true, const string &headers="", int flags=0)
virtual int sendInvite (const string &headers="")
virtual void setOnHold (bool hold)
virtual void updateUACTransCSeq (unsigned int old_cseq, unsigned int new_cseq)
string getAppParam (const string &param_name) const
virtual void destroy ()
virtual void setStopped (bool wakeup=false)
bool getStopped ()
void postDtmfEvent (AmDtmfEvent *)
void setInbandDetector (Dtmf::InbandDetectorType t)
bool isDtmfDetectionEnabled ()
void setDtmfDetectionEnabled (bool e)
void putDtmfAudio (const unsigned char *buf, int size, unsigned long long system_ts)
void sendDtmf (int event, unsigned int duration_ms)
virtual bool setTimer (int timer_id, double timeout)
virtual bool removeTimer (int timer_id)
virtual bool removeTimers ()
virtual void onDtmf (int event, int duration)
virtual void onStart ()
virtual void onStop ()
virtual void onInvite (const AmSipRequest &req)
virtual void onOutgoingInvite (const string &headers)
virtual void onCancel (const AmSipRequest &req)
virtual void onRinging (const AmSipReply &reply)
virtual void onBye (const AmSipRequest &req)
virtual void onRemoteDisappeared (const AmSipReply &)
virtual void onSipRequest (const AmSipRequest &req)
virtual void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
virtual void onInvite2xx (const AmSipReply &reply)
virtual void onInvite1xxRel (const AmSipReply &)
virtual void onPrack2xx (const AmSipReply &)
virtual void onFailure ()
virtual void onNoAck (unsigned int cseq)
virtual void onNoPrack (const AmSipRequest &req, const AmSipReply &rpl)
virtual void onAudioEvent (AmAudioEvent *audio_ev)
virtual void onSystemEvent (AmSystemEvent *ev)
virtual void onRtpTimeout ()
virtual void onSessionTimeout ()
virtual void onSendRequest (AmSipRequest &req, int &flags)
virtual void onSendReply (const AmSipRequest &req, AmSipReply &reply, int &flags)
virtual bool getSdpOffer (AmSdp &offer)
virtual bool getSdpAnswer (const AmSdp &offer, AmSdp &answer)
virtual int onSdpCompleted (const AmSdp &offer, const AmSdp &answer)
virtual void onEarlySessionStart ()
virtual void onSessionStart ()
virtual void onBeforeDestroy ()
string advertisedIP (int addrType=AT_NONE)
string localMediaIP (int addrType=AT_NONE)
string sid4dbg ()
virtual int readStreams (unsigned long long ts, unsigned char *buffer)
virtual int writeStreams (unsigned long long ts, unsigned char *buffer)
virtual void clearRTPTimeout ()
virtual void processDtmfEvents ()
virtual bool onBeforeRTPRelay (AmRtpPacket *p, sockaddr_storage *remote_addr)
virtual void onAfterRTPRelay (AmRtpPacket *p, sockaddr_storage *remote_addr)
int getRtpInterface ()
void setRtpInterface (int _rtp_interface)
Static Public Member Functions
static unsigned int getSessionNum ()
static unsigned int getMaxSessionNum ()
static unsigned int getAvgSessionNum ()
static bool timersSupported ()
static string getNewId ()
Data Fields
SessionRefreshMethod refresh_method
AmSipDialog * dlg
Protected Member Functions
virtual AmSipDialog * createSipDialog ()
virtual bool processEventsCatchExceptions ()
bool startup ()
virtual bool processingCycle ()
void finalize ()
Protected Attributes
vector< SdpPayload * > m_payloads
AmCondition< bool > sess_stopped
string callgroup
bool accept_early_session
int rtp_interface
vector< AmSessionEventHandler * > ev_handlers
AmAudio * input
AmAudio * output
Friends
class AmRtpAudio
class AmMediaProcessor
class AmMediaProcessorThread
class AmSessionContainer
class AmSessionFactory
class AmSessionProcessorThread
Detailed Description
Implements the default behavior of one session.
The session is identified by Call-ID, From-Tag and To-Tag.
Constructor & Destructor Documentation
AmSession::AmSession (AmSipDialog * dlg = NULL)
Session constructor.
Member Function Documentation
void AmSession::addHandler (AmSessionEventHandler * sess_evh)
add a handler which will be called for all events in session
See also:
AmSessionEventHandler
References ev_handlers.
Referenced by AmUACAuth::enable(), and EchoFactory::onInvite().
void AmSession::changeCallgroup (const string & cg)
change the callgroup
This function removes the session from the media processor and adds it again.
References callgroup, and AmMediaProcessor::changeCallgroup().
void AmSession::clearAudio () [virtual]
Clears input & ouput (no need to lock)
Implements AmMediaSession.
Reimplemented in WebConferenceDialog.
References AmAudio::close(), lockAudio(), and unlockAudio().
virtual void AmSession::clearRTPTimeout () [inline, virtual]
Reset timeouts of all RTP streams related to this media session.
Called during initialization when session starts to be processed by media processor.
Implements AmMediaSession.
References AmRtpStream::clearRTPTimeout().
void AmSession::destroy () [virtual]
Destroy the session. It causes the session to be erased from the active session list and added to the dead session list.
See also:
AmSessionContainer
References AmSessionContainer::destroySession().
Referenced by finalize(), and startup().
void AmSession::finalize () [protected, virtual]
clean up session
Reimplemented from AmEventQueue.
Reimplemented in AmB2BSession.
References destroy(), AmBasicSipDialog::finalize(), and onBeforeDestroy().
string AmSession::getAppParam (const string & param_name) const
Get a session parameter ('P-App-Param' HF, etc...)
Referenced by b2b_connectDialog::onInvite().
unsigned int AmSession::getAvgSessionNum () [static]
Gets the average of running sessions since last query
string AmSession::getCallgroup ()
get the callgroup
Returns:
callgroup
References callgroup.
const string & AmSession::getCallID () const
Gets the Session's call ID
const string & AmSession::getFirstBranch () const
Gets the branch param of the first via in the original INVITE
AmAudio* AmSession::getInput () [inline]
Audio input getter . Note: audio must be locked!
Referenced by DSMCall::onEarlySessionStart().
const string & AmSession::getLocalTag () const
Gets the Session's local tag
Referenced by CallLeg::addCallee(), AmSessionAudioConnector::connectSession(), CallLeg::debug(), AmSessionContainer::destroySession(), CallLeg::disconnect(), AmSessionAudioConnector::disconnectSession(), AmB2ABCalleeSession::onB2ABEvent(), AmB2BCalleeSession::onB2BEvent(), WebConferenceDialog::onBye(), SBCCallLeg::onBye(), AnnRecorderDialog::onDtmf(), ConferenceDialog::onDtmf(), EarlyRecordDialog::onEarlySessionStart(), SBCCallLeg::onOtherBye(), CallLeg::onSdpCompleted(), EarlyRecordDialog::onSessionStart(), SimpleConferenceDialog::onSessionStart(), WebConferenceDialog::onSessionStart(), AnswerMachineDialog::onSessionStart(), WebConferenceDialog::onSipReply(), AmB2BSession::onSipReply(), CallLeg::onSipReply(), CallLeg::onSipRequest(), WebConferenceDialog::process(), processingCycle(), AmB2ABCallerSession::relayEvent(), AmB2BCallerSession::relayEvent(), removeTimer(), removeTimers(), CallLeg::replaceExistingLeg(), AmB2BSession::setRtpRelayMode(), setStopped(), setTimer(), and CallLeg::updateLocalSdp().
unsigned int AmSession::getMaxSessionNum () [static]
Gets the maximum of running sessions since last query
string AmSession::getNewId () [static]
Creates a new Id which can be used within sessions.
References get_random(), and int2hex().
Referenced by CallLeg::CallLeg(), UACAuthFactory::onLoad(), AmBasicSipDialog::reply_error(), and setLocalTag().
AmAudio* AmSession::getOutput () [inline]
Audio output getter. Note: audio must be locked!
Referenced by DSMCall::onEarlySessionStart().
const vector< SdpPayload * > & AmSession::getPayloads ()
Gets the current RTP payload
const string & AmSession::getRemoteTag () const
Gets the Session's remote tag
int AmSession::getRPort ()
Gets the port number of the remote part of the session
References AmRtpStream::getRPort().
Referenced by sid4dbg().
bool AmSession::getSdpAnswer (const AmSdp & offer, AmSdp & answer) [virtual]
Hook called when an SDP offer is required
Hook called when an SDP answer is required
Implements AmSipDialogEventHandler.
Reimplemented in CallLeg, and DSMCall.
References SdpConnection::address, SdpConnection::addrType, AmRtpAudio::getSdpAnswer(), SdpConnection::network, and AmRtpStream::setLocalIP().
Referenced by DSMCall::getSdpAnswer().
bool AmSession::getSdpOffer (AmSdp & offer) [virtual]
Hook called when an SDP offer is required
Implements AmSipDialogEventHandler.
Reimplemented in CallLeg, and DSMCall.
References SdpConnection::address, SdpConnection::addrType, AmRtpAudio::getSdpOffer(), SdpConnection::network, and AmRtpStream::setLocalIP().
Referenced by DSMCall::getSdpOffer().
unsigned int AmSession::getSessionNum () [static]
Gets the number of running sessions
Referenced by AmSessionContainer::broadcastShutdown().
bool AmSession::getStopped () [inline]
Has the session already been stopped ?
Referenced by AmB2BCallerSession::relayEvent(), and startMediaProcessing().
bool AmSession::isAudioSet () [virtual]
checks if input/output is set, might be overidden!
Reimplemented in WebConferenceDialog.
References lockAudio(), and unlockAudio().
Referenced by startMediaProcessing().
void AmSession::lockAudio ()
Lock audio input & output (inclusive RTP stream)
Referenced by WebConferenceDialog::clearAudio(), clearAudio(), WebConferenceDialog::isAudioSet(), isAudioSet(), onSdpCompleted(), WebConferenceDialog::readStreams(), readStreams(), setInput(), setOnHold(), and writeStreams().
void AmSession::onAudioEvent (AmAudioEvent * audio_ev) [virtual]
Entry point for Audio events
References setStopped().
Referenced by process().
virtual void AmSession::onBeforeDestroy () [inline, virtual]
called in the session thread before the session is destroyed, i.e. after the main event loop has finished
Reimplemented in AmB2ABCalleeSession, AmB2ABCallerSession, SBCCallLeg, DSMCall, RtmpSession, and PySemsB2ABDialog.
Referenced by finalize(), and startup().
virtual bool AmSession::onBeforeRTPRelay (AmRtpPacket * p, sockaddr_storage * remote_addr) [inline, virtual]
Call-backs used by RTP stream(s)
Note: these methods will be called from the RTP receiver thread.
void AmSession::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented in AmB2BCallerSession, CallLeg, SBCCallLeg, AmB2ABSession, ConferenceDialog, CallGenDialog, IvrDialog, AnswerMachineDialog, AnnRecorderDialog, WebConferenceDialog, VoiceboxDialog, PinAuthConferenceDialog, AnnounceAuthDialog, DSMCall, EarlyAnnounceDialog, DtmfTesterDialog, SimpleConferenceDialog, AnnounceTransferDialog, AnnouncementDialog, RtmpSession, b2b_connectDialog, CacheAnnounceDialog, MyCCDialog, EchoDialog, PrecodedDialog, EarlyRecordDialog, MyJukeboxDialog, GWSession, MyAnnounceAppDialog, MyConfigurableAppDialog, MyAppDialog, and MyAppDialog.
References setStopped().
Referenced by AmB2BSession::onSipRequest(), and onSipRequest().
void AmSession::onCancel (const AmSipRequest & req) [virtual]
onCancel will be called if a CANCEL for a running dialog has been received. At this point, the CANCEL transaction has been replied with 200.
A normal plug-in does not have to do anything special, as normal dialogs are immediatly replied with 200 or error code.
Note: You are still responsible for responding the initial transaction.
Reimplemented in AmB2BCallerSession, CallLeg, DSMCall, EarlyAnnounceDialog, b2b_connectDialog, and GWSession.
References AmSipDialog::bye(), and setStopped().
Referenced by onSipRequest().
void AmSession::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented in ConferenceDialog, SBCCallLeg, IvrDialog, AnswerMachineDialog, AnnRecorderDialog, CallBackDialog, WebConferenceDialog, VoiceboxDialog, PinAuthConferenceDialog, AnnounceAuthDialog, DSMCall, EarlyAnnounceDialog, DtmfTesterDialog, JukecallSession, ServiceLineCallerDialog, AnnounceTransferDialog, SimpleConferenceDialog, AnnouncementDialog, b2b_connectDialog, CacheAnnounceDialog, EchoDialog, MyCCDialog, and MyJukeboxDialog.
Referenced by process().
void AmSession::onEarlySessionStart () [virtual]
Hook called when an early session starts (SDP OA completed + dialog in early state)
Implements AmSipDialogEventHandler.
Reimplemented in CallLeg, AmB2ABCalleeSession, CallGenDialog, WebConferenceDialog, DSMCall, EarlyAnnounceDialog, EarlyRecordDialog, and PySemsB2ABDialog.
References startMediaProcessing().
void AmSession::onFailure () [virtual]
Hook called when either a received request or reply has been rejected by the local SIP UA layer.
Reimplemented from AmBasicSipEventHandler.
void AmSession::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented in AmB2BCallerSession, CallLeg, ConferenceDialog, SBCCallLeg, IvrDialog, CallBackDialog, WebConferenceDialog, EarlyAnnounceDialog, RtmpSession, DSMCall, C2DCallerDialog, b2b_connectDialog, AnnounceTransferDialog, AnnounceCallerDialog, and GWSession.
References AmBasicSipDialog::reply().
Referenced by onSipRequest().
void AmSession::onInvite1xxRel (const AmSipReply &) [virtual]
Hook called when a provisional reply is received with 100rel active
Implements AmSipDialogEventHandler.
References AmSipDialog::prack(), and sid4dbg().
void AmSession::onInvite2xx (const AmSipReply & reply) [virtual]
2xx reply has been received for an INVITE transaction
Implements AmSipDialogEventHandler.
Reimplemented in AmB2BCallerSession, CallLeg, AmB2BSession, and C2DCallerDialog.
References AmSipDialog::send_200_ack().
void AmSession::onNoAck (unsigned int ack_cseq) [virtual]
Hook called when a UAS INVITE transaction did not receive the ACK
Implements AmSipDialogEventHandler.
Reimplemented in CallLeg, AmB2BSession, and DSMCall.
References AmSipDialog::bye(), AmBasicSipDialog::getStatus(), and setStopped().
void AmSession::onNoPrack (const AmSipRequest & req, const AmSipReply & rpl) [virtual]
Hook called when a UAS INVITE transaction did not receive the PRACK
Implements AmSipDialogEventHandler.
Reimplemented in CallLeg.
References AmBasicSipDialog::getStatus(), AmBasicSipDialog::reply(), and setStopped().
virtual void AmSession::onOutgoingInvite (const string & headers) [inline, virtual]
onOutgoingInvite will be called if an INVITE is sent in the session.
Reimplemented in DSMCall.
Referenced by sendInvite().
void AmSession::onPrack2xx (const AmSipReply & reply) [virtual]
answer for a locally sent PRACK is received
Implements AmSipDialogEventHandler.
void AmSession::onRemoteDisappeared (const AmSipReply &) [virtual]
remote side is unreachable - 408/481 reply received
Reimplemented from AmBasicSipEventHandler.
Reimplemented in AmB2BCallerSession, CallLeg, AmB2BSession, SBCCallLeg, and DSMCall.
References AmSipDialog::bye(), and setStopped().
virtual void AmSession::onRinging (const AmSipReply & reply) [inline, virtual]
onRinging will be called after 180 is received. If local audio is set up, session is added to media processor.
Reimplemented in WebConferenceDialog, DSMCall, and GWSession.
Referenced by onSipReply().
void AmSession::onRtpTimeout () [virtual]
This callback is called if RTP timeout encountered
Reimplemented in CallLeg, AmB2BSession, IvrDialog, WebConferenceDialog, and DSMCall.
References AmSipDialog::bye(), and setStopped().
Referenced by process().
int AmSession::onSdpCompleted (const AmSdp & offer, const AmSdp & answer) [virtual]
Hook called when an SDP OA transaction has been completed
Implements AmSipDialogEventHandler.
Reimplemented in CallLeg, AmB2BSession, IvrDialog, and DSMCall.
References AmConfig::ForceSymmetricRtp, AmRtpAudio::init(), AmMediaSession::isProcessingMedia(), lockAudio(), AmSdp::print(), and unlockAudio().
void AmSession::onSendReply (const AmSipRequest & req, AmSipReply & reply, int & flags) [virtual]
Called by AmSipDialog when a reply is sent
Reimplemented from AmBasicSipEventHandler.
void AmSession::onSendRequest (AmSipRequest & req, int & flags) [virtual]
Hook called before a request is sent
Reimplemented from AmBasicSipEventHandler.
Reimplemented in SBCCallLeg, and DSMCallCalleeSession.
void AmSession::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Implements AmSipDialogEventHandler.
Reimplemented in CallLeg, AmB2ABCalleeSession, ConferenceDialog, CallGenDialog, AnswerMachineDialog, IvrDialog, AnnRecorderDialog, CallBackDialog, WebConferenceDialog, VoiceboxDialog, PinAuthConferenceDialog, AnnounceAuthDialog, DSMCall, ServiceLineCallerDialog, DtmfTesterDialog, SimpleConferenceDialog, C2DCallerDialog, JukecallSession, AnnouncementDialog, AnnounceTransferDialog, RtmpSession, b2b_connectDialog, CacheAnnounceDialog, AnnounceCallerDialog, EchoDialog, MyCCDialog, PrecodedDialog, EarlyRecordDialog, PySemsB2ABDialog, PySemsB2BDialog, MyJukeboxDialog, MyAnnounceAppDialog, MyConfigurableAppDialog, MyAppDialog, and MyAppDialog.
References startMediaProcessing().
void AmSession::onSessionTimeout () [virtual]
This callback is called if session timeout encountered (session timers)
Reimplemented in CallLeg, AmB2BSession, WebConferenceDialog, and DSMCall.
References AmSipDialog::bye(), and setStopped().
void AmSession::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_dlg_status) [virtual]
Entry point for SIP Replies
Reimplemented from AmBasicSipEventHandler.
Reimplemented in CallLeg, AmB2ABCalleeSession, AmB2BSession, SBCCallLeg, DSMCallCalleeSession, ConferenceDialog, IvrDialog, CallGenDialog, WebConferenceDialog, DSMCall, AnnounceTransferDialog, and RtmpSession.
References AmBasicSipDialog::getStatus(), onRinging(), and updateRefreshMethod().
void AmSession::onSipRequest (const AmSipRequest & req) [virtual]
Entry point for SIP Requests
Reimplemented from AmBasicSipEventHandler.
Reimplemented in CallLeg, AmB2BSession, SBCCallLeg, ConferenceDialog, IvrDialog, DSMCall, AnnounceTransferDialog, and GWSession.
References AmMimeBody::getLen(), AmMimeBody::getPayload(), AmMimeBody::hasContentType(), onBye(), onCancel(), onInvite(), postDtmfEvent(), AmBasicSipDialog::reply(), setStopped(), and updateRefreshMethod().
virtual void AmSession::onStart () [inline, virtual]
onStart will be called before everything else.
Reimplemented in ConferenceDialog, SBCCallLeg, CallGenDialog, and DSMCall.
Referenced by startup().
virtual void AmSession::onStop () [inline, virtual]
onStop will be called once session is marked to be stopped (called only once).
Referenced by setStopped().
void AmSession::onSystemEvent (AmSystemEvent * ev) [virtual]
entry point for system events
Reimplemented in AmB2BCallerSession, and DSMCall.
References setStopped().
Referenced by process().
void AmSession::postDtmfEvent (AmDtmfEvent * evt) [virtual]
Entry point for DTMF events
Implements AmDtmfSink.
Referenced by onSipRequest(), and AmRtpStream::recvDtmfPacket().
void AmSession::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Implements AmEventHandler.
Reimplemented in AmB2BSession, AmB2ABSession, ConferenceDialog, CallGenDialog, SBCCallLeg, AnswerMachineDialog, AnnRecorderDialog, CallBackDialog, DSMCall, VoiceboxDialog, WebConferenceDialog, PinAuthConferenceDialog, AnnounceAuthDialog, EarlyAnnounceDialog, DtmfTesterDialog, RtmpSession, AnnounceTransferDialog, ServiceLineCallerDialog, AnnouncementDialog, JukecallSession, SimpleConferenceDialog, C2DCallerDialog, CacheAnnounceDialog, b2b_connectDialog, AnnounceCallerDialog, MyCCDialog, PySemsDialog, PySemsB2ABDialog, PySemsB2BDialog, MyJukeboxDialog, and EarlyRecordDialog.
References AmDtmfEvent::duration(), AmDtmfEvent::event(), onAudioEvent(), onDtmf(), onRtpTimeout(), and onSystemEvent().
void AmSession::processDtmfEvents () [virtual]
Handle events in DTMF event queue.
DTMF events should be detected from RTP stream when reading data (see readStreams()) and put into an event queue for later processing to avoid blocking of audio processing for too long time.
This DTMF event queue should be processed then, within this method, which is triggered by AmMediaProcessorThread once reading/writing from media streams is finished.
Implements AmMediaSession.
References AmDtmfEventQueue::processEvents().
bool AmSession::processEventsCatchExceptions () [protected, virtual]
process pending events,
Returns:
whether everything went smoothly
Referenced by processingCycle().
bool AmSession::processingCycle () [protected, virtual]
Returns:
whether session continues running
one cycle of the event processing loop. this should be called until it returns false.
Reimplemented from AmEventQueue.
References AmSipDialog::bye(), getLocalTag(), AmBasicSipDialog::getStatus(), AmBasicSipDialog::getUACTransPending(), and processEventsCatchExceptions().
int AmSession::readStreams (unsigned long long ts, unsigned char * buffer) [virtual]
Read from all media streams.
To preserve current media processing scheme it is needed to read from all streams first and then write to them. This can be important for example in case of conferences where we need to have media from all streams ready for mixing them.
So the AmMediaProcessorThread first calls readStreams on all sessions and then writeStreams on all sessions.
Parameters:
ts timestamp for which the processing is currently running
buffer multi-purpose space given from outside (AmMediaProcessorThread)
Buffer given as parametr is usable for anything, originally was intended for data read from one stream before putting to another stream.
The reason for having this buffer as parameter is that buffer size for audio processing is quite large (2K here) and thus allocating it on stack on some architectures may be problematic.
On other hand having the buffer dynamically allocated for each media session would significantly increase memory consumption per call.
So for now it seems to be the simplest way just to give the buffer as parameter from AmMediaProcessorThread and reuse it in all sessions handled by this thread (processing is done sequentially one session after another).
Implements AmMediaSession.
Reimplemented in CallLeg, and WebConferenceDialog.
References AmRtpAudio::get(), lockAudio(), AmAudio::put(), and unlockAudio().
bool AmSession::refresh (int flags = 0) [virtual]
refresh the session - re-INVITE or UPDATE
Reimplemented in AmB2BSession.
References AmBasicSipDialog::getStatus(), AmSipDialog::getUACInvTransPending(), refresh_method, sendReinvite(), and sendUpdate().
bool AmSession::removeTimer (int timer_id) [virtual]
remove a Timer
Parameters:
timer_id the ID of the timer (<0 for system timers)
Returns:
true on success
References getLocalTag().
Referenced by SBCCallLeg::process().
bool AmSession::removeTimers () [virtual]
remove all Timers
Returns:
true on success Note: this doesn't clear timer events already in the event queue
References getLocalTag().
Referenced by AnnRecorderDialog::onDtmf().
void AmSession::sendDtmf (int event, unsigned int duration_ms)
send a DTMF as RTP payload (RFC4733)
Parameters:
event event ID (e.g. key press), see rfc
duration_ms duration in milliseconds
References AmRtpStream::sendDtmf().
int AmSession::sendInvite (const string & headers = "") [virtual]
send an INVITE
References AmMimeBody::addPart(), AmSipDialog::invite(), and onOutgoingInvite().
Referenced by AmB2ABCalleeSession::onB2ABEvent().
int AmSession::sendReinvite (bool updateSDP = true, const string & headers = "", int flags = 0) [virtual]
send a Re-INVITE (if connected)
References AmMimeBody::addPart(), and AmSipDialog::reinvite().
Referenced by refresh(), and setOnHold().
int AmSession::sendUpdate (const AmMimeBody * body, const string & hdrs) [virtual]
send an UPDATE in the session
References AmSipDialog::update().
Referenced by refresh().
void AmSession::setCallgroup (const string & cg)
Set the call group for this call; calls in the same group are processed by the same media processor thread.
Note: this must be set before inserting the session to the MediaProcessor!
References callgroup.
Referenced by AmB2ABCalleeSession::onB2ABEvent(), and SimpleConferenceDialog::onSessionStart().
void AmSession::setForceDtmfReceiving (bool receive) [inline]
setter for rtp_str->force_receive_dtmf
References AmRtpStream::force_receive_dtmf.
void AmSession::setInput (AmAudio * in)
Audio input & output set methods. Note: audio will be locked by the methods.
References lockAudio(), and unlockAudio().
Referenced by EarlyRecordDialog::onEarlySessionStart(), and DSMCall::onEarlySessionStart().
void AmSession::setLocalTag ()
Sets the Session's local tag if not set already
References getNewId().
void AmSession::setLocalTag (const string & tag)
Sets the Session's local tag
void AmSession::setMute (bool mute) [inline]
setter for rtp_str->mute
References AmRtpStream::mute.
Referenced by EarlyRecordDialog::onEarlySessionStart(), and WebConferenceDialog::onSessionStart().
void AmSession::setOnHold (bool hold) [virtual]
set the session on/off hold
References AmRtpStream::getOnHold(), lockAudio(), sendReinvite(), AmRtpStream::setOnHold(), and unlockAudio().
void AmSession::setReceiving (bool receive) [inline]
setter for rtp_str->receiving
References AmRtpStream::setReceiving().
Referenced by EarlyAnnounceDialog::onEarlySessionStart(), PrecodedDialog::onSessionStart(), AnnounceCallerDialog::onSessionStart(), AnnounceTransferDialog::onSessionStart(), C2DCallerDialog::onSessionStart(), and AnswerMachineDialog::onSessionStart().
void AmSession::setStopped (bool wakeup = false) [virtual]
Signals the session it should stop. This will cause the session to be able to exit the main loop. If wakeup is set, a bogus event will be sent to wake up the session.
References getLocalTag(), onStop(), AmSessionContainer::postEvent(), and AmCondition< T >::set().
Referenced by onAudioEvent(), b2b_connectDialog::onB2ABEvent(), AmB2ABCalleeSession::onB2ABEvent(), AmB2BCalleeSession::onB2BEvent(), MyAppDialog::onBye(), MyConfigurableAppDialog::onBye(), MyAnnounceAppDialog::onBye(), MyJukeboxDialog::onBye(), EarlyRecordDialog::onBye(), EchoDialog::onBye(), PrecodedDialog::onBye(), MyCCDialog::onBye(), CacheAnnounceDialog::onBye(), b2b_connectDialog::onBye(), AnnounceTransferDialog::onBye(), SimpleConferenceDialog::onBye(), DtmfTesterDialog::onBye(), EarlyAnnounceDialog::onBye(), AnnounceAuthDialog::onBye(), PinAuthConferenceDialog::onBye(), VoiceboxDialog::onBye(), AnnRecorderDialog::onBye(), AnswerMachineDialog::onBye(), CallGenDialog::onBye(), ConferenceDialog::onBye(), AmB2ABSession::onBye(), onBye(), b2b_connectDialog::onCancel(), EarlyAnnounceDialog::onCancel(), onCancel(), AnnRecorderDialog::onDtmf(), C2DCallerDialog::onInvite(), CallBackDialog::onInvite(), SBCCallLeg::onInvite(), onNoAck(), onNoPrack(), AmB2BSession::onOtherReply(), onRemoteDisappeared(), onRtpTimeout(), PrecodedDialog::onSessionStart(), RtmpSession::onSessionStart(), onSessionTimeout(), AnnounceTransferDialog::onSipReply(), RtmpSession::onSipReply(), DSMCall::onSipReply(), WebConferenceDialog::onSipReply(), CallGenDialog::onSipReply(), ConferenceDialog::onSipReply(), AnnounceTransferDialog::onSipRequest(), onSipRequest(), onSystemEvent(), EarlyRecordDialog::process(), CacheAnnounceDialog::process(), AnnouncementDialog::process(), RtmpSession::process(), DtmfTesterDialog::process(), EarlyAnnounceDialog::process(), AnnounceAuthDialog::process(), WebConferenceDialog::process(), VoiceboxDialog::process(), AnnRecorderDialog::process(), CallGenDialog::process(), ConferenceDialog::process(), AmB2ABSession::terminateLeg(), and AmB2BSession::terminateLeg().
bool AmSession::setTimer (int timer_id, double timeout) [virtual]
set a Timer
Parameters:
timer_id the ID of the timer (<0 for system timers)
timeout timeout in seconds (fractal value allowed)
Returns:
true on success
References getLocalTag().
Referenced by MyCCDialog::onOtherReply(), WebConferenceDialog::process(), AnnRecorderDialog::process(), SBCCallLeg::process(), and SBCCallLeg::startCallTimers().
void AmSession::setUri (const string & uri)
Sets the URI for the session
Referenced by WebConferenceFactory::onInvite().
string AmSession::sid4dbg ()
format session id for debugging
References AmRtpStream::getRHost(), getRPort(), and int2str().
Referenced by onInvite1xxRel().
void AmSession::startMediaProcessing ()
start processing media - add to media processor
References AmMediaProcessor::addSession(), callgroup, getStopped(), isAudioSet(), and AmMediaSession::isProcessingMedia().
Referenced by onEarlySessionStart(), and onSessionStart().
bool AmSession::startup () [protected, virtual]
Returns:
whether startup was successful
Reimplemented from AmEventQueue.
References destroy(), onBeforeDestroy(), and onStart().
void AmSession::stopMediaProcessing ()
stop processing media - remove from media processor
References AmMediaSession::isProcessingMedia(), and AmMediaProcessor::removeSession().
bool AmSession::timersSupported () [static]
Deprecated: check for support of timers
Returns:
always true
void AmSession::unlockAudio ()
Unlock audio input & output (inclusive RTP stream)
Referenced by WebConferenceDialog::clearAudio(), clearAudio(), WebConferenceDialog::isAudioSet(), isAudioSet(), onSdpCompleted(), WebConferenceDialog::readStreams(), readStreams(), setInput(), setOnHold(), and writeStreams().
void AmSession::updateRefreshMethod (const string & headers)
update selected session refresh method from remote capabilities
References key_in_list(), and refresh_method.
Referenced by AmB2BSession::onSipReply(), onSipReply(), AmB2BSession::onSipRequest(), and onSipRequest().
virtual void AmSession::updateUACTransCSeq (unsigned int old_cseq, unsigned int new_cseq) [inline, virtual]
update UAC trans state reference from old_cseq to new_cseq e.g. if uac_auth or session_timer have resent a UAC request
Reimplemented in AmB2BSession, and C2DCallerDialog.
int AmSession::writeStreams (unsigned long long ts, unsigned char * buffer) [virtual]
Write to all media streams.
For the meaning of parameters see description of readStreams() method.
Implements AmMediaSession.
Reimplemented in CallLeg.
References AmAudio::get(), lockAudio(), AmRtpAudio::put(), and unlockAudio().
Field Documentation
bool AmSession::accept_early_session [protected]
do accept early session?
Referenced by DSMCall::onOutgoingInvite().
string AmSession::callgroup [protected]
this is the group the media is processed with
by default local tag
Referenced by changeCallgroup(), AmB2ABSession::connectSession(), getCallgroup(), setCallgroup(), and startMediaProcessing().
vector<AmSessionEventHandler*> AmSession::ev_handlers [protected]
Session event handlers (ex: session timer, UAC auth, etc...)
Referenced by addHandler().
SessionRefreshMethod AmSession::refresh_method
currently selected session refresh method
Referenced by SessionTimer::configure(), AmB2BSession::refresh(), refresh(), and updateRefreshMethod().
int AmSession::rtp_interface [protected]
Local IP interface to be used for RTP streams
The documentation for this class was generated from the following files:
AmSession.h
AmSession.cpp