SEMS: AmB2ABCalleeSession Class Reference
AmB2ABCalleeSession Class Reference
Callee leg of a B2AB session.
#include <AmB2ABSession.h>
Public Member Functions
AmB2ABCalleeSession (const string &other_local_tag, AmSessionAudioConnector *callers_connector)
void onEarlySessionStart ()
void onSessionStart ()
void onSipReply (const AmSipRequest &req, const AmSipReply &rep, AmSipDialog::Status old_dlg_status)
Protected Member Functions
void onB2ABEvent (B2ABEvent *ev)
void onBeforeDestroy ()
Protected Attributes
AmCondition< bool > * released
Detailed Description
Callee leg of a B2AB session.
Member Function Documentation
void AmB2ABCalleeSession::onB2ABEvent (B2ABEvent * ev) [protected, virtual]
B2ABEvent handler
Reimplemented from AmB2ABSession.
Reimplemented in PySemsB2ABCalleeDialog.
References AmSession::getLocalTag(), AmB2ABSession::other_id, AmB2ABSession::relayEvent(), AmSession::sendInvite(), AmSession::setCallgroup(), and AmSession::setStopped().
void AmB2ABCalleeSession::onBeforeDestroy () [protected, virtual]
called in the session thread before the session is destroyed, i.e. after the main event loop has finished
Reimplemented from AmSession.
References AmB2ABSession::connector, and AmSessionAudioConnector::release().
void AmB2ABCalleeSession::onEarlySessionStart () [virtual]
Hook called when an early session starts (SDP OA completed + dialog in early state)
Reimplemented from AmSession.
References AmB2ABSession::connectSession(), and AmB2ABSession::relayEvent().
void AmB2ABCalleeSession::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmB2ABSession::connectSession(), and AmB2ABSession::relayEvent().
void AmB2ABCalleeSession::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmSipDialog::Status old_dlg_status) [virtual]
Entry point for SIP Replies
Reimplemented from AmSession.
References AmBasicSipDialog::getStatus(), and AmB2ABSession::relayEvent().
The documentation for this class was generated from the following files:
AmB2ABSession.h
AmB2ABSession.cpp