SEMS: AmPrecodedFile Class Reference
AmPrecodedFile Class Reference
Public Member Functions
int open (const std::string &filename)
void initPlugin ()
AmPrecodedFileInstance * getFileInstance (int payload_id)
amci_payload_t * payload (int payload_id) const
int getDynPayload (const string &name, int rate, int encoding_param) const
void getPayloads (vector< SdpPayload > &pl_vec) const
Member Function Documentation
int AmPrecodedFile::getDynPayload (const string & name, int rate, int encoding_param) const [virtual]
Payload lookup function by name & rate
Parameters:
name Payload ID.
Returns:
-1 if failed, else the internal payload id.
Implements AmPayloadProvider.
void AmPrecodedFile::getPayloads (vector< SdpPayload > & pl_vec) const [virtual]
List all the payloads available for a media type
Implements AmPayloadProvider.
void AmPrecodedFile::initPlugin ()
need to call after open()
Referenced by PrecodedFactory::onLoad().
int AmPrecodedFile::open (const std::string & filename)
Open the file
References explode(), amci_payload_t::name, and amci_payload_t::payload_id.
Referenced by PrecodedFactory::onLoad().
amci_payload_t * AmPrecodedFile::payload (int payload_id) const [virtual]
from
Implements AmPayloadProvider.
The documentation for this class was generated from the following files:
AmPrecodedFile.h
AmPrecodedFile.cpp