SEMS: AmB2BMedia Class Reference
AmB2BMedia Class Reference
Class for control over media relaying and transcoding in a B2B session.
#include <AmB2BMedia.h>
Data Structures
struct AudioStreamPair
struct RelayStreamPair
Public Member Functions
AmB2BMedia (AmB2BSession *_a, AmB2BSession *_b)
void addToMediaProcessor ()
void addToMediaProcessorUnsafe ()
void changeSession (bool a_leg, AmB2BSession *new_session)
void addReference ()
bool releaseReference ()
void replaceConnectionAddress (AmSdp &parser_sdp, bool a_leg, const string &relay_address, const string &relay_public_address)
bool replaceOffer (AmSdp &sdp, bool a_leg)
void updateStreams (bool a_leg, const AmSdp &local_sdp, const AmSdp &remote_sdp, RelayController *ctrl)
void stop (bool a_leg)
virtual int readStreams (unsigned long long ts, unsigned char *buffer)
virtual int writeStreams (unsigned long long ts, unsigned char *buffer)
virtual void processDtmfEvents ()
void sendDtmf (bool a_leg, int event, unsigned int duration_ms)
virtual void clearAudio ()
void clearAudio (bool a_leg)
virtual void clearRTPTimeout ()
virtual void onMediaProcessingTerminated ()
void mute (bool a_leg)
void unmute (bool a_leg)
bool isMuted (bool a_leg)
void setFirstStreamInput (bool a_leg, AmAudio *in)
void createHoldAnswer (bool a_leg, const AmSdp &offer, AmSdp &answer, bool use_zero_con)
void setRtpLogger (msg_logger *_logger)
void setRelayDTMFReceiving (bool enabled)
void pauseRelay ()
void restartRelay ()
void setReceiving (bool receiving_a, bool receiving_b)
void debug ()
Static Public Member Functions
static bool canRelay (const SdpMedia &m)
Detailed Description
Class for control over media relaying and transcoding in a B2B session.
This class manages RTP streams of both call legs, configures AmRtpStream relaying functionality and in case media needs to be transcoded its AmMediaSession interface implementation reads data from RTP streams in one leg and writes them to appropriate RTP streams of the other leg.
From the signaling part of the session (AmB2BSession instance for caller and for callee) it needs to be informed about local and remote SDP in each leg via updateLocalSdp() and updateRemoteSdp() methods.
Signaling parts of the session (caller and callee) needs to update outgoing SDP bodies by local address and ports of RTP streams using replaceConnectionAddress() method.
Because generating B2B SDP is no more based on AmSession's offer/answer mechanism but we relay remote's SDP with just slight changes (some payloads filtered out, some payloads added before forwarding) we don't need to remember payload ID mapping any more (local to remote). Payload IDs should be generated correctly by the remote party and we don't need to change it when relaying RTP packets.
TODO:
handle offer/answer correctly (refused new offer means old offer/answer is still valid)
handle "on hold" streams - probably should be controlled by signaling (AmB2BSession) - either we should not send audio or we should send hold music
Currently problematic, setting AmRtpStream::active to false in AmRtpStream::init doesn't help always - if some RTP packets arrive later than media session is updated the stream remains 'active' (verified with SPA 942 and twinkle)
non-audio streams - list of AmRtpStream pairs which can be just relayed
reference counting using atomic variables instead of locking
RTCP
correct sampling periods when relaying/transcoding according to values advertised in local SDP (i.e. the relayed one)
Is non-transparent SSRC & seq. no needed if some payloads can be transcoded and some relayed? Couldn't be confusing to have transparent ones for relayed but our own SSRC & seq. no for transcoded payloads? [wireshark seems to be confused] => disable transparent SSRC/seq.no if there are payloads for transcoding?
Note that forcing our own SSRC can break things if the incomming RTP stream comes from a source mixing audio from different sources - in that case we should prefer to propagate SSRC (i.e. use transparent SSRC)!
we should use our seq. numbers if transcoding is possible but propagate lost packets (i.e. remember the difference between received seq. numbers and sent ones and for the transcoding purpose use seq. number = max. already used number + 1)
configurable playout buffer type (from a test with transcoding PCMA -> PCMU between SPA 942 and 941 it seems that at simulated 20% packet loss is the audio quality better with ADAPTIVE_PLAYOUT in comparison with SIMPLE_PLAYOUT but can't say it is really big differece)
In-band DTMF detection within relayed payloads not supported yet. Do we need it?
Member Function Documentation
void AmB2BMedia::addReference ()
Adds a reference.
Both AmB2BSessions and AmMediaProcessor uses refcnt to this class; B2BSession in case of RTP relay, AmMediaProcessor in case of local media processing.
Instance of this object is created with reference counter set to zero. Thus if somebody wants to hold a reference it must call addReference() explicitly after construction!
Referenced by addToMediaProcessor().
void AmB2BMedia::addToMediaProcessor ()
To add a AmB2BMedia session to the media processor, *this method MUST be used* as it increases the refcnt.
References addReference(), and AmMediaProcessor::addSession().
void AmB2BMedia::addToMediaProcessorUnsafe ()
unsafe version (no locking of mutex)
To add a AmB2BMedia session to the media processor, *this method MUST be used* as it increases the refcnt.
References AmMediaProcessor::addSession().
virtual void AmB2BMedia::clearAudio () [inline, virtual]
Release all RTP streams of both legs and both AmB2BSessions as well.
Though readStreams(), writeStreams() or processDtmfEvents() can be called after call to clearAudio, they will do nothing because all relevant information will be rlready eleased.
Implements AmMediaSession.
References clearAudio().
Referenced by clearAudio(), and stop().
void AmB2BMedia::clearAudio (bool a_leg)
release RTP streams for one leg
void AmB2BMedia::clearRTPTimeout () [virtual]
Clear RTP timeout of all streams in both call legs.
Implements AmMediaSession.
void AmB2BMedia::onMediaProcessingTerminated () [virtual]
Callback function called once media processor releases this instance from processing loop.
Deletes itself if there are no other references! FIXME: might be returning something like "release me" and calling delete from media processor would be better?
Reimplemented from AmMediaSession.
References releaseReference().
void AmB2BMedia::pauseRelay ()
pause relaying on streams
void AmB2BMedia::processDtmfEvents () [virtual]
Calls processDtmfEvent on both AmB2BSessions for which this AmB2BMedia instance manages media.
Implements AmMediaSession.
virtual int AmB2BMedia::readStreams (unsigned long long ts, unsigned char * buffer) [inline, virtual]
Should read from all streams before writing to the other streams.
Because processing is driven by destination stream (i.e. we don't read anything unless the destination stream is ready to send something - see sendIntReached()) all processing is done in writeStreams
Implements AmMediaSession.
bool AmB2BMedia::releaseReference ()
Releases reference.
Returns true if this was the last reference, in that case the pointer to that object is now *invalid* Must be last operation in member method!
Referenced by AmB2BSession::clearRtpReceiverRelay(), and onMediaProcessingTerminated().
void AmB2BMedia::replaceConnectionAddress (AmSdp & parser_sdp, bool a_leg, const string & relay_address, const string & relay_public_address)
Replace connection address and ports within SDP.
Throws an exception (string) in case of error. (FIXME?)
References SdpConnection::address, and int2str().
Referenced by AmB2BSession::updateLocalSdp().
bool AmB2BMedia::replaceOffer (AmSdp & sdp, bool a_leg)
replace offer inside given SDP with locally generated one (media streams etc must be initialised like in case replaceConnectionAddress)
void AmB2BMedia::restartRelay ()
restart relaying on streams
void AmB2BMedia::sendDtmf (bool a_leg, int event, unsigned int duration_ms)
Sends DTMF using the given call leg
Referenced by SBCCallLeg::onDtmf().
void AmB2BMedia::setReceiving (bool receiving_a, bool receiving_b)
set 'receving' property of RTP/relay streams (not receiving=drop incoming packets)
set receving of RTP/relay streams (not receiving=drop incoming packets)
void AmB2BMedia::setRelayDTMFReceiving (bool enabled)
enable or disable DTMF receiving on relay streams
void AmB2BMedia::stop (bool a_leg)
Clear audio for given leg and stop processing if both legs stopped.
Releases all RTP streams and removes itself from media processor if still there.
References clearAudio(), AmMediaSession::isProcessingMedia(), and AmMediaProcessor::removeSession().
Referenced by AmB2BSession::clearRtpReceiverRelay().
void AmB2BMedia::updateStreams (bool a_leg, const AmSdp & local_sdp, const AmSdp & remote_sdp, RelayController * ctrl)
Update media session with local & remote SDP.
References SdpConnection::address.
Referenced by AmB2BSession::onSdpCompleted().
int AmB2BMedia::writeStreams (unsigned long long ts, unsigned char * buffer) [virtual]
Read and write all RTP streams if data are to be written (see readStreams()).
Implements AmMediaSession.
The documentation for this class was generated from the following files:
AmB2BMedia.h
AmB2BMedia.cpp