SEMS: AmAudioRtpFormat Class Reference
AmAudioRtpFormat Class Reference
RTP audio format.
#include <AmRtpAudio.h>
Public Member Functions
unsigned int getTSRate ()
unsigned int getFrameSize ()
int setCurrentPayload (Payload pl)
Protected Member Functions
void initCodec ()
Protected Attributes
unsigned int frame_size
Detailed Description
RTP audio format.
Member Function Documentation
unsigned int AmAudioRtpFormat::getTSRate () [inline]
return the timestamp sampling rate
Referenced by AmRtpAudio::put().
void AmAudioRtpFormat::initCodec () [protected, virtual]
from AmAudioFormat
Reimplemented from AmAudioFormat.
References AmAudioFormat::codec, AmAudioFormat::h_codec, amci_codec_t::id, and amci_codec_t::init.
int AmAudioRtpFormat::setCurrentPayload (Payload pl)
changes payload. returns != 0 on error.
References AmAudioFormat::channels, AmAudioFormat::codec, AmAudioFormat::codec_id, AmAudioFormat::destroyCodec(), and AmAudioFormat::rate.
Referenced by AmRtpAudio::init().
The documentation for this class was generated from the following files:
AmRtpAudio.h
AmRtpAudio.cpp