SEMS: MyJukeboxDialog Class Reference
MyJukeboxDialog Class Reference
Public Member Functions
void onSessionStart ()
void onDtmf (int event, int duration)
void process (AmEvent *ev)
void onBye (const AmSipRequest &req)
Member Function Documentation
void MyJukeboxDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::setStopped().
void MyJukeboxDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References int2str(), and AmAudioFile::open().
void MyJukeboxDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
void MyJukeboxDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
The documentation for this class was generated from the following files:
MyJukebox.h
MyJukebox.cpp