SEMS: AmUACAuth Class Reference
AmUACAuth Class Reference
Static Public Member Functions
static UACAuthCred * unpackCredentials (const AmArg &arg)
static bool enable (AmSession *s)
Member Function Documentation
bool AmUACAuth::enable (AmSession * s) [static]
enable SIP UAC authentication
Returns:
true if successful
References AmSession::addHandler(), and AmPlugIn::getFactory4Seh().
Referenced by EarlyRecordFactory::onInvite(), AnnouncementFactory::onInvite(), DtmfTesterFactory::onInvite(), Click2DialFactory::onInvite(), AnnounceAuthFactory::onInvite(), CallBackFactory::onInvite(), AnnRecorderFactory::onInvite(), DSMFactory::onInvite(), and WebConferenceFactory::onInvite().
UACAuthCred * AmUACAuth::unpackCredentials (const AmArg & arg) [static]
unpack UAC auth credentials from an AmArg
Returns:
UACAuthCred object, NULL if failed
Referenced by EarlyRecordFactory::onInvite(), AnnouncementFactory::onInvite(), DtmfTesterFactory::onInvite(), AnnRecorderFactory::onInvite(), DSMFactory::onInvite(), and WebConferenceFactory::onInvite().
The documentation for this class was generated from the following files:
AmUACAuth.h
AmUACAuth.cpp