SEMS: AnnouncementDialog Class Reference
AnnouncementDialog Class Reference
announcement session logic implementation
#include <Announcement.h>
Public Member Functions
AnnouncementDialog (const string &filename, UACAuthCred *credentials=NULL)
void onSessionStart ()
void onBye (const AmSipRequest &req)
void onDtmf (int event, int duration_msec)
void process (AmEvent *event)
UACAuthCred * getCredentials ()
Detailed Description
announcement session logic implementation
Member Function Documentation
void AnnouncementDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
void AnnouncementDialog::onDtmf (int event, int duration) [inline, virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
void AnnouncementDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmAudioFile::open().
void AnnouncementDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmSipDialog::bye(), and AmSession::setStopped().
The documentation for this class was generated from the following files:
Announcement.h
Announcement.cpp