SEMS: RtmpAudio Class Reference
RtmpAudio Class Reference
Public Member Functions
RtmpAudio (RtmpSender *s)
int get (unsigned long long system_ts, unsigned char *buffer, int output_sample_rate, unsigned int nb_samples)
int put (unsigned long long system_ts, unsigned char *buffer, int output_sample_rate, unsigned int size)
void bufferPacket (const RTMPPacket &p)
void add_to_history (int16_t *, unsigned int)
unsigned int conceal_loss (unsigned int, unsigned char *)
void setSenderPtr (RtmpSender *s)
void setPlayStreamID (unsigned int stream_id)
Protected Member Functions
int read (unsigned int user_ts, unsigned int size)
int write (unsigned int user_ts, unsigned int size)
Member Function Documentation
int RtmpAudio::get (unsigned long long system_ts, unsigned char * buffer, int output_sample_rate, unsigned int nb_samples) [virtual]
Get some samples from input stream.
Warning:
For packet based payloads / file formats, use:
           nb_sample = input buffer size / sample size of the reference format
whereby the format with/from which the codec works is the reference one.
Returns:
# bytes read, else -1 if error (0 is OK)
Reimplemented from AmAudio.
References AmAdaptivePlayout::read(), AmAudio::resampleOutput(), AmAudio::samples, and AmAudio::scaleSystemTS().
int RtmpAudio::put (unsigned long long system_ts, unsigned char * buffer, int input_sample_rate, unsigned int size) [virtual]
Put some samples to the output stream.
Warning:
For packet based payloads / file formats, use:
           nb_sample = input buffer size / sample size of the reference format
whereby the format with/from which the codec works is the reference one.
Returns:
# bytes written, else -1 if error (0 is OK)
Reimplemented from AmAudio.
References AmAudio::encode(), AmAudio::resampleInput(), AmAudio::samples, and AmAudio::scaleSystemTS().
int RtmpAudio::read (unsigned int user_ts, unsigned int size) [inline, protected, virtual]
Gets 'size' bytes directly from stream (Read,Pull).
Implements AmAudio.
int RtmpAudio::write (unsigned int user_ts, unsigned int size) [inline, protected, virtual]
Puts 'size' bytes directly from stream (Write,Push).
Implements AmAudio.
The documentation for this class was generated from the following files:
RtmpAudio.h
RtmpAudio.cpp