SEMS: EarlyAnnounceDialog Class Reference
EarlyAnnounceDialog Class Reference
session logic implementation for early_announce sessions
#include <EarlyAnnounce.h>
Public Member Functions
EarlyAnnounceDialog (const string &filename)
void onInvite (const AmSipRequest &req)
void onEarlySessionStart ()
void onBye (const AmSipRequest &req)
void onCancel (const AmSipRequest &req)
void onDtmf (int event, int duration_msec)
void process (AmEvent *event)
Detailed Description
session logic implementation for early_announce sessions
Member Function Documentation
void EarlyAnnounceDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmB2BCallerSession.
References AmSession::setStopped().
void EarlyAnnounceDialog::onCancel (const AmSipRequest & req) [virtual]
onCancel will be called if a CANCEL for a running dialog has been received. At this point, the CANCEL transaction has been replied with 200.
A normal plug-in does not have to do anything special, as normal dialogs are immediatly replied with 200 or error code.
Note: You are still responsible for responding the initial transaction.
Reimplemented from AmB2BCallerSession.
References AmBasicSipDialog::reply(), and AmSession::setStopped().
void EarlyAnnounceDialog::onDtmf (int event, int duration) [inline, virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
void EarlyAnnounceDialog::onEarlySessionStart () [virtual]
Hook called when an early session starts (SDP OA completed + dialog in early state)
Reimplemented from AmSession.
References AmAudioFile::open(), and AmSession::setReceiving().
void EarlyAnnounceDialog::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmB2BCallerSession.
References AmMimeBody::addPart(), and AmBasicSipDialog::reply().
void EarlyAnnounceDialog::process (AmEvent * event) [virtual]
See also:
AmEventQueue
Reimplemented from AmB2BSession.
References get_header_keyvalue(), AmB2BSession::recvd_req, AmB2BCallerSession::relayEvent(), AmBasicSipDialog::reply(), AmSession::setStopped(), and str2i().
The documentation for this class was generated from the following files:
EarlyAnnounce.h
EarlyAnnounce.cpp