SEMS: AmCondition< T > Class Template Reference
AmCondition< T > Class Template Reference
C++ Wrapper class for pthread condition.
#include <AmThread.h>
Public Member Functions
AmCondition (const T &_t)
void set (const T &newval)
T get ()
void wait_for ()
bool wait_for_to (unsigned long msec)
Detailed Description
template<class T>
class AmCondition< T >
C++ Wrapper class for pthread condition.
Member Function Documentation
template<class T> void AmCondition< T >::set (const T & newval) [inline]
Change the condition's value.
Referenced by AmSessionAudioConnector::block(), AmSessionContainer::createSession(), AmMediaSession::onMediaProcessingStarted(), AmSessionAudioConnector::release(), AmMailDeamon::sendQueued(), and AmSession::setStopped().
template<class T> void AmCondition< T >::wait_for () [inline]
Waits for the condition to be true.
Referenced by XmlRpc::MultithreadXmlRpcServer::acceptConnection(), and AmSessionAudioConnector::waitReleased().
template<class T> bool AmCondition< T >::wait_for_to (unsigned long msec) [inline]
Waits for the condition to be true or a timeout.
The documentation for this class was generated from the following file:
AmThread.h