SEMS: AmRtpDtmfDetector Class Reference
AmRtpDtmfDetector Class Reference
RTP DTMF detector.
#include <AmDtmfDetector.h>
Public Member Functions
AmRtpDtmfDetector (AmKeyPressSink *keysink)
void process (AmRtpDtmfEvent *event)
void checkTimeout ()
Detailed Description
RTP DTMF detector.
This class implements detection of DTMF sent via RTP
Constructor & Destructor Documentation
AmRtpDtmfDetector::AmRtpDtmfDetector (AmKeyPressSink * keysink)
Constructor
Parameters:
keysink is the sink for detected keys
Member Function Documentation
void AmRtpDtmfDetector::process (AmRtpDtmfEvent * event)
Process RTP DTMF event
References AmDtmfEvent::event(), AmKeyPressSink::flushKey(), AmKeyPressSink::registerKeyPressed(), and AmRtpDtmfEvent::volume().
The documentation for this class was generated from the following files:
AmDtmfDetector.h
AmDtmfDetector.cpp