SEMS: AmBasicSipEventHandler Class Reference
AmBasicSipEventHandler Class Reference
base class for SIP request/reply event handler
#include <AmBasicSipDialog.h>
Public Member Functions
virtual void onSipRequest (const AmSipRequest &req)
virtual void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_status)
virtual void onSendRequest (AmSipRequest &req, int &flags)
virtual void onSendReply (const AmSipRequest &req, AmSipReply &reply, int &flags)
virtual void onRequestSent (const AmSipRequest &req)
virtual void onReplySent (const AmSipRequest &req, const AmSipReply &reply)
virtual void onRemoteDisappeared (const AmSipReply &reply)
virtual void onLocalTerminate (const AmSipReply &reply)
virtual void onFailure ()
virtual void onTransFinished ()
Detailed Description
base class for SIP request/reply event handler
Member Function Documentation
virtual void AmBasicSipEventHandler::onFailure () [inline, virtual]
Hook called when either a received request or reply has been rejected by the local SIP UA layer.
Reimplemented in AmSession.
virtual void AmBasicSipEventHandler::onLocalTerminate (const AmSipReply & reply) [inline, virtual]
Hook called when the all dialog usages should be terminated before a local reply is sent.
Reimplemented in SimpleRelayDialog.
Referenced by AmBasicSipDialog::onReplyTxed().
virtual void AmBasicSipEventHandler::onRemoteDisappeared (const AmSipReply & reply) [inline, virtual]
Hook called when the all dialog usages should be terminated after a reply received from the far end, or a locally generated timeout (408).
Reimplemented in AmSession, AmB2BCallerSession, CallLeg, AmB2BSession, SBCCallLeg, SimpleRelayDialog, and DSMCall.
Referenced by AmBasicSipDialog::onRxReplyStatus().
virtual void AmBasicSipEventHandler::onReplySent (const AmSipRequest & req, const AmSipReply & reply) [inline, virtual]
Hook called after a reply has been sent
Reimplemented in AmSipSubscriptionDialog, AmB2BSession, SimpleRelayDialog, and SubscriptionDialog.
Referenced by AmBasicSipDialog::onReplyTxed().
virtual void AmBasicSipEventHandler::onRequestSent (const AmSipRequest & req) [inline, virtual]
Hook called after a request has been sent
Reimplemented in AmSipSubscriptionDialog, AmB2BSession, SimpleRelayDialog, and SubscriptionDialog.
Referenced by AmBasicSipDialog::onRequestTxed().
virtual void AmBasicSipEventHandler::onSendReply (const AmSipRequest & req, AmSipReply & reply, int & flags) [inline, virtual]
Hook called before a reply is sent
Reimplemented in AmSession, and AmSIPRegistration.
Referenced by AmBasicSipDialog::onTxReply().
virtual void AmBasicSipEventHandler::onSendRequest (AmSipRequest & req, int & flags) [inline, virtual]
Hook called before a request is sent
Reimplemented in AmSession, SBCCallLeg, DSMCallCalleeSession, SimpleRelayDialog, and AmSIPRegistration.
Referenced by AmBasicSipDialog::onTxRequest().
virtual void AmBasicSipEventHandler::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_status) [inline, virtual]
Hook called when a reply has been received
Reimplemented in AmSession, AmSipSubscriptionDialog, CallLeg, AmB2ABCalleeSession, AmB2BSession, SBCCallLeg, DSMCallCalleeSession, ConferenceDialog, IvrDialog, CallGenDialog, SimpleRelayDialog, AmSIPRegistration, WebConferenceDialog, DSMCall, AnnounceTransferDialog, RtmpSession, SubscriptionDialog, and RegisterDialog.
Referenced by AmBasicSipDialog::onRxReply().
virtual void AmBasicSipEventHandler::onSipRequest (const AmSipRequest & req) [inline, virtual]
Hook called when a request has been received
Reimplemented in AmSession, AmSipSubscriptionDialog, CallLeg, AmB2BSession, SBCCallLeg, ConferenceDialog, IvrDialog, SimpleRelayDialog, DSMCall, AnnounceTransferDialog, SubscriptionDialog, and GWSession.
Referenced by AmSipDialog::onRxReqSanity(), and AmBasicSipDialog::onRxRequest().
The documentation for this class was generated from the following file:
AmBasicSipDialog.h