SEMS: AnnRecorderDialog Class Reference
AnnRecorderDialog Class Reference
announcement session logic implementation
#include <AnnRecorder.h>
Public Member Functions
AnnRecorderDialog (const std::map< string, string > &params, AmPromptCollection &prompts, UACAuthCred *credentials=NULL)
void onSessionStart ()
void onBye (const AmSipRequest &req)
void onDtmf (int event, int duration_msec)
void process (AmEvent *event)
UACAuthCred * getCredentials ()
Detailed Description
announcement session logic implementation
Member Function Documentation
void AnnRecorderDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::setStopped().
void AnnRecorderDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist(), AmSipDialog::bye(), AmAudioFile::close(), AmSession::getLocalTag(), AmAudioFile::open(), AmSession::removeTimers(), and AmSession::setStopped().
void AnnRecorderDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist().
void AnnRecorderDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist(), AmSipDialog::bye(), AmArg::get(), AmSession::setStopped(), and AmSession::setTimer().
The documentation for this class was generated from the following files:
AnnRecorder.h
AnnRecorder.cpp