SEMS: WebConferenceFactory Class Reference
WebConferenceFactory Class Reference
Public Member Functions
WebConferenceFactory (const string &_app_name)
AmSession * onInvite (const AmSipRequest &, const string &app_name, const map< string, string > &app_params)
AmSession * onInvite (const AmSipRequest &req, const string &app_name, AmArg &session_params)
int onLoad ()
bool isValidConference (const string &conf_id, const string &participant_id)
bool newParticipant (const string &conf_id, const string &localtag, const string &number, const string &participant_id, bool check_exisiting=true)
void updateStatus (const string &conf_id, const string &localtag, ConferenceRoomParticipant::ParticipantStatus status, const string &reason)
void callStats (bool success, unsigned int connect_t)
void closeExpiredRooms ()
WebConferenceFactory * getInstance ()
void invoke (const string &method, const AmArg &args, AmArg &ret)
void roomDelete (const string &room, const string &adminpin, AmArg &ret, bool ignore_adminpin)
void roomCreate (const AmArg &args, AmArg &ret)
void roomInfo (const AmArg &args, AmArg &ret)
void roomDelete (const AmArg &args, AmArg &ret)
void changeRoomAdminpin (const AmArg &args, AmArg &ret)
void roomAddParticipant (const AmArg &args, AmArg &ret)
void dialout (const AmArg &args, AmArg &ret)
void kickout (const AmArg &args, AmArg &ret)
void mute (const AmArg &args, AmArg &ret)
void unmute (const AmArg &args, AmArg &ret)
void serverInfo (const AmArg &args, AmArg &ret)
void vqRoomFeedback (const AmArg &args, AmArg &ret)
void vqCallFeedback (const AmArg &args, AmArg &ret)
void vqConferenceFeedback (const AmArg &args, AmArg &ret)
void resetFeedback (const AmArg &args, AmArg &ret)
void flushFeedback (const AmArg &args, AmArg &ret)
void getRoomPassword (const AmArg &args, AmArg &ret)
void listRooms (const AmArg &args, AmArg &ret)
void findParticipant (const AmArg &args, AmArg &ret)
Static Public Attributes
static string DigitsDir
static PlayoutType m_PlayoutType = ADAPTIVE_PLAYOUT
static string urlbase = ""
static string MasterPassword
static int ParticipantExpiredDelay
static int RoomExpiredDelay
static int RoomSweepInterval
static bool ignore_pin = false
static bool PrivateRoomsMode = false
static bool LoopFirstParticipantPrompt = false
static unsigned int LonelyUserTimer = 0
static bool room_pin_split = false
static unsigned int room_pin_split_pos = 0
static string participant_id_paramname
static string participant_id_hdr = "X-ParticipantID"
Member Function Documentation
AmSession * WebConferenceFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
References AmSessionEventHandlerFactory::onInvite().
AmSession * WebConferenceFactory::onInvite (const AmSipRequest & req, const string & app_name, AmArg & session_params) [virtual]
Creates a dialog state on new UAC request.
Parameters:
session_params parameters passed to the new session by the caller.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Reimplemented from AmSessionFactory.
References AmUACAuth::enable(), AmSession::setUri(), and AmUACAuth::unpackCredentials().
int WebConferenceFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
The documentation for this class was generated from the following files:
WebConference.h
WebConference.cpp