SEMS: AmSipSubscription Class Reference
AmSipSubscription Class Reference
SIP Subscription collection.
#include <AmSipSubscription.h>
Public Member Functions
AmSipSubscription (AmBasicSipDialog *dlg, AmEventQueue *ev_q)
virtual void allowUnsolicitedNotify (bool allow)
bool isActive ()
void terminate ()
bool subscriptionExists (SingleSubscription::Role role, const string &event, const string &id)
bool onRequestIn (const AmSipRequest &req)
void onRequestSent (const AmSipRequest &req)
bool onReplyIn (const AmSipRequest &req, const AmSipReply &reply)
void onReplySent (const AmSipRequest &req, const AmSipReply &reply)
virtual void onNotify (const AmSipRequest &req, SingleSubscription *sub)
virtual void onFailureReply (const AmSipReply &reply, SingleSubscription *sub)
virtual void onTimeout (int timer_id, SingleSubscription *sub)
virtual void debug ()
Protected Types
typedef list
< SingleSubscription * > Subscriptions
typedef map< unsigned int,
Subscriptions::iterator > CSeqMap
Protected Member Functions
SingleSubscription * makeSubscription (const AmSipRequest &req, bool uac)
Subscriptions::iterator createSubscription (const AmSipRequest &req, bool uac)
Subscriptions::iterator matchSubscription (const AmSipRequest &req, bool uac)
Subscriptions::iterator findSubscription (SingleSubscription::Role role, const string &event, const string &id)
void removeSubFromUACCSeqMap (Subscriptions::iterator sub)
void removeSubFromUASCSeqMap (Subscriptions::iterator sub)
virtual void removeSubscription (Subscriptions::iterator sub)
virtual SingleSubscription * newSingleSubscription (SingleSubscription::Role role, const string &event, const string &id)
Protected Attributes
AmBasicSipDialog * dlg
AmEventQueue * ev_q
Subscriptions subs
CSeqMap uas_cseq_map
CSeqMap uac_cseq_map
bool allow_subless_notify
Friends
class SingleSubscription
Detailed Description
SIP Subscription collection.
This class contains all the suscriptions sharing the same dialog.
Constructor & Destructor Documentation
AmSipSubscription::AmSipSubscription (AmBasicSipDialog * dlg, AmEventQueue * ev_q)
AmSipSubscription
Member Function Documentation
bool AmSipSubscription::isActive ()
Is there at least one active subscription?
AmSipSubscription::Subscriptions::iterator AmSipSubscription::matchSubscription (const AmSipRequest & req, bool uac) [protected]
match single subscription if none, create one
References get_header_param(), and strip_header_params().
bool AmSipSubscription::subscriptionExists (SingleSubscription::Role role, const string & event, const string & id)
Check if a subscription exists
Referenced by SubscriptionDialog::onSipReply(), and AmB2BSession::onSipReply().
void AmSipSubscription::terminate ()
Terminate all subscriptions
Referenced by SubscriptionDialog::terminate().
The documentation for this class was generated from the following files:
AmSipSubscription.h
AmSipSubscription.cpp