SEMS: AmSessionFactory Class Reference
AmSessionFactory Class Reference
Interface for plugins to create sessions.
#include <AmApi.h>
Public Member Functions
void configureSession (AmSession *sess)
AmSessionFactory (const string &name)
virtual AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)=0
virtual AmSession * onInvite (const AmSipRequest &req, const string &app_name, AmArg &session_params)
virtual AmSession * onRefer (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
virtual AmSession * onRefer (const AmSipRequest &req, const string &app_name, AmArg &session_params)
virtual void onOoDRequest (const AmSipRequest &req)
Static Public Member Functions
static void replyOptions (const AmSipRequest &req)
Protected Member Functions
int configureModule (AmConfigReader &cfg)
Detailed Description
Interface for plugins to create sessions.
Member Function Documentation
int AmSessionFactory::configureModule (AmConfigReader & cfg) [protected]
This reads the module configuration from cfg into the modules mod_conf.
Referenced by GatewayFactory::onLoad(), AnnounceTransferFactory::onLoad(), AnnounceB2BFactory::onLoad(), DtmfTesterFactory::onLoad(), AnnouncementFactory::onLoad(), CacheAnnounceFactory::onLoad(), Click2DialFactory::onLoad(), ServiceLineFactory::onLoad(), EarlyAnnounceFactory::onLoad(), PinAuthConferenceFactory::onLoad(), AnnounceAuthFactory::onLoad(), RegistrationAgentFactory::onLoad(), VoiceboxFactory::onLoad(), AnnRecorderFactory::onLoad(), CallBackFactory::onLoad(), ConferenceFactory::onLoad(), PySemsFactory::onLoad(), AnswerMachineFactory::onLoad(), IvrFactory::onLoad(), and DSMFactory::onLoad().
void AmSessionFactory::configureSession (AmSession * sess)
This function applys the module configuration
virtual AmSession* AmSessionFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [pure virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implemented in WebConferenceFactory, DSMFactory, SBCFactory, IvrFactory, AnswerMachineFactory, ConferenceFactory, CallGenFactory, RtmpFactory, AnnRecorderFactory, CallBackFactory, RegistrationAgentFactory, VoiceboxFactory, AnnounceAuthFactory, EarlyAnnounceFactory, PinAuthConferenceFactory, ServiceLineFactory, Click2DialFactory, CacheAnnounceFactory, AnnouncementFactory, DtmfTesterFactory, SimpleConferenceFactory, AnnounceB2BFactory, AnnounceTransferFactory, UrlCatcherFactory, PrecodedFactory, EchoFactory, JukecallFactory, b2b_connectFactory, MyCCFactory, MyJukeboxFactory, EarlyRecordFactory, MyAnnounceAppFactory, MyConfigurableAppFactory, MyAppFactory, and MyAppFactory.
Referenced by AmSessionContainer::createSession(), and onInvite().
AmSession * AmSessionFactory::onInvite (const AmSipRequest & req, const string & app_name, AmArg & session_params) [virtual]
Creates a dialog state on new UAC request.
Parameters:
session_params parameters passed to the new session by the caller.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Reimplemented in WebConferenceFactory, DSMFactory, CallGenFactory, AnnRecorderFactory, CallBackFactory, PinAuthConferenceFactory, Click2DialFactory, AnnouncementFactory, DtmfTesterFactory, SimpleConferenceFactory, and EarlyRecordFactory.
References onInvite().
void AmSessionFactory::onOoDRequest (const AmSipRequest & req) [virtual]
Method to receive any out-of-dialog request other than INVITE and REFER
Warning: This method should not make any expensive processing as it would block the thread posting the event!
Reimplemented in SBCFactory.
References AmBasicSipDialog::reply_error().
AmSession * AmSessionFactory::onRefer (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new REFER with local-tag.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Reimplemented in ConferenceFactory.
Referenced by AmSessionContainer::createSession(), and onRefer().
AmSession * AmSessionFactory::onRefer (const AmSipRequest & req, const string & app_name, AmArg & session_params) [virtual]
Creates a dialog state on new REFER with local-tag. Passes session_params to the new session.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
References onRefer().
The documentation for this class was generated from the following files:
AmApi.h
AmApi.cpp