SEMS: AmSipSubscriptionDialog Class Reference
AmSipSubscriptionDialog Class Reference
Public Member Functions
AmSipSubscriptionDialog (const AmSipSubscriptionInfo &info, const string &sess_link, AmEventQueue *ev_q=NULL)
int subscribe (int expires)
string getDescription ()
void onNotify (const AmSipRequest &req, SingleSubscription *sub)
void onFailureReply (const AmSipReply &reply, SingleSubscription *sub)
void onTimeout (int timer_id, SingleSubscription *sub)
void onSipRequest (const AmSipRequest &req)
void onRequestSent (const AmSipRequest &req)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_status)
void onReplySent (const AmSipRequest &req, const AmSipReply &reply)
Member Function Documentation
void AmSipSubscriptionDialog::onNotify (const AmSipRequest & req, SingleSubscription * sub) [virtual]
AmSipSubscription interface
Reimplemented from AmSipSubscription.
References AmMimeBody::empty(), AmSessionContainer::postEvent(), and AmBasicSipDialog::reply().
void AmSipSubscriptionDialog::onReplySent (const AmSipRequest & req, const AmSipReply & reply) [inline, virtual]
Hook called after a reply has been sent
Reimplemented from AmBasicSipEventHandler.
void AmSipSubscriptionDialog::onRequestSent (const AmSipRequest & req) [inline, virtual]
Hook called after a request has been sent
Reimplemented from AmBasicSipEventHandler.
void AmSipSubscriptionDialog::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_status) [inline, virtual]
Hook called when a reply has been received
Reimplemented from AmBasicSipEventHandler.
void AmSipSubscriptionDialog::onSipRequest (const AmSipRequest & req) [inline, virtual]
AmBasicDialogEventHandler interface
Reimplemented from AmBasicSipEventHandler.
The documentation for this class was generated from the following files:
AmSipSubscription.h
AmSipSubscription.cpp