SEMS: UACAuth Class Reference
UACAuth Class Reference
SessionEventHandler for implementing uac authentication.
#include <UACAuth.h>
Public Member Functions
UACAuth (AmBasicSipDialog *dlg, UACAuthCred *cred)
virtual bool process (AmEvent *)
virtual bool onSipEvent (AmSipEvent *)
virtual bool onSipRequest (const AmSipRequest &)
virtual bool onSipReply (const AmSipRequest &, const AmSipReply &, AmBasicSipDialog::Status old_status)
virtual bool onSendRequest (AmSipRequest &req, int &flags)
virtual bool onSendReply (const AmSipRequest &req, AmSipReply &reply, int &flags)
Static Public Member Functions
static string calcNonce ()
static bool checkNonce (const string &nonce)
static void checkAuthentication (const AmSipRequest *req, const string &realm, const string &user, const string &pwd, AmArg &ret)
static void setServerSecret (const string &secret)
static bool tc_isequal (const std::string &s1, const std::string &s2)
static bool tc_isequal (const char *s1, const char *s2, size_t len)
Detailed Description
SessionEventHandler for implementing uac authentication.
Member Function Documentation
string UACAuth::calcNonce () [static]
calculate nonce: time-stamp H(time-stamp private-key)
References cvt_hex(), and int2hex().
bool UACAuth::checkNonce (const string & nonce) [static]
check nonce integrity.
Returns:
true if correct
References cvt_hex(), and tc_isequal().
bool UACAuth::tc_isequal (const std::string & s1, const std::string & s2) [static]
time-constant string compare function (but leaks timing of length mismatch)
Returns:
true if matching
time-constant string compare function, but leaks timing of length mismatch
Referenced by checkNonce().
bool UACAuth::tc_isequal (const char * s1, const char * s2, size_t len) [static]
time-constant string compare function
Returns:
true if matching
time-constant string compare function, but leaks timing of length mismatch
The documentation for this class was generated from the following files:
UACAuth.h
UACAuth.cpp