SEMS: CCDSMModule Class Reference
CCDSMModule Class Reference
Public Member Functions
virtual void invoke (const string &method, const AmArg &args, AmArg &ret)
virtual int onLoad ()
virtual void onUnload ()
bool init (SBCCallLeg *call, const map< string, string > &values)
CCChainProcessing onInitialInvite (SBCCallLeg *call, InitialInviteHandlerParams &params)
CCChainProcessing onBLegRefused (SBCCallLeg *call, const AmSipReply &reply)
void onDestroyLeg (SBCCallLeg *call)
void onStateChange (SBCCallLeg *call, const CallLeg::StatusChangeCause &cause)
CCChainProcessing onInDialogRequest (SBCCallLeg *call, const AmSipRequest &req)
CCChainProcessing onInDialogReply (SBCCallLeg *call, const AmSipReply &reply)
CCChainProcessing onEvent (SBCCallLeg *call, AmEvent *e)
CCChainProcessing onDtmf (SBCCallLeg *call, int event, int duration)
CCChainProcessing putOnHold (SBCCallLeg *call)
CCChainProcessing resumeHeld (SBCCallLeg *call, bool send_reinvite)
CCChainProcessing createHoldRequest (SBCCallLeg *call, AmSdp &sdp)
CCChainProcessing handleHoldReply (SBCCallLeg *call, bool succeeded)
int relayEvent (SBCCallLeg *call, AmEvent *e)
bool init (SBCCallProfile &profile, SimpleRelayDialog *relay, void *&user_data)
void initUAC (const AmSipRequest &req, void *user_data)
void initUAS (const AmSipRequest &req, void *user_data)
void finalize (void *user_data)
void onSipRequest (const AmSipRequest &req, void *user_data)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status, void *user_data)
void onB2BRequest (const AmSipRequest &req, void *user_data)
void onB2BReply (const AmSipReply &reply, void *user_data)
Static Public Member Functions
static CCDSMModule * instance ()
Member Function Documentation
bool CCDSMModule::init (SBCCallLeg * call, const map< string, string > & values) [virtual]
First method called from extended CC module interface. It should initialize CC module internals (values from sbcprofile.conf can be used for evaluating CC module parameters).
Reimplemented from ExtendedCCInterface.
CCChainProcessing CCDSMModule::onBLegRefused (SBCCallLeg * call, const AmSipReply & reply) [virtual]
one of existing B legs is refused, handle redirect here or do serial fork or ...
Reimplemented from ExtendedCCInterface.
References SBCDSMInstance::onBLegRefused().
void CCDSMModule::onDestroyLeg (SBCCallLeg * call) [virtual]
called when the call leg is being destroyed, useful to cleanup used resources
Reimplemented from ExtendedCCInterface.
CCChainProcessing CCDSMModule::onEvent (SBCCallLeg * call, AmEvent * e) [virtual]
called before any other processing for the event is done
Reimplemented from ExtendedCCInterface.
CCChainProcessing CCDSMModule::onInDialogRequest (SBCCallLeg * call, const AmSipRequest & req) [virtual]
called from A/B leg when in-dialog request comes in
Reimplemented from ExtendedCCInterface.
References SBCDSMInstance::onInDialogRequest().
CCChainProcessing CCDSMModule::onInitialInvite (SBCCallLeg * call, InitialInviteHandlerParams & params) [virtual]
called from A-leg onInvite
can be used for forking or handling INVITE with Replaces header
Reimplemented from ExtendedCCInterface.
References SBCDSMInstance::onInitialInvite().
int CCDSMModule::relayEvent (SBCCallLeg * call, AmEvent * e) [virtual]
Possibility to influence messages relayed to the B2B peer leg. return value:
lower than 0 means error (returned upstream, the one returning error is responsible for destrying the event instance)
greater than 0 means "stop processing and return 0 upstream"
equal to 0 means "continue processing"
Reimplemented from ExtendedCCInterface.
The documentation for this class was generated from the following files:
CCDSM.h
CCDSM.cpp