SEMS: AmB2ABCallerSession Class Reference
AmB2ABCallerSession Class Reference
Caller leg of a B2AB session.
#include <AmB2ABSession.h>
Public Types
enum CalleeStatus {
None = 0, NoReply, Early, Ringing,
Connected
}
Public Member Functions
CalleeStatus getCalleeStatus ()
void connectCallee (const string &remote_party, const string &remote_uri, const string &local_party, const string &local_uri, const string &headers="")
void terminateOtherLeg ()
Protected Member Functions
virtual AmB2ABCalleeSession * createCalleeSession ()
void relayEvent (AmEvent *ev)
void onB2ABEvent (B2ABEvent *ev)
void onBeforeDestroy ()
Detailed Description
Caller leg of a B2AB session.
Member Function Documentation
void AmB2ABCallerSession::onB2ABEvent (B2ABEvent * ev) [protected, virtual]
B2ABEvent handler
Reimplemented from AmB2ABSession.
Reimplemented in b2b_connectDialog.
References AmB2ABSession::connectSession(), and AmB2ABSession::terminateLeg().
void AmB2ABCallerSession::onBeforeDestroy () [protected, virtual]
called in the session thread before the session is destroyed, i.e. after the main event loop has finished
Reimplemented from AmSession.
Reimplemented in PySemsB2ABDialog.
References AmB2ABSession::connector, and AmSessionAudioConnector::waitReleased().
void AmB2ABCallerSession::relayEvent (AmEvent * ev) [protected, virtual]
Relay one event to the other side.
Reimplemented from AmB2ABSession.
References AmSession::getLocalTag(), and AmB2ABSession::other_id.
Referenced by JukecallSession::onDtmf().
void AmB2ABCallerSession::terminateOtherLeg () [virtual]
Terminate the other leg and forget it.
Reimplemented from AmB2ABSession.
Referenced by b2b_connectDialog::onBye().
The documentation for this class was generated from the following files:
AmB2ABSession.h
AmB2ABSession.cpp