SEMS: SubscriptionDialog Class Reference
SubscriptionDialog Class Reference
B2B Subscription UA.
#include <SubscriptionDialog.h>
Public Member Functions
SubscriptionDialog (SBCCallProfile &profile, vector< AmDynInvoke * > &cc_modules, AmSipSubscription *subscription=NULL, atomic_ref_cnt *parent_obj=NULL)
SubscriptionDialog (AmSipSubscription *subscription=NULL, atomic_ref_cnt *parent_obj=NULL)
void terminate ()
bool terminated ()
void onSipRequest (const AmSipRequest &req)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
void onRequestSent (const AmSipRequest &req)
void onReplySent (const AmSipRequest &req, const AmSipReply &reply)
Protected Member Functions
void process (AmEvent *ev)
bool getMappedReferID (unsigned int refer_id, unsigned int &mapped_id) const
virtual void insertMappedReferID (unsigned int refer_id, unsigned int mapped_id)
Protected Attributes
AmSipSubscription * subs
RelayMap refer_id_map
Detailed Description
B2B Subscription UA.
This class represents one side of a B2BUA supporting SIP standalone subscriptions.
Constructor & Destructor Documentation
SubscriptionDialog::SubscriptionDialog (SBCCallProfile & profile, vector< AmDynInvoke * > & cc_modules, AmSipSubscription * subscription = NULL, atomic_ref_cnt * parent_obj = NULL)
SubscriptionDialog
Member Function Documentation
bool SubscriptionDialog::getMappedReferID (unsigned int refer_id, unsigned int & mapped_id) const [protected]
Returns true and sets mapped_id if refer_id corresponds to an existing refer event subscription which has been relayed.
Referenced by onSipRequest().
void SubscriptionDialog::onReplySent (const AmSipRequest & req, const AmSipReply & reply) [virtual]
Hook called after a reply has been sent
Reimplemented from SimpleRelayDialog.
void SubscriptionDialog::onRequestSent (const AmSipRequest & req) [virtual]
Hook called after a request has been sent
Reimplemented from SimpleRelayDialog.
void SubscriptionDialog::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_status) [virtual]
Hook called when a reply has been received
Reimplemented from SimpleRelayDialog.
References int2str(), and AmSipSubscription::subscriptionExists().
void SubscriptionDialog::onSipRequest (const AmSipRequest & req) [virtual]
Hook called when a request has been received
Reimplemented from SimpleRelayDialog.
References get_header_param(), getMappedReferID(), int2str(), str2int(), and strip_header_params().
void SubscriptionDialog::terminate () [inline, virtual]
correctly terminate the dialog; MUST be redefined if "terminated" method is redefined
Reimplemented from SimpleRelayDialog.
References AmSipSubscription::terminate().
The documentation for this class was generated from the following files:
SubscriptionDialog.h
SubscriptionDialog.cpp