SEMS: AmPlugIn Class Reference
AmPlugIn Class Reference
Container for loaded Plug-ins.
#include <AmPlugIn.h>
Public Member Functions
int addCodec (amci_codec_t *c)
int addPayload (amci_payload_t *p)
int addFileFormat (amci_inoutfmt_t *f)
void set_load_rtld_global (const string &plugin_name)
void init ()
int load (const string &directory, const string &plugins)
void registerLoggingPlugins ()
amci_payload_t * payload (int payload_id) const
int getDynPayload (const string &name, int rate, int encoding_param) const
void getPayloads (vector< SdpPayload > &pl_vec) const
amci_inoutfmt_t * fileFormat (const string &fmt_name, const string &ext="")
amci_subtype_t * subtype (amci_inoutfmt_t *iofmt, int subtype)
amci_subtype_t * subtype (amci_inoutfmt_t *iofmt, const string &subtype_name)
amci_codec_t * codec (int id)
AmSessionFactory * getFactory4App (const string &app_name)
bool registerFactory4App (const string &app_name, AmSessionFactory *f)
AmSessionFactory * findSessionFactory (const AmSipRequest &req, string &app_name)
AmSessionEventHandlerFactory * getFactory4Seh (const string &name)
AmDynInvokeFactory * getFactory4Di (const string &name)
AmLoggingFacility * getFactory4LogFaclty (const string &name)
Static Public Member Functions
static AmPlugIn * instance ()
static void dispose ()
static bool registerApplication (const string &app_name, AmSessionFactory *f)
static bool registerSIPEventHandler (const string &seh_name, AmSessionEventHandlerFactory *f)
static bool registerDIInterface (const string &di_name, AmDynInvokeFactory *f)
static bool registerLoggingFacility (const string &lf_name, AmLoggingFacility *f)
Detailed Description
Container for loaded Plug-ins.
Member Function Documentation
amci_codec_t * AmPlugIn::codec (int id)
Codec lookup function.
Parameters:
id Codec ID (see amci/codecs.h).
Returns:
NULL if failed.
Referenced by AmAudioFormat::getCodec().
amci_inoutfmt_t * AmPlugIn::fileFormat (const string & fmt_name, const string & ext = "")
Returns:
the suported payloads.
the order of payloads. File format lookup according to the format name and/or file extension.
Parameters:
fmt_name Format name.
ext File extension.
Returns:
NULL if failed.
Referenced by AmAudioFile::fileName2Fmt(), and AmAudioFileFormat::getSubtype().
AmSessionFactory * AmPlugIn::findSessionFactory (const AmSipRequest & req, string & app_name)
Find the proper SessionFactory for the given request.
References AmConfig::Application, AmConfig::AppSelect, get_header_param(), getFactory4App(), and run_regex_mapping().
Referenced by AmSessionContainer::createSession().
int AmPlugIn::getDynPayload (const string & name, int rate, int encoding_param) const [virtual]
Payload lookup function by name & rate
Parameters:
name Payload ID.
Returns:
-1 if failed, else the internal payload id.
Implements AmPayloadProvider.
AmSessionFactory * AmPlugIn::getFactory4App (const string & app_name)
Application lookup function
Parameters:
app_name application name
Returns:
NULL if failed (-> application not found).
Referenced by AmSessionContainer::createSession(), and findSessionFactory().
AmDynInvokeFactory * AmPlugIn::getFactory4Di (const string & name)
Dynamic invokation component
Referenced by MyCCFactory::onLoad(), MWI::onLoad(), VoiceboxFactory::onLoad(), AnnRecorderFactory::onLoad(), and AnswerMachineFactory::onLoad().
AmLoggingFacility * AmPlugIn::getFactory4LogFaclty (const string & name)
logging facility lookup function
Parameters:
name application name
Returns:
NULL if failed (-> handler not found).
AmSessionEventHandlerFactory * AmPlugIn::getFactory4Seh (const string & name)
Session event handler lookup function
Parameters:
name application name
Returns:
NULL if failed (-> handler not found).
Referenced by AmUACAuth::enable(), SBCFactory::onInvite(), GatewayFactory::onLoad(), EchoFactory::onLoad(), ConferenceFactory::onLoad(), SBCFactory::onLoad(), IvrFactory::onLoad(), and DSMFactory::onLoad().
void AmPlugIn::getPayloads (vector< SdpPayload > & pl_vec) const [virtual]
return 0, or -1 in case of error.
Implements AmPayloadProvider.
int AmPlugIn::load (const string & directory, const string & plugins)
Loads all plug-ins from the directory given as parameter.
Returns:
-1 if failed, else 0.
References AmConfig::ExcludePlugins, and explode().
Referenced by SBCFactory::onLoad().
amci_payload_t * AmPlugIn::payload (int payload_id) const [virtual]
Payload lookup function.
Parameters:
payload_id Payload ID.
Returns:
NULL if failed .
Implements AmPayloadProvider.
bool AmPlugIn::registerApplication (const string & app_name, AmSessionFactory * f) [static]
register a factory for applications
Returns:
true on success
References registerFactory4App().
Referenced by SBCFactory::onLoad().
bool AmPlugIn::registerDIInterface (const string & di_name, AmDynInvokeFactory * f) [static]
register a DI Interface module note: unprotected, use only at server startup (onLoad)
Returns:
true on success
Referenced by SBCFactory::onLoad().
bool AmPlugIn::registerFactory4App (const string & app_name, AmSessionFactory * f)
Returns:
true if this record has been inserted.
Referenced by PySemsFactory::onLoad(), IvrFactory::onLoad(), DSMFactory::onLoad(), and registerApplication().
bool AmPlugIn::registerLoggingFacility (const string & lf_name, AmLoggingFacility * f) [static]
register a logging facility note: unprotected, use only at server startup (onLoad)
Returns:
true on success
void AmPlugIn::registerLoggingPlugins ()
register logging plugins to receive logging messages
bool AmPlugIn::registerSIPEventHandler (const string & seh_name, AmSessionEventHandlerFactory * f) [static]
register a SIP Event Handler module note: unprotected, use only at server startup (onLoad)
Returns:
true on success
amci_subtype_t * AmPlugIn::subtype (amci_inoutfmt_t * iofmt, int subtype)
File format's subtype lookup function.
Parameters:
iofmt The file format.
subtype Subtype ID (see plug-in declaration for values).
Returns:
NULL if failed.
References amci_inoutfmt_t::subtypes, and amci_subtype_t::type.
Referenced by AmAudioFile::fileName2Fmt(), and AmAudioFileFormat::getSubtype().
amci_subtype_t * AmPlugIn::subtype (amci_inoutfmt_t * iofmt, const string & subtype_name)
File subtype lookup function.
Parameters:
subtype_name The subtype's name (e.g. Pcm16).
Returns:
NULL if failed.
References amci_inoutfmt_t::subtypes.
The documentation for this class was generated from the following files:
AmPlugIn.h
AmPlugIn.cpp