SEMS: AnnounceTransferDialog Class Reference
AnnounceTransferDialog Class Reference
session logic implementation for announce_transfer sessions
#include <AnnounceTransfer.h>
Public Member Functions
AnnounceTransferDialog (const string &filename)
void onInvite (const AmSipRequest &req)
void onSessionStart ()
void startSession ()
void onBye (const AmSipRequest &req)
void onSipRequest (const AmSipRequest &req)
void onSipReply (const AmSipRequest &req, const AmSipReply &rep, AmBasicSipDialog::Status old_dlg_status)
void onDtmf (int event, int duration_msec)
void process (AmEvent *event)
Detailed Description
session logic implementation for announce_transfer sessions
Member Function Documentation
void AnnounceTransferDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::setStopped().
void AnnounceTransferDialog::onDtmf (int event, int duration) [inline, virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
void AnnounceTransferDialog::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmSession.
References get_session_param().
void AnnounceTransferDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmSession::setReceiving().
void AnnounceTransferDialog::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_dlg_status) [virtual]
Entry point for SIP Replies
Reimplemented from AmSession.
References AmSipDialog::bye(), and AmSession::setStopped().
void AnnounceTransferDialog::onSipRequest (const AmSipRequest & req) [virtual]
Entry point for SIP Requests
Reimplemented from AmSession.
References AmSipDialog::bye(), AmMimeBody::getLen(), AmMimeBody::getPayload(), AmMimeBody::isContentType(), parse_return_code(), AmBasicSipDialog::reply(), AmSession::setStopped(), and strip_header_params().
void AnnounceTransferDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmSipDialog::refer().
The documentation for this class was generated from the following files:
AnnounceTransfer.h
AnnounceTransfer.cpp