SEMS: _trans_layer Class Reference
_trans_layer Class Reference
#include <trans_layer.h>
Data Structures
struct less_case_i
Public Member Functions
void register_ua (sip_ua *ua)
int register_transport (trsp_socket *trsp)
void clear_transports ()
int send_reply (sip_msg *msg, const trans_ticket *tt, const cstring &dialog_id, const cstring &to_tag, msg_logger *logger=NULL)
int send_request (sip_msg *msg, trans_ticket *tt, const cstring &dialog_id, const cstring &_next_hop, int out_interface=-1, unsigned int flags=0, msg_logger *logger=NULL)
int cancel (trans_ticket *tt, const cstring &dialog_id, unsigned int inv_cseq, const cstring &hdrs)
void received_msg (sip_msg *msg)
void timer_expired (trans_timer *t, trans_bucket *bucket, sip_trans *tr)
int find_outbound_if (sockaddr_storage *remote_ip)
void send_non_200_ack (sip_msg *reply, sip_trans *t)
int send_sl_reply (sip_msg *req, int reply_code, const cstring &reason, const cstring &hdrs, const cstring &body)
int send_sf_error_reply (const trans_ticket *tt, const sip_msg *req, int reply_code, const cstring &reason, const cstring &hdrs=cstring(), const cstring &body=cstring())
void transport_error (sip_msg *msg)
void timeout (trans_bucket *bucket, sip_trans *t)
const trans_stats & get_stats ()
Static Public Attributes
static bool accept_fr_without_totag = false
static unsigned int default_bl_ttl = DEFAULT_BL_TTL
Protected Member Functions
int set_next_hop (sip_msg *msg, cstring *next_hop, unsigned short *next_port, cstring *next_trsp)
int set_trsp_socket (sip_msg *msg, const cstring &next_trsp, int out_interface)
sip_trans * copy_uac_trans (sip_trans *tr)
int try_next_ip (trans_bucket *bucket, sip_trans *tr, bool use_new_trans)
int update_uac_reply (trans_bucket *bucket, sip_trans *t, sip_msg *msg)
int update_uac_request (trans_bucket *bucket, sip_trans *&t, sip_msg *msg)
int update_uas_request (trans_bucket *bucket, sip_trans *t, sip_msg *msg)
int update_uas_reply (trans_bucket *bucket, sip_trans *t, int reply_code)
_trans_layer ()
void process_rcvd_msg (sip_msg *msg)
Detailed Description
The transaction layer object. Uses the singleton pattern.
Constructor & Destructor Documentation
_trans_layer::_trans_layer () [protected]
Avoid external instantiation.
See also:
singleton.
Member Function Documentation
int _trans_layer::cancel (trans_ticket * tt, const cstring & dialog_id, unsigned int inv_cseq, const cstring & hdrs)
Cancels a request. A CANCEL request is sent if necessary.
Parameters:
tt transaction ticket from the original INVITE.
References sip_trans::canceled, sip_trans::clear_timer(), trsp_socket::copy_addr_to(), sip_trans::dialog_id, ht_bucket< Value >::exist(), sip_trans::flags, trans_stats::inc_sent_requests(), sip_trans::logger, sip_trans::msg, and sip_trans::state.
Referenced by timer_expired(), and update_uac_reply().
void _trans_layer::clear_transports ()
Clears all registered transport instances.
int _trans_layer::find_outbound_if (sockaddr_storage * remote_ip)
Tries to find an interface suitable for sending to the destination supplied.
Referenced by set_trsp_socket().
void _trans_layer::process_rcvd_msg (sip_msg * msg) [protected]
Processes a parsed SIP message
References sip_trans::dialog_id, trans_stats::inc_received_replies(), trans_stats::inc_received_requests(), sip_trans::logger, sip_trans::msg, sip_trans::retransmit(), send_sl_reply(), sip_trans::state, update_uac_reply(), and update_uas_request().
Referenced by received_msg(), and transport_error().
void _trans_layer::received_msg (sip_msg * msg)
Called by the transport layer when a new message has been recived.
References process_rcvd_msg(), and send_sl_reply().
int _trans_layer::register_transport (trsp_socket * trsp)
Register a transport instance. This method MUST be called at least once.
References trsp_socket::get_if(), and trsp_socket::get_transport().
void _trans_layer::register_ua (sip_ua * ua)
Register a SIP UA. This method MUST be called ONCE.
void _trans_layer::send_non_200_ack (sip_msg * reply, sip_trans * t)
Send ACK coresponding to error replies
References trsp_socket::copy_addr_to(), sip_trans::flags, trans_stats::inc_sent_requests(), sip_trans::logger, sip_trans::msg, and trsp_socket::send().
Referenced by update_uac_reply().
int _trans_layer::send_reply (sip_msg * msg, const trans_ticket * tt, const cstring & dialog_id, const cstring & to_tag, msg_logger * logger = NULL)
Sends a UAS reply. If a body is included, the hdrs parameter should include a well-formed 'Content-Type', but no 'Content-Length' header.
References trsp_socket::copy_addr_to(), sip_trans::dialog_id, ht_bucket< Value >::exist(), ht_bucket< Value >::get_id(), trsp_socket::get_transport(), trans_stats::inc_sent_replies(), int2str(), trsp_socket::is_opt_set(), trsp_socket::is_reliable(), sip_trans::last_rseq, sip_trans::logger, sip_trans::msg, ht_bucket< Value >::remove(), sip_trans::reply_status, sip_trans::reset_timer(), sip_trans::retr_addr, sip_trans::retr_buf, sip_trans::retr_len, trsp_socket::send(), and sip_trans::to_tag.
Referenced by send_sf_error_reply().
int _trans_layer::send_request (sip_msg * msg, trans_ticket * tt, const cstring & dialog_id, const cstring & _next_hop, int out_interface = -1, unsigned int flags = 0, msg_logger * logger = NULL)
Sends a UAC request. Caution: Route headers should not be added to the general header list (msg->hdrs).
Parameters:
[in] msg Pre-built message.
[out] tt transaction ticket (needed for replies & CANCEL)
References trsp_socket::copy_addr_to(), default_bl_ttl, sip_trans::dialog_id, sip_trans::flags, ht_bucket< Value >::get_id(), trans_stats::inc_sent_requests(), sip_trans::logger, sip_trans::msg, sip_trans::reset_timer(), sip_trans::retr_buf, sip_trans::retr_len, set_next_hop(), set_trsp_socket(), and sip_trans::targets.
int _trans_layer::send_sf_error_reply (const trans_ticket * tt, const sip_msg * req, int reply_code, const cstring & reason, const cstring & hdrs = cstring(), const cstring & body = cstring())
Sends a stateful error reply. If a body is included, the hdrs parameter should include a well-formed 'Content-Type', but no 'Content-Length' header.
References send_reply().
int _trans_layer::send_sl_reply (sip_msg * req, int reply_code, const cstring & reason, const cstring & hdrs, const cstring & body)
Sends a stateless reply. Useful for error replies. If a body is included, the hdrs parameter should include a well-formed 'Content-Type', but no 'Content-Length' header.
References trans_stats::inc_sent_replies(), int2str(), and trsp_socket::send().
Referenced by process_rcvd_msg(), and received_msg().
int _trans_layer::set_next_hop (sip_msg * msg, cstring * next_hop, unsigned short * next_port, cstring * next_trsp) [protected]
Fills the address structure passed and modifies R-URI and Route headers as needed.
Referenced by send_request().
int _trans_layer::set_trsp_socket (sip_msg * msg, const cstring & next_trsp, int out_interface) [protected]
Fills the local_socket attribute using the given transport and interface. If out_interface == -1, we will try hard to find an interface based on msg->remote_ip.
References find_outbound_if().
Referenced by send_request(), and try_next_ip().
void _trans_layer::timeout (trans_bucket * bucket, sip_trans * t)
Transaction timeout
References sip_trans::dialog_id, sip_trans::flags, ht_bucket< Value >::get_id(), sip_trans::msg, ht_bucket< Value >::remove(), sip_trans::reset_all_timers(), sip_trans::reset_timer(), and sip_trans::state.
Referenced by timer_expired().
void _trans_layer::timer_expired (trans_timer * t, trans_bucket * bucket, sip_trans * tr)
This is called by the transaction timer callback. At this place, the bucket is already locked, so please be quick.
References cancel(), sip_trans::clear_timer(), trsp_socket::copy_addr_to(), default_bl_ttl, ht_bucket< Value >::exist(), sip_trans::flags, ht_bucket< Value >::get_id(), trans_stats::inc_sent_reply_retrans(), trans_stats::inc_sent_request_retrans(), sip_trans::logger, sip_trans::msg, ht_bucket< Value >::remove(), sip_trans::reset_timer(), sip_trans::retr_len, sip_trans::retransmit(), sip_trans::state, timeout(), try_next_ip(), and sip_trans::type.
void _trans_layer::transport_error (sip_msg * msg)
Allows the transport layer to signal an asynchronous error while sending out a SIP message.
References process_rcvd_msg().
int _trans_layer::try_next_ip (trans_bucket * bucket, sip_trans * tr, bool use_new_trans) [protected]
If the destination has multiple IPs (SRV records), try the next destination IP.
Returns:
0 if the message has been re-sent. -1 if no additional destination has been found.
References sip_trans::clear_timer(), trsp_socket::copy_addr_to(), default_bl_ttl, sip_trans::flags, ht_bucket< Value >::get_id(), trsp_socket::get_if(), sip_trans::get_timer(), trans_stats::inc_sent_requests(), trsp_socket::is_reliable(), sip_trans::logger, sip_trans::msg, sip_msg::release(), sip_trans::reset_timer(), set_trsp_socket(), sip_trans::state, and sip_trans::targets.
Referenced by timer_expired(), and update_uac_reply().
int _trans_layer::update_uac_reply (trans_bucket * bucket, sip_trans * t, sip_msg * msg) [protected]
Implements the state changes for the UAC state machine
Returns:
-1 if errors
transaction state if successfull
References cancel(), sip_trans::clear_timer(), default_bl_ttl, sip_trans::flags, ht_bucket< Value >::get_id(), trsp_socket::is_reliable(), sip_trans::msg, ht_bucket< Value >::remove(), sip_trans::reset_all_timers(), sip_trans::reset_timer(), sip_trans::retransmit(), send_non_200_ack(), sip_trans::state, sip_trans::to_tag, and try_next_ip().
Referenced by process_rcvd_msg().
int _trans_layer::update_uas_request (trans_bucket * bucket, sip_trans * t, sip_msg * msg) [protected]
Implements the state changes for the UAS state machine
References sip_trans::clear_timer(), ht_bucket< Value >::get_id(), trsp_socket::is_reliable(), ht_bucket< Value >::remove(), sip_trans::reset_timer(), and sip_trans::state.
Referenced by process_rcvd_msg().
Field Documentation
bool _trans_layer::accept_fr_without_totag = false [static]
Config option: if true, final replies without a to-tag will be accepted for requests which do not create a dialog.
unsigned int _trans_layer::default_bl_ttl = DEFAULT_BL_TTL [static]
Config option: default blacklist time-to-live
Referenced by send_request(), timer_expired(), try_next_ip(), and update_uac_reply().
The documentation for this class was generated from the following files:
trans_layer.h
trans_layer.cpp