SEMS: MyCCDialog Class Reference
MyCCDialog Class Reference
Public Member Functions
MyCCDialog (AmDynInvoke *cc_acc)
void onSessionStart ()
void onDtmf (int event, int duration)
void process (AmEvent *ev)
void onBye (const AmSipRequest &req)
Protected Member Functions
bool onOtherReply (const AmSipReply &reply)
void onOtherBye (const AmSipRequest &req)
Member Function Documentation
void MyCCDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmB2BCallerSession.
References AmSession::setStopped(), and AmB2BCallerSession::terminateOtherLeg().
void MyCCDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References AmArg::get(), and int2str().
void MyCCDialog::onOtherBye (const AmSipRequest & req) [protected, virtual]
handle BYE on other leg
Reimplemented from AmB2BSession.
bool MyCCDialog::onOtherReply (const AmSipReply & reply) [protected, virtual]
Reply received from other leg has been replied
Returns:
true if reply was processed (should be absorbed)
false if reply was not processed
Reimplemented from AmB2BSession.
References AmMediaProcessor::removeSession(), and AmSession::setTimer().
void MyCCDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
void MyCCDialog::process (AmEvent * event) [virtual]
See also:
AmEventQueue
Reimplemented from AmB2BSession.
References AmArg::get(), AmB2BCallerSession::terminateLeg(), and AmB2BCallerSession::terminateOtherLeg().
The documentation for this class was generated from the following files:
MyCC.h
MyCC.cpp