SEMS: SBCCallLeg Class Reference
SBCCallLeg Class Reference
Public Member Functions
SBCCallLeg (const SBCCallProfile &call_profile, AmSipDialog *dlg=NULL, AmSipSubscription *p_subs=NULL)
SBCCallLeg (SBCCallLeg *caller, AmSipDialog *dlg=NULL, AmSipSubscription *p_subs=NULL)
SBCCallLeg (AmSipDialog *dlg=NULL, AmSipSubscription *p_subs=NULL)
void process (AmEvent *ev)
void onInvite (const AmSipRequest &req)
void onDtmf (int event, int duration)
virtual void onStart ()
virtual void onBeforeDestroy ()
UACAuthCred * getCredentials ()
void setAuthHandler (AmSessionEventHandler *h)
void setAuthDI (AmDynInvoke *di_inst)
bool initCCExtModules (const CCInterfaceListT &cc_module_list, const vector< AmDynInvoke * > &cc_module_di)
bool initPendingCCExtModules ()
void addPendingCCExtModule (const string &cc_name, const string &cc_module, const map< string, string > &cc_values)
void saveCallTimer (int timer, double timeout)
void clearCallTimer (int timer)
void clearCallTimers ()
void setLocalParty (const string &party, const string &uri)
void setRemoteParty (const string &party, const string &uri)
SBCCallProfile & getCallProfile ()
CallStatus getCallStatus ()
void setRTPMeasurements (const list< atomic_int * > &rtp_meas)
const RateLimit * getRTPRateLimit ()
void setRTPRateLimit (RateLimit *rl)
AmB2BMedia * getMediaSession ()
virtual void updateLocalSdp (AmSdp &sdp)
void changeRtpMode (RTPRelayMode new_mode)
bool reinvite (const AmSdp &sdp, unsigned &request_cseq)
int relayEvent (AmEvent *ev)
void onSipRequest (const AmSipRequest &req)
bool isALeg ()
int startTimer (double timeout)
virtual void setMediaSession (AmB2BMedia *new_session)
virtual void computeRelayMask (const SdpMedia &m, bool &enable, PayloadMask &mask)
Protected Member Functions
void setOtherId (const AmSipReply &reply)
void setOtherId (const string &n_other_id)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmSipDialog::Status old_dlg_status)
void onSendRequest (AmSipRequest &req, int &flags)
virtual void onInitialReply (B2BSipReplyEvent *e)
void onRemoteDisappeared (const AmSipReply &reply)
void onBye (const AmSipRequest &req)
void onOtherBye (const AmSipRequest &req)
void onControlCmd (string &cmd, AmArg &params)
virtual bool startCallTimers ()
virtual void stopCallTimers ()
const map< int, double > getCallTimers ()
void createCalleeSession ()
bool getCCInterfaces ()
vector< AmDynInvoke * > & getCCModules ()
virtual void createHoldRequest (AmSdp &sdp)
virtual void alterHoldRequest (AmSdp &sdp)
virtual void holdRequested ()
virtual void holdAccepted ()
virtual void holdRejected ()
virtual void resumeRequested ()
virtual void resumeAccepted ()
virtual void resumeRejected ()
int applySSTCfg (AmConfigReader &sst_cfg, const AmSipRequest *p_req)
bool openLogger (const std::string &path)
msg_logger * getLogger ()
virtual double get491RetryTime ()
Protected Attributes
bool cc_started
struct timeval call_start_ts
struct timeval call_connect_ts
struct timeval call_end_ts
Member Function Documentation
void SBCCallLeg::alterHoldRequest (AmSdp & sdp) [protected, virtual]
called to alter B2B hold request (i.e. the request from other peer)
Reimplemented from CallLeg.
void SBCCallLeg::changeRtpMode (RTPRelayMode new_mode) [inline]
change RTP mode (and AmB2BMedia if needed) but do not send reINVITE
Changes the mode for all peer legs as well.
WARNING: really unsafe because possibly makes the object state inconsistent with sent SIP messages (sent/received SDPs).
WARNING: might require several events exchanged between call legs, the AmB2BMedia will be valid after them!
TODO: add parameter to trigger reINVITE
Reimplemented from CallLeg.
void SBCCallLeg::clearCallTimer (int timer)
clear saved call timer, only effective before call is connected
Referenced by process().
void SBCCallLeg::clearCallTimers ()
clear all saved call timer, only effective before call is connected
bool SBCCallLeg::getCCInterfaces () [protected]
initialize call control module interfaces
Returns:
sucess or not
Referenced by initPendingCCExtModules(), and onInvite().
bool SBCCallLeg::initCCExtModules (const CCInterfaceListT & cc_module_list, const vector< AmDynInvoke * > & cc_module_di)
initialize modules from
cc_module_list with DI interface instances from
cc_module_di add sucessfull ext-API call control instances to cc_ext
Returns:
true on success (all modules properly initialized)
References ExtendedCCInterface::init(), and initPendingCCExtModules().
Referenced by initPendingCCExtModules(), and onInvite().
bool SBCCallLeg::initPendingCCExtModules ()
init pending modules until queue is empty
References getCCInterfaces(), and initCCExtModules().
Referenced by initCCExtModules(), and onInvite().
void SBCCallLeg::onBeforeDestroy () [virtual]
called in the session thread before the session is destroyed, i.e. after the main event loop has finished
Reimplemented from AmSession.
void SBCCallLeg::onBye (const AmSipRequest & req) [protected, virtual]
onBye is called whenever a BYE request is received.
Reimplemented from CallLeg.
References AmSession::getLocalTag().
void SBCCallLeg::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References AmB2BSession::getRtpRelayMode(), and AmB2BMedia::sendDtmf().
void SBCCallLeg::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from CallLeg.
References AmB2BSession::est_invite_cseq, getCCInterfaces(), initCCExtModules(), initPendingCCExtModules(), AmUriParser::parse_uri(), AmBasicSipDialog::reply(), SBCCallProfile::retarget(), AmSession::setStopped(), and AmB2BSession::subs.
void SBCCallLeg::onOtherBye (const AmSipRequest & req) [protected, virtual]
handle BYE on other leg
Reimplemented from CallLeg.
References AmSession::getLocalTag().
void SBCCallLeg::onRemoteDisappeared (const AmSipReply &) [protected, virtual]
remote side is unreachable - 408/481 reply received
Reimplemented from CallLeg.
void SBCCallLeg::onSendRequest (AmSipRequest & req, int & flags) [protected, virtual]
Hook called before a request is sent
Reimplemented from AmSession.
void SBCCallLeg::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmSipDialog::Status old_dlg_status) [protected, virtual]
Entry point for SIP Replies
Reimplemented from CallLeg.
References AmMimeBody::getCTStr(), AmB2BSession::relayed_req, and AmB2BSession::updateUACTransCSeq().
void SBCCallLeg::onSipRequest (const AmSipRequest & req) [virtual]
Entry point for SIP Requests
Reimplemented from CallLeg.
References AmBasicSipDialog::reply(), and AmB2BSession::sip_relay_only.
void SBCCallLeg::onStart () [virtual]
onStart will be called before everything else.
Reimplemented from AmSession.
void SBCCallLeg::process (AmEvent * event) [virtual]
See also:
AmEventQueue
Reimplemented from AmB2BSession.
References clearCallTimer(), AmArg::get(), AmSession::removeTimer(), saveCallTimer(), AmSession::setTimer(), and CallLeg::stopCall().
int SBCCallLeg::relayEvent (AmEvent * ev) [virtual]
Relay one event to the other side.
Returns:
0 on success
Reimplemented from AmB2BSession.
References AmMimeBody::getCTStr().
void SBCCallLeg::saveCallTimer (int timer, double timeout)
save call timer; only effective before call is connected
Referenced by process().
bool SBCCallLeg::startCallTimers () [protected, virtual]
Returns:
whether successful
References AmSession::setTimer().
void SBCCallLeg::updateLocalSdp (AmSdp & sdp) [virtual]
Called when SDP relayed from other leg should be sent to the remote party. Default implementation updates connection address and ports.
Reimplemented from CallLeg.
Field Documentation
bool SBCCallLeg::cc_started [protected]
set to true once CCStart passed to call CCEnd implicitly (from onStop) only when CCStart was called
The documentation for this class was generated from the following files:
SBCCallLeg.h
SBCCallLeg.cpp