SEMS: AmConferenceChannel Class Reference
AmConferenceChannel Class Reference
one channel of a conference
#include <AmConferenceChannel.h>
Public Member Functions
AmConferenceChannel (AmConferenceStatus *status, int channel_id, string channel_tag, bool own_channel)
string getConfID ()
Protected Member Functions
int read (unsigned int user_ts, unsigned int size)
int write (unsigned int user_ts, unsigned int size)
int get (unsigned long long system_ts, unsigned char *buffer, int output_sample_rate, unsigned int nb_samples)
int put (unsigned long long system_ts, unsigned char *buffer, int input_sample_rate, unsigned int size)
Detailed Description
one channel of a conference
A ConferenceChannel is one channel, i.e. to/from one participant, in a conference.
Member Function Documentation
int AmConferenceChannel::get (unsigned long long system_ts, unsigned char * buffer, int output_sample_rate, unsigned int nb_samples) [protected, virtual]
Get some samples from input stream.
Warning:
For packet based payloads / file formats, use:
           nb_sample = input buffer size / sample size of the reference format
whereby the format with/from which the codec works is the reference one.
Returns:
# bytes read, else -1 if error (0 is OK)
Reimplemented from AmAudio.
References int2str(), AmAudio::resampleOutput(), and async_file::write().
Referenced by ConferenceDialog::onBye(), ConferenceDialog::onSipReply(), and ConferenceDialog::process().
int AmConferenceChannel::put (unsigned long long system_ts, unsigned char * buffer, int input_sample_rate, unsigned int size) [protected, virtual]
Put some samples to the output stream.
Warning:
For packet based payloads / file formats, use:
           nb_sample = input buffer size / sample size of the reference format
whereby the format with/from which the codec works is the reference one.
Returns:
# bytes written, else -1 if error (0 is OK)
Reimplemented from AmAudio.
References int2str(), AmAudio::resampleInput(), and AmAudio::samples.
int AmConferenceChannel::read (unsigned int user_ts, unsigned int size) [inline, protected, virtual]
Gets 'size' bytes directly from stream (Read,Pull).
Implements AmAudio.
int AmConferenceChannel::write (unsigned int user_ts, unsigned int size) [inline, protected, virtual]
Puts 'size' bytes directly from stream (Write,Push).
Implements AmAudio.
The documentation for this class was generated from the following files:
AmConferenceChannel.h
AmConferenceChannel.cpp