SEMS: AnnounceAuthFactory Class Reference
AnnounceAuthFactory Class Reference
Public Member Functions
AnnounceAuthFactory (const string &_app_name)
int onLoad ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
Static Public Attributes
static string AnnouncePath
static string AnnounceFile
Member Function Documentation
AmSession * AnnounceAuthFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
References AmUACAuth::enable(), and file_exists().
int AnnounceAuthFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AmSessionFactory::configureModule(), file_exists(), AmConfig::ModConfigPath, and AmThread::start().
The documentation for this class was generated from the following files:
AnnounceAuth.h
AnnounceAuth.cpp