SEMS: AnnounceAuthDialog Class Reference
AnnounceAuthDialog Class Reference
Public Member Functions
AnnounceAuthDialog (const string &filename, const string &auth_realm, const string &auth_user, const string &auth_pwd)
void onSessionStart ()
void startSession ()
void onBye (const AmSipRequest &req)
void onDtmf (int event, int duration_msec)
void process (AmEvent *event)
UACAuthCred * getCredentials ()
Member Function Documentation
void AnnounceAuthDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::setStopped().
void AnnounceAuthDialog::onDtmf (int event, int duration) [inline, virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
void AnnounceAuthDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
void AnnounceAuthDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmSipDialog::bye(), and AmSession::setStopped().
The documentation for this class was generated from the following files:
AnnounceAuth.h
AnnounceAuth.cpp