SEMS: DSMFactory Class Reference
DSMFactory Class Reference
Factory for announcement sessions.
#include <DSM.h>
Public Member Functions
int onLoad ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
AmSession * onInvite (const AmSipRequest &req, const string &app_name, AmArg &session_params)
AmDynInvoke * getInstance ()
void invoke (const string &method, const AmArg &args, AmArg &ret)
void postEvent (AmEvent *e)
bool createSystemDSM (const string &config_name, const string &start_diag, bool reload, string &status)
bool addScriptDiagsToEngine (const string &config_set, DSMStateEngine *engine, map< string, string > &config_vars, bool &SetParamVariables)
Static Public Member Functions
static DSMFactory * instance ()
Detailed Description
Factory for announcement sessions.
Member Function Documentation
bool DSMFactory::addScriptDiagsToEngine (const string & config_set, DSMStateEngine * engine, map< string, string > & config_vars, bool & SetParamVariables)
add script diags from config set to DSM engine
Returns:
true on success (config set found)
AmSession * DSMFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
AmSession * DSMFactory::onInvite (const AmSipRequest & req, const string & app_name, AmArg & session_params) [virtual]
Creates a dialog state on new UAC request.
Parameters:
session_params parameters passed to the new session by the caller.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Reimplemented from AmSessionFactory.
References AmUACAuth::enable(), AmArg::get(), and AmUACAuth::unpackCredentials().
int DSMFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AmSessionFactory::configureModule(), explode(), AmPlugIn::getFactory4Seh(), AmConfig::ModConfigPath, and AmPlugIn::registerFactory4App().
The documentation for this class was generated from the following files:
DSM.h
DSM.cpp