SEMS: SimpleRelayDialog Class Reference
SimpleRelayDialog Class Reference
Data Structures
struct CCModuleInfo
Public Member Functions
SimpleRelayDialog (SBCCallProfile &profile, vector< AmDynInvoke * > &cc_modules, atomic_ref_cnt *parent_obj=NULL)
SimpleRelayDialog (atomic_ref_cnt *parent_obj=NULL)
void setParent (atomic_ref_cnt *p_obj)
void setOtherDlg (const string &dlg)
const string & getOtherDlg ()
void setKeepVias (bool kv)
bool getKeepVias ()
vector< FilterEntry > & getHeaderFilter ()
const vector< FilterEntry > & getHeaderFilter () const
string & getAppendHeaders ()
const string & getAppendHeaders () const
ReplyTranslationMap & getReplyTranslations ()
const ReplyTranslationMap & getReplyTranslations () const
virtual int initUAC (const AmSipRequest &req, const SBCCallProfile &cp)
virtual int initUAS (const AmSipRequest &req, const SBCCallProfile &cp)
virtual bool terminated ()
void onSendRequest (AmSipRequest &req, int &flags)
void onSipRequest (const AmSipRequest &req)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
void onRequestSent (const AmSipRequest &req)
void onReplySent (const AmSipRequest &req, const AmSipReply &reply)
void onRemoteDisappeared (const AmSipReply &reply)
void onLocalTerminate (const AmSipReply &reply)
void finalize ()
Protected Types
typedef map< unsigned int,
unsigned int > RelayMap
Protected Member Functions
void process (AmEvent *ev)
bool processingCycle ()
void initCCModules (SBCCallProfile &profile, vector< AmDynInvoke * > &cc_modules)
virtual void onB2BRequest (const AmSipRequest &req)
virtual void onB2BReply (const AmSipReply &reply)
virtual void terminate ()
Protected Attributes
RelayMap relayed_reqs
Member Function Documentation
void SimpleRelayDialog::finalize () [virtual]
Terminates pending UAS/UAC transactions
Reimplemented from AmBasicSipDialog.
void SimpleRelayDialog::initCCModules (SBCCallProfile & profile, vector< AmDynInvoke * > & cc_modules) [protected]
SimpleRelayDialog
References ExtendedCCInterface::init().
void SimpleRelayDialog::onLocalTerminate (const AmSipReply & reply) [virtual]
Hook called when the all dialog usages should be terminated before a local reply is sent.
Reimplemented from AmBasicSipEventHandler.
References terminate().
void SimpleRelayDialog::onRemoteDisappeared (const AmSipReply & reply) [virtual]
Hook called when the all dialog usages should be terminated after a reply received from the far end, or a locally generated timeout (408).
Reimplemented from AmBasicSipEventHandler.
References terminate().
void SimpleRelayDialog::onReplySent (const AmSipRequest & req, const AmSipReply & reply) [virtual]
Hook called after a reply has been sent
Reimplemented from AmBasicSipEventHandler.
Reimplemented in SubscriptionDialog.
void SimpleRelayDialog::onRequestSent (const AmSipRequest & req) [virtual]
Hook called after a request has been sent
Reimplemented from AmBasicSipEventHandler.
Reimplemented in SubscriptionDialog.
void SimpleRelayDialog::onSendRequest (AmSipRequest & req, int & flags) [virtual]
Hook called before a request is sent
Reimplemented from AmBasicSipEventHandler.
void SimpleRelayDialog::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_status) [virtual]
Hook called when a reply has been received
Reimplemented from AmBasicSipEventHandler.
Reimplemented in SubscriptionDialog, and RegisterDialog.
void SimpleRelayDialog::onSipRequest (const AmSipRequest & req) [virtual]
Hook called when a request has been received
Reimplemented from AmBasicSipEventHandler.
Reimplemented in SubscriptionDialog.
References AmBasicSipDialog::reply().
virtual void SimpleRelayDialog::terminate () [inline, protected, virtual]
correctly terminate the dialog; MUST be redefined if "terminated" method is redefined
Reimplemented in SubscriptionDialog.
Referenced by onLocalTerminate(), and onRemoteDisappeared().
The documentation for this class was generated from the following files:
SBCSimpleRelay.h
SBCSimpleRelay.cpp