SEMS: trans_stats Class Reference
trans_stats Class Reference
Public Member Functions
void inc_sent_requests ()
void inc_sent_replies ()
void inc_received_requests ()
void inc_received_replies ()
void inc_sent_request_retrans ()
void inc_sent_reply_retrans ()
unsigned get_sent_requests () const
unsigned get_sent_replies () const
unsigned get_received_requests () const
unsigned get_received_replies () const
unsigned get_sent_request_retrans () const
unsigned get_sent_reply_retrans () const
Member Function Documentation
void trans_stats::inc_received_replies () [inline]
increment number of received replies
Referenced by _trans_layer::process_rcvd_msg().
void trans_stats::inc_received_requests () [inline]
increment number of received requests
Referenced by _trans_layer::process_rcvd_msg().
void trans_stats::inc_sent_replies () [inline]
increment number of sent replies
Referenced by _trans_layer::send_reply(), and _trans_layer::send_sl_reply().
void trans_stats::inc_sent_reply_retrans () [inline]
increment number of sent reply retransmissions
Referenced by _trans_layer::timer_expired().
void trans_stats::inc_sent_request_retrans () [inline]
increment number of sent request retransmissions
Referenced by _trans_layer::timer_expired().
void trans_stats::inc_sent_requests () [inline]
increment number of sent requests
Referenced by _trans_layer::cancel(), _trans_layer::send_non_200_ack(), _trans_layer::send_request(), and _trans_layer::try_next_ip().
The documentation for this class was generated from the following file:
trans_layer.h