SEMS: AmAudioFileFormat Class Reference
AmAudioFileFormat Class Reference
AmAudioFormat for file
#include <AmAudioFile.h>
Public Member Functions
AmAudioFileFormat (const string &name, int subtype=-1)
AmAudioFileFormat (const string &name, int subtype, amci_subtype_t *p_subtype)
virtual amci_codec_t * getCodec ()
string getName ()
int getSubtypeId ()
virtual amci_subtype_t * getSubtype ()
void setSubtypeId (int subtype_id)
Protected Member Functions
int getCodecId ()
Detailed Description
AmAudioFormat for file
Constructor & Destructor Documentation
AmAudioFileFormat::AmAudioFileFormat (const string & name, int subtype = -1)
Constructor for file based formats. All information are taken from the plug-in description.
Parameters:
name The file format name (ex. "Wav").
subtype Subtype for the file format (see amci.h).
References AmAudioFormat::channels, amci_subtype_t::channels, AmAudioFormat::codec, getCodec(), getSubtype(), AmAudioFormat::rate, amci_subtype_t::sample_rate, and amci_subtype_t::type.
AmAudioFileFormat::AmAudioFileFormat (const string & name, int subtype, amci_subtype_t * p_subtype)
format with rate & channels, not taken from subtype
References AmAudioFormat::channels, amci_subtype_t::channels, AmAudioFormat::codec, getCodec(), AmAudioFormat::rate, and amci_subtype_t::sample_rate.
Member Function Documentation
amci_codec_t * AmAudioFileFormat::getCodec () [virtual]
Returns:
The format's codec pointer.
Reimplemented from AmAudioFormat.
References AmAudioFormat::codec_id, amci_subtype_t::codec_id, and AmAudioFormat::destroyCodec().
Referenced by AmAudioFileFormat().
string AmAudioFileFormat::getName () [inline]
Returns:
Format name.
amci_subtype_t * AmAudioFileFormat::getSubtype () [virtual]
Returns:
Subtype pointer.
Reimplemented in AmPrecodedFileFormat.
References AmPlugIn::fileFormat(), amci_inoutfmt_t::name, AmPlugIn::subtype(), and amci_subtype_t::type.
Referenced by AmAudioFileFormat().
int AmAudioFileFormat::getSubtypeId () [inline]
Returns:
Format subtype.
Referenced by AmAudioFile::fpopen_int(), and AmAudioFile::on_close().
The documentation for this class was generated from the following files:
AmAudioFile.h
AmAudioFile.cpp