SEMS: AmBasicSipDialog Class Reference
AmBasicSipDialog Class Reference
Public Types
enum Status {
Disconnected = 0, Trying, Proceeding, Cancelling,
Early, Connected, Disconnecting, __max_Status
}
Public Member Functions
AmBasicSipDialog (AmBasicSipEventHandler *h=NULL)
void setEventhandler (AmBasicSipEventHandler *h)
AmSipRequest * getUACTrans (unsigned int t_cseq)
AmSipRequest * getUASTrans (unsigned int t_cseq)
string getUACTransMethod (unsigned int t_cseq)
bool getUACTransPending ()
Status getStatus () const
virtual void setStatus (Status new_status)
virtual const char * getStatusStr ()
unsigned int getUsages ()
void incUsages ()
void decUsages ()
const string & getCallid () const
virtual void setCallid (const string &n_callid)
const string & getLocalTag () const
virtual void setLocalTag (const string &n_tag)
const string & getRemoteTag () const
virtual void setRemoteTag (const string &n_tag)
const string & get1stBranch () const
virtual void set1stBranch (const string &n_branch)
const string & getExtLocalTag () const
virtual void setExtLocalTag (const string &new_ext_tag)
const string & getContactParams () const
virtual void setContactParams (const string &new_contact_params)
const string & getUser () const
virtual void setUser (const string &new_user)
const string & getDomain () const
virtual void setDomain (const string &new_domain)
const string & getLocalUri () const
virtual void setLocalUri (const string &new_local_uri)
const string & getRemoteUri () const
virtual void setRemoteUri (const string &new_remote_uri)
const string & getLocalParty () const
virtual void setLocalParty (const string &new_local_party)
const string & getRemoteParty () const
virtual void setRemoteParty (const string &new_remote_party)
const string & getRemoteUA () const
virtual void setRemoteUA (const string &new_remote_ua)
const string & getRouteSet () const
virtual void setRouteSet (const string &new_rs)
const string & getNextHop () const
virtual void setNextHop (const string &new_nh)
bool getNextHop1stReq () const
virtual void setNextHop1stReq (bool nh_1st_req)
bool getPatchRURINextHop () const
virtual void setPatchRURINextHop (bool patch_nh)
bool getNextHopFixed () const
virtual void setNextHopFixed (bool nh_fixed)
string getContactHdr ()
string getContactUri ()
string getRoute ()
virtual void setOutboundInterface (int interface_id)
int getOutboundIf ()
void resetOutboundIf ()
virtual void initFromLocalRequest (const AmSipRequest &req)
virtual void onRxRequest (const AmSipRequest &req)
virtual void onRxReply (const AmSipReply &reply)
void updateDialogTarget (const AmSipReply &reply)
virtual int reply (const AmSipRequest &req, unsigned int code, const string &reason, const AmMimeBody *body=NULL, const string &hdrs="", int flags=0)
virtual int sendRequest (const string &method, const AmMimeBody *body=NULL, const string &hdrs="", int flags=0)
virtual void finalize ()
virtual void dropTransactions ()
void dump ()
void setMsgLogger (msg_logger *logger)
msg_logger * getMsgLogger ()
Static Public Member Functions
static const char * getStatusStr (Status st)
static int reply_error (const AmSipRequest &req, unsigned int code, const string &reason, const string &hdrs="", msg_logger *logger=NULL)
Data Fields
string outbound_proxy
bool force_outbound_proxy
bool nat_handling
unsigned int cseq
bool r_cseq_i
unsigned int r_cseq
Protected Member Functions
virtual int onTxReply (const AmSipRequest &req, AmSipReply &reply, int &flags)
virtual int onTxRequest (AmSipRequest &req, int &flags)
virtual void onReplyTxed (const AmSipRequest &req, const AmSipReply &reply)
virtual void onRequestTxed (const AmSipRequest &req)
virtual bool onRxReqSanity (const AmSipRequest &req)
virtual bool onRxReqStatus (const AmSipRequest &req)
virtual bool onRxReplySanity (const AmSipReply &reply)
virtual bool onRxReplyStatus (const AmSipReply &reply)
virtual void termUasTrans ()
virtual void termUacTrans ()
Protected Attributes
Status status
string callid
string local_tag
string ext_local_tag
string remote_tag
string first_branch
string contact_params
string user
string domain
string local_uri
string remote_uri
string remote_party
string local_party
string remote_ua
string route
string next_hop
bool next_hop_1st_req
bool patch_ruri_next_hop
bool next_hop_fixed
int outbound_interface
TransMap uas_trans
TransMap uac_trans
unsigned int usages
AmBasicSipEventHandler * hdl
msg_logger * logger
Member Function Documentation
virtual void AmBasicSipDialog::finalize () [inline, virtual]
Terminates pending UAS/UAC transactions
Reimplemented in SimpleRelayDialog.
References termUacTrans(), and termUasTrans().
Referenced by AmSession::finalize().
string AmBasicSipDialog::getContactHdr ()
Compute the Contact-HF for the next request
References getContactUri().
Referenced by reply(), AmSipDialog::send_200_ack(), and sendRequest().
string AmBasicSipDialog::getContactUri ()
Compute the Contact URI for the next request
References getOutboundIf(), and int2str().
Referenced by getContactHdr(), and AmSIPRegistration::onSipReply().
msg_logger* AmBasicSipDialog::getMsgLogger () [inline]
Get message logger
References logger.
int AmBasicSipDialog::getOutboundIf ()
Compute, set and return the outbound interface based on remote_uri, next_hop_ip, outbound_proxy, route.
Computes, set and return the outbound interface based on remote_uri, next_hop_ip, outbound_proxy, route.
References setOutboundInterface().
Referenced by getContactUri().
string AmBasicSipDialog::getRoute ()
Compute the Route-HF for the next request
Referenced by AmSipDialog::send_200_ack(), and sendRequest().
Status AmBasicSipDialog::getStatus () const [inline]
Getter/Setter basic dialog status
Referenced by AmSipDialog::cancel(), AmSipDialog::info(), AmSipDialog::invite(), b2b_connectDialog::onB2ABEvent(), AmB2BSession::onB2BEvent(), b2b_connectDialog::onCancel(), DSMCall::onCancel(), b2b_connectDialog::onInvite(), DSMCall::onInvite(), RtmpSession::onInvite(), ConferenceDialog::onInvite(), AmSession::onNoAck(), AmSession::onNoPrack(), AmB2BSession::onRemoteDisappeared(), AmSipDialog::onSdpCompleted(), RtmpSession::onSipReply(), DSMCall::onSipReply(), WebConferenceDialog::onSipReply(), CallGenDialog::onSipReply(), ConferenceDialog::onSipReply(), AmB2ABCalleeSession::onSipReply(), AmSession::onSipReply(), ConferenceDialog::onSipRequest(), CallLeg::onSipRequest(), AmSipDialog::prack(), AmSession::processingCycle(), AmSipDialog::refer(), AmB2BSession::refresh(), AmSession::refresh(), AmSipDialog::reinvite(), AmSipDialog::transfer(), and AmSipDialog::update().
AmSipRequest * AmBasicSipDialog::getUACTrans (unsigned int t_cseq)
Returns:
UAC request coresponding to cseq or NULL
Referenced by getUACTransMethod().
string AmBasicSipDialog::getUACTransMethod (unsigned int t_cseq)
Returns:
the method of the corresponding uac request
References getUACTrans().
bool AmBasicSipDialog::getUACTransPending ()
Returns:
whether UAC transaction is pending
Referenced by AmSession::processingCycle().
AmSipRequest * AmBasicSipDialog::getUASTrans (unsigned int t_cseq)
Returns:
UAS request coresponding to cseq or NULL
void AmBasicSipDialog::initFromLocalRequest (const AmSipRequest & req) [virtual]
Set outbound_interface to specific value (-1 = default). Initialize dialog from locally originated UAC request
Update dialog status from UAC Request that we send.
void AmBasicSipDialog::onReplyTxed (const AmSipRequest & req, const AmSipReply & reply) [protected, virtual]
Executed for replies sent by a local UA, after the reply has been successfuly sent.
Error code list from RFC 5057: those error codes terminate the dialog
Note: 408, 480 should only terminate the usage according to RFC 5057.
Reimplemented in AmSipDialog.
References AmBasicSipEventHandler::onLocalTerminate(), and AmBasicSipEventHandler::onReplySent().
Referenced by reply().
void AmBasicSipDialog::onRequestTxed (const AmSipRequest & req) [protected, virtual]
Executed for requests sent by a local UA, after the request has been successfuly sent.
Reimplemented in AmSipDialog.
References AmBasicSipEventHandler::onRequestSent().
Referenced by sendRequest().
void AmBasicSipDialog::onRxReply (const AmSipReply & reply) [virtual]
Executed for replies received by the local UA.
References onRxReplySanity(), onRxReplyStatus(), AmBasicSipEventHandler::onSipReply(), and updateDialogTarget().
bool AmBasicSipDialog::onRxReplySanity (const AmSipReply & reply) [protected, virtual]
Basic sanity check on received replies
Returns:
true to continue processing, false otherwise
Reimplemented in AmSipDialog.
Referenced by onRxReply().
bool AmBasicSipDialog::onRxReplyStatus (const AmSipReply & reply) [protected, virtual]
Executed from onRxReply() to allow inherited classes to extend the basic behavior (deletes the transaction on final reply).
Returns:
true to continue processing, false otherwise
Error code list from RFC 5057: those error codes terminate the dialog
Note: 408, 480 should only terminate the usage according to RFC 5057.
Reimplemented in AmSipDialog.
References AmBasicSipEventHandler::onRemoteDisappeared().
Referenced by onRxReply().
bool AmBasicSipDialog::onRxReqSanity (const AmSipRequest & req) [protected, virtual]
Basic sanity check on received requests
Note: At this point in the processing, the request has not been inserted yet into the uas_trans container. Thus, reply_error() should be used instead of reply() method.
Returns:
true to continue processing, false otherwise
Reimplemented in AmSipDialog.
References AmConfig::IgnoreNotifyLowerCSeq, and reply_error().
Referenced by AmSipDialog::onRxReqSanity(), and onRxRequest().
virtual bool AmBasicSipDialog::onRxReqStatus (const AmSipRequest & req) [inline, protected, virtual]
Executed from onRxRequest() to allow inherited classes to extend the basic behavior.
Returns:
true to continue processing, false otherwise
Reimplemented in AmSipDialog.
Referenced by onRxRequest().
void AmBasicSipDialog::onRxRequest (const AmSipRequest & req) [virtual]
Executed for requests received by the local UA.
References int2str(), logger, onRxReqSanity(), onRxReqStatus(), AmBasicSipEventHandler::onSipRequest(), and setOutboundInterface().
int AmBasicSipDialog::onTxReply (const AmSipRequest & req, AmSipReply & reply, int & flags) [protected, virtual]
Executed for replies sent by a local UA, right before the reply is passed to the transaction layer.
Reimplemented in AmSipDialog.
References AmBasicSipEventHandler::onSendReply().
Referenced by reply().
int AmBasicSipDialog::onTxRequest (AmSipRequest & req, int & flags) [protected, virtual]
Executed for requests sent by a local UA, right before the request is passed to the transaction layer.
Reimplemented in AmSipDialog.
References AmBasicSipEventHandler::onSendRequest().
Referenced by AmSipDialog::onTxRequest(), and sendRequest().
int AmBasicSipDialog::reply (const AmSipRequest & req, unsigned int code, const string & reason, const AmMimeBody * body = NULL, const string & hdrs = "", int flags = 0) [virtual]
Returns:
0 on success
References getContactHdr(), logger, onReplyTxed(), onTxReply(), and AmConfig::Signature.
Referenced by AmSipDialog::bye(), b2b_connectDialog::onB2ABEvent(), VoiceboxDialog::onBye(), AnswerMachineDialog::onBye(), b2b_connectDialog::onCancel(), EarlyAnnounceDialog::onCancel(), b2b_connectDialog::onInvite(), C2DCallerDialog::onInvite(), EarlyAnnounceDialog::onInvite(), RtmpSession::onInvite(), SBCCallLeg::onInvite(), AmSession::onInvite(), AmSession::onNoPrack(), AmSipSubscriptionDialog::onNotify(), AmOfferAnswer::onRequestIn(), AmSipDialog::onRxReqStatus(), AnnounceTransferDialog::onSipRequest(), SimpleRelayDialog::onSipRequest(), SBCCallLeg::onSipRequest(), AmB2BSession::onSipRequest(), CallLeg::onSipRequest(), AmSession::onSipRequest(), RtmpSession::process(), EarlyAnnounceDialog::process(), AmB2BSession::relaySip(), reply_error(), and termUasTrans().
int AmBasicSipDialog::reply_error (const AmSipRequest & req, unsigned int code, const string & reason, const string & hdrs = "", msg_logger * logger = NULL) [static]
This method should only be used to send responses to requests which are not referenced by any dialog.
WARNING: If the request has already been referenced (see uas_trans), this method cannot mark the request as replied, thus leaving it in the pending state forever.
References AmSession::getNewId(), reply(), and AmConfig::Signature.
Referenced by AmSessionContainer::createSession(), RtmpFactory::onInvite(), SBCFactory::onOoDRequest(), AmSessionFactory::onOoDRequest(), AmSipDialog::onRxReqSanity(), onRxReqSanity(), _RegisterCache::saveSingleContact(), AmSessionContainer::startSessionUAS(), and _RegisterCache::throttleRegister().
void AmBasicSipDialog::resetOutboundIf ()
Reset outbound_interface to default value (-1).
References setOutboundInterface().
int AmBasicSipDialog::sendRequest (const string & method, const AmMimeBody * body = NULL, const string & hdrs = "", int flags = 0) [virtual]
Returns:
0 on success
References getContactHdr(), getRoute(), logger, onRequestTxed(), onTxRequest(), and AmConfig::Signature.
Referenced by AmSipDialog::bye(), AmSipDialog::info(), AmSipDialog::invite(), AmB2BCalleeSession::onB2BEvent(), AmSipDialog::onRxReplyStatus(), ConferenceDialog::onSipRequest(), AmSipDialog::prack(), AmSipDialog::refer(), AmSipDialog::reinvite(), AmB2BSession::relaySip(), AmSipDialog::transfer(), and AmSipDialog::update().
void AmBasicSipDialog::setMsgLogger (msg_logger * logger)
Enable or disable message logger
References logger.
void AmBasicSipDialog::setOutboundInterface (int interface_id) [virtual]
Set outbound_interface to specific value (-1 = default).
Referenced by getOutboundIf(), onRxRequest(), resetOutboundIf(), and SBCCallProfile::retarget().
void AmBasicSipDialog::termUacTrans () [protected, virtual]
Terminate pending UAC transactions
References trans_ticket::lock_bucket(), trans_ticket::remove_trans(), and trans_ticket::unlock_bucket().
Referenced by finalize().
void AmBasicSipDialog::termUasTrans () [protected, virtual]
Terminate pending UAS transactions
References reply().
Referenced by finalize().
void AmBasicSipDialog::updateDialogTarget (const AmSipReply & reply)
Updates remote_uri if necessary.
Note: this method is offered for inherited classes implementing dialog functionnalities. It is not used by the basic class.
References int2str().
Referenced by onRxReply().
Field Documentation
msg_logger* AmBasicSipDialog::logger [protected]
Message logger
Referenced by getMsgLogger(), onRxRequest(), reply(), AmSipDialog::send_200_ack(), sendRequest(), and setMsgLogger().
unsigned int AmBasicSipDialog::usages [protected]
Dialog usages in the sense of RFC 5057
The documentation for this class was generated from the following files:
AmBasicSipDialog.h
AmBasicSipDialog.cpp