SEMS: SimpleConferenceDialog Class Reference
SimpleConferenceDialog Class Reference
Public Member Functions
void process (AmEvent *ev)
void onSessionStart ()
void onDtmf (int event, int duration)
void onBye (const AmSipRequest &req)
Member Function Documentation
void SimpleConferenceDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmPlaylist::close(), and AmSession::setStopped().
void SimpleConferenceDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
void SimpleConferenceDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmSession::getLocalTag(), and AmSession::setCallgroup().
void SimpleConferenceDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
The documentation for this class was generated from the following files:
SimpleConference.h
SimpleConference.cpp