SEMS: AmOfferAnswer Class Reference
AmOfferAnswer Class Reference
Public Types
enum OAState {
OA_None = 0, OA_OfferRecved, OA_OfferSent, OA_Completed,
__max_OA
}
Public Member Functions
AmOfferAnswer (AmSipDialog *dlg)
OAState getState ()
void setState (OAState n_st)
const AmSdp & getLocalSdp ()
const AmSdp & getRemoteSdp ()
void clear ()
void clearTransitionalState ()
int onRequestIn (const AmSipRequest &req)
int onReplyIn (const AmSipReply &reply)
int onRequestOut (AmSipRequest &req)
int onReplyOut (AmSipReply &reply)
int onRequestSent (const AmSipRequest &req)
int onReplySent (const AmSipReply &reply)
void onNoAck (unsigned int ack_cseq)
Constructor & Destructor Documentation
AmOfferAnswer::AmOfferAnswer (AmSipDialog * dlg)
Constructor
Member Function Documentation
AmOfferAnswer::OAState AmOfferAnswer::getState ()
Accessors
Referenced by AmSipDialog::onRxReqSanity().
int AmOfferAnswer::onRequestIn (const AmSipRequest & req)
Event handlers
References AmSipDialog::bye(), AmMimeBody::empty(), AmMimeBody::hasContentType(), and AmBasicSipDialog::reply().
Referenced by AmSipDialog::onRxReqStatus().
The documentation for this class was generated from the following files:
AmOfferAnswer.h
AmOfferAnswer.cpp