SEMS: AmRtpAudio Class Reference
AmRtpAudio Class Reference
binds together a AmRtpStream and an AmAudio for a session
#include <AmRtpAudio.h>
Public Member Functions
AmRtpAudio (AmSession *_s, int _if)
unsigned int getFrameSize ()
bool checkInterval (unsigned long long ts)
bool sendIntReached ()
bool sendIntReached (unsigned long long ts)
int setCurrentPayload (int payload)
int getCurrentPayload ()
int receive (unsigned long long system_ts)
int get (unsigned long long system_ts, unsigned char *buffer, int output_sample_rate, unsigned int nb_samples)
int put (unsigned long long system_ts, unsigned char *buffer, int input_sample_rate, unsigned int size)
unsigned int bytes2samples (unsigned int) const
void getSdpOffer (unsigned int index, SdpMedia &offer)
void getSdpAnswer (unsigned int index, const SdpMedia &offer, SdpMedia &answer)
int init (const AmSdp &local, const AmSdp &remote, bool force_symmetric_rtp=false)
void setPlayoutType (PlayoutType type)
void add_to_history (int16_t *buffer, unsigned int size)
unsigned int conceal_loss (unsigned int ts_diff, unsigned char *out_buffer)
Protected Member Functions
int read (unsigned int user_ts, unsigned int size)
int write (unsigned int user_ts, unsigned int size)
Detailed Description
binds together a AmRtpStream and an AmAudio for a session
Member Function Documentation
unsigned int AmRtpAudio::bytes2samples (unsigned int bytes) const
Convert the size from bytes to samples, depending on the format.
Reimplemented from AmAudio.
int AmRtpAudio::get (unsigned long long system_ts, unsigned char * buffer, int output_sample_rate, unsigned int nb_samples) [virtual]
Get some samples from input stream.
Warning:
For packet based payloads / file formats, use:
           nb_sample = input buffer size / sample size of the reference format
whereby the format with/from which the codec works is the reference one.
Returns:
# bytes read, else -1 if error (0 is OK)
Reimplemented from AmAudio.
References AmRtpStream::active, AmRtpStream::receiving, AmAudio::resampleOutput(), and AmAudio::scaleSystemTS().
Referenced by WebConferenceDialog::readStreams(), AmSession::readStreams(), and AudioStreamData::writeStream().
void AmRtpAudio::getSdpAnswer (unsigned int index, const SdpMedia & offer, SdpMedia & answer) [virtual]
Generate an answer for the given SDP media based on the stream capabilities.
Parameters:
index index of the SDP media within the SDP.
offer the remote offer.
answer the local answer to be filled/completed.
Reimplemented from AmRtpStream.
Referenced by AmSession::getSdpAnswer().
void AmRtpAudio::getSdpOffer (unsigned int index, SdpMedia & offer) [virtual]
Generate an SDP offer based on the stream capabilities.
Parameters:
index index of the SDP media within the SDP.
offer the local offer to be filled/completed.
Reimplemented from AmRtpStream.
Referenced by AmSession::getSdpOffer().
int AmRtpAudio::init (const AmSdp & local, const AmSdp & remote, bool force_passive_mode = false) [virtual]
Enables RTP stream.
Parameters:
local the SDP message generated by the local UA.
remote the SDP message generated by the remote UA.
Warning:
It is necessary to call getSdpOffer/getSdpAnswer prior to init(...)
so that the internal SDP media line index is set properly.
Reimplemented from AmRtpStream.
References AmAudio::fmt, AmRtpStream::init(), amci_codec_t::plc, and AmAudioRtpFormat::setCurrentPayload().
Referenced by AudioStreamData::initStream(), and AmSession::onSdpCompleted().
int AmRtpAudio::put (unsigned long long system_ts, unsigned char * buffer, int input_sample_rate, unsigned int size) [virtual]
Put some samples to the output stream.
Warning:
For packet based payloads / file formats, use:
           nb_sample = input buffer size / sample size of the reference format
whereby the format with/from which the codec works is the reference one.
Returns:
# bytes written, else -1 if error (0 is OK)
Reimplemented from AmAudio.
References AmAudio::encode(), AmAudio::fmt, AmAudioRtpFormat::getTSRate(), AmRtpStream::mute, and AmAudio::resampleInput().
Referenced by AudioStreamData::writeStream(), and AmSession::writeStreams().
int AmRtpAudio::read (unsigned int user_ts, unsigned int size) [inline, protected, virtual]
Gets 'size' bytes directly from stream (Read,Pull).
Implements AmAudio.
int AmRtpAudio::write (unsigned int user_ts, unsigned int size) [inline, protected, virtual]
Puts 'size' bytes directly from stream (Write,Push).
Implements AmAudio.
The documentation for this class was generated from the following files:
AmRtpAudio.h
AmRtpAudio.cpp