SEMS: SBCDSMInstance Class Reference
SBCDSMInstance Class Reference
#include <SBCDSMInstance.h>
Public Member Functions
SBCDSMInstance (SBCCallLeg *call, const VarMapT &values)
CCChainProcessing onInitialInvite (SBCCallLeg *call, InitialInviteHandlerParams &params)
void onStateChange (SBCCallLeg *call, const CallLeg::StatusChangeCause &cause)
CCChainProcessing onBLegRefused (SBCCallLeg *call, const AmSipReply &reply)
CCChainProcessing onInDialogRequest (SBCCallLeg *call, const AmSipRequest &req)
CCChainProcessing onInDialogReply (SBCCallLeg *call, const AmSipReply &reply)
CCChainProcessing onEvent (SBCCallLeg *call, AmEvent *event)
CCChainProcessing onDtmf (SBCCallLeg *call, int event, int duration)
CCChainProcessing putOnHold (SBCCallLeg *call)
CCChainProcessing resumeHeld (SBCCallLeg *call, bool send_reinvite)
CCChainProcessing createHoldRequest (SBCCallLeg *call, AmSdp &sdp)
CCChainProcessing handleHoldReply (SBCCallLeg *call, bool succeeded)
AmPlaylist * getPlaylist ()
bool init (SBCCallProfile &profile, SimpleRelayDialog *relay)
void initUAC (SBCCallProfile &profile, SimpleRelayDialog *relay, const AmSipRequest &req)
void initUAS (SBCCallProfile &profile, SimpleRelayDialog *relay, const AmSipRequest &req)
void finalize (SBCCallProfile &profile, SimpleRelayDialog *relay)
void onSipRequest (SBCCallProfile &profile, SimpleRelayDialog *relay, const AmSipRequest &req)
void onSipReply (SBCCallProfile &profile, SimpleRelayDialog *relay, const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
void onB2BRequest (SBCCallProfile &profile, SimpleRelayDialog *relay, const AmSipRequest &req)
void onB2BReply (SBCCallProfile &profile, SimpleRelayDialog *relay, const AmSipReply &reply)
void playPrompt (const string &name, bool loop=false, bool front=false)
void playFile (const string &name, bool loop, bool front=false)
void playSilence (unsigned int length, bool front=false)
void playRingtone (int length, int on, int off, int f, int f2, bool front)
void recordFile (const string &name)
unsigned int getRecordLength ()
unsigned int getRecordDataSize ()
void stopRecord ()
void setInOutPlaylist ()
void setInputPlaylist ()
void setOutputPlaylist ()
void addToPlaylist (AmPlaylistItem *item, bool front=false)
void flushPlaylist ()
void setPromptSet (const string &name)
void addSeparator (const string &name, bool front=false)
void connectMedia ()
void disconnectMedia ()
void mute ()
void unmute ()
void B2BconnectCallee (const string &remote_party, const string &remote_uri, bool relayed_invite=false)
void B2BterminateOtherLeg ()
void B2BaddReceivedRequest (const AmSipRequest &req)
void B2BsetRelayEarlyMediaSDP (bool enabled)
void B2BsetHeaders (const string &hdr, bool replaceCRLF)
void B2BclearHeaders ()
void B2BaddHeader (const string &hdr)
void B2BremoveHeader (const string &hdr)
void transferOwnership (DSMDisposable *d)
void releaseOwnership (DSMDisposable *d)
Detailed Description
DSM interpreter instance for one call leg
Member Function Documentation
void SBCDSMInstance::B2BaddHeader (const string & hdr) [virtual]
add a header to the headers of the outgoing INVITE
Implements DSMSession.
void SBCDSMInstance::B2BaddReceivedRequest (const AmSipRequest & req) [virtual]
insert request in list of received ones
Implements DSMSession.
void SBCDSMInstance::B2BclearHeaders () [virtual]
set headers of outgoing INVITE
Implements DSMSession.
void SBCDSMInstance::B2BconnectCallee (const string & remote_party, const string & remote_uri, bool relayed_invite = false) [virtual]
B2BUA functions
Implements DSMSession.
void SBCDSMInstance::B2BremoveHeader (const string & hdr) [virtual]
remove a header to the headers of the outgoing INVITE
Implements DSMSession.
void SBCDSMInstance::B2BsetHeaders (const string & hdr, bool replaceCRLF) [virtual]
set headers of outgoing INVITE
Implements DSMSession.
void SBCDSMInstance::B2BsetRelayEarlyMediaSDP (bool enabled) [virtual]
enable early media relay as reinvite
Implements DSMSession.
CCChainProcessing SBCDSMInstance::onBLegRefused (SBCCallLeg * call, const AmSipReply & reply)
Returns:
whether to continue processing
Referenced by CCDSMModule::onBLegRefused().
CCChainProcessing SBCDSMInstance::onInDialogRequest (SBCCallLeg * call, const AmSipRequest & req)
called from A/B leg when in-dialog request comes in
Referenced by CCDSMModule::onInDialogRequest().
CCChainProcessing SBCDSMInstance::onInitialInvite (SBCCallLeg * call, InitialInviteHandlerParams & params)
Returns:
whether to continue processing called from A/B leg when in-dialog request comes in
Referenced by CCDSMModule::onInitialInvite().
void SBCDSMInstance::releaseOwnership (DSMDisposable * d) [virtual]
release ownership of object from this session instance
Implements DSMSession.
void SBCDSMInstance::transferOwnership (DSMDisposable * d) [virtual]
transfer ownership of object to this session instance
Implements DSMSession.
The documentation for this class was generated from the following files:
SBCDSMInstance.h
SBCDSMInstance.cpp