SEMS: VoiceboxFactory Class Reference
VoiceboxFactory Class Reference
Public Member Functions
VoiceboxFactory (const string &_app_name)
AmSession * onInvite (const AmSipRequest &, const string &app_name, const map< string, string > &app_params)
int onLoad ()
Friends
class VoiceboxDialog
Member Function Documentation
AmSession * VoiceboxFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
References get_header_keyvalue(), and AmUriParser::parse_uri().
int VoiceboxFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AmSessionFactory::configureModule(), explode(), AmPlugIn::getFactory4Di(), AmConfig::ModConfigPath, and str2i().
The documentation for this class was generated from the following files:
Voicebox.h
Voicebox.cpp