SEMS: CacheAnnounceDialog Class Reference
CacheAnnounceDialog Class Reference
Public Member Functions
CacheAnnounceDialog (AmFileCache *announce)
void onSessionStart ()
void startSession ()
void onBye (const AmSipRequest &req)
void onDtmf (int event, int duration_msec)
void process (AmEvent *event)
Member Function Documentation
void CacheAnnounceDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::setStopped().
void CacheAnnounceDialog::onDtmf (int event, int duration) [inline, virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
void CacheAnnounceDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
void CacheAnnounceDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmSipDialog::bye(), and AmSession::setStopped().
The documentation for this class was generated from the following files:
CacheAnnounce.h
CacheAnnounce.cpp