SEMS: AmRtpStream Class Reference
AmRtpStream Class Reference
RTP implementation.
#include <AmRtpStream.h>
Data Structures
struct PayloadMapping
Public Member Functions
void setReceiving (bool r)
void pause ()
void resume ()
AmRtpStream (AmSession *_s, int _if)
virtual ~AmRtpStream ()
int send (unsigned int ts, unsigned char *buffer, unsigned int size)
int send_raw (char *packet, unsigned int length)
int compile_and_send (const int payload, bool marker, unsigned int ts, unsigned char *buffer, unsigned int size)
int receive (unsigned char *buffer, unsigned int size, unsigned int &ts, int &payload)
void recvPacket (int fd)
void recvRtcpPacket ()
int ping ()
int hasLocalSocket ()
int getLocalSocket ()
void setLocalIP (const string &ip)
void setLocalPort (unsigned short p=0)
int getLocalPort ()
int getLocalRtcpPort ()
int getRPort ()
string getRHost ()
void setRAddr (const string &addr, unsigned short port, unsigned short rtcp_port=0)
void setPassiveMode (bool p)
bool getPassiveMode ()
unsigned int get_ssrc ()
int getLocalTelephoneEventPT ()
int getLocalTelephoneEventRate ()
void setPayloadProvider (AmPayloadProvider *pl_prov)
int getSdpMediaIndex ()
void forceSdpMediaIndex (int idx)
int getPayloadType ()
int getLastPayload ()
string getPayloadName (int payload_type)
void sendDtmf (int event, unsigned int duration_ms)
virtual void getSdpOffer (unsigned int index, SdpMedia &offer)
virtual void getSdpAnswer (unsigned int index, const SdpMedia &offer, SdpMedia &answer)
virtual int init (const AmSdp &local, const AmSdp &remote, bool force_passive_mode=false)
void setOnHold (bool on_hold)
bool getOnHold ()
void setMonitorRTPTimeout (bool m)
bool getMonitorRTPTimeout ()
void clearRTPTimeout ()
void setRelayStream (AmRtpStream *stream)
void setRelayPayloads (const PayloadMask &_relay_payloads)
void enableRtpRelay ()
void disableRtpRelay ()
void enableRawRelay ()
void disableRawRelay ()
void setRtpRelayTransparentSeqno (bool transparent)
void setRtpRelayTransparentSSRC (bool transparent)
void setRtpRelayFilterRtpDtmf (bool filter)
void stopReceiving ()
void resumeReceiving ()
void changeSession (AmSession *_s)
void setLogger (msg_logger *_logger)
void debug ()
Data Fields
bool mute
bool force_receive_dtmf
Protected Types
typedef std::vector< Payload > PayloadCollection
typedef std::map< unsigned int,
AmRtpPacket *, ts_less > ReceiveBuffer
typedef std::queue< AmRtpPacket * > RtpEventQueue
typedef std::map< unsigned
char, PayloadMapping > PayloadMappingTable
Protected Member Functions
void recvDtmfPacket (AmRtpPacket *p)
void bufferPacket (AmRtpPacket *p)
int nextPacket (AmRtpPacket *&p)
AmRtpPacket * reuseBufferedPacket ()
void handleSymmetricRtp (struct sockaddr_storage *recv_addr, bool rtcp)
void relay (AmRtpPacket *p)
void getSdp (SdpMedia &m)
void clearRTPTimeout (struct timeval *recv_time)
int getDefaultPT ()
Protected Attributes
PayloadCollection payloads
int payload
PayloadMappingTable pl_map
int sdp_media_index
unsigned int sequence
int last_payload
string r_host
unsigned short r_port
unsigned short r_rtcp_port
int l_if
struct sockaddr_storage r_saddr
struct sockaddr_storage l_saddr
struct sockaddr_storage l_rtcp_saddr
unsigned short l_port
int l_sd
unsigned int l_rtcp_port
int l_rtcp_sd
struct timeval last_recv_time
unsigned int l_ssrc
unsigned int r_ssrc
bool r_ssrc_i
bool passive
bool passive_rtcp
bool hold
bool begin_talk
bool monitor_rtp_timeout
auto_ptr< const SdpPayload > remote_telephone_event_pt
auto_ptr< const SdpPayload > local_telephone_event_pt
AmDtmfSender dtmf_sender
PacketMem mem
ReceiveBuffer receive_buf
RtpEventQueue rtp_ev_qu
AmMutex receive_mut
bool receiving
bool relay_enabled
bool relay_raw
AmRtpStream * relay_stream
bool relay_transparent_seqno
bool relay_transparent_ssrc
bool relay_filter_dtmf
AmSession * session
msg_logger * logger
AmPayloadProvider * payload_provider
PayloadMask relay_payloads
bool offer_answer_used
bool active
Detailed Description
RTP implementation.
Rtp stream high level interface.
Constructor & Destructor Documentation
AmRtpStream::AmRtpStream (AmSession * _s, int _if)
Allocates resources for future use of RTP.
References clearRTPTimeout(), get_random(), l_ssrc, payload_provider, r_saddr, and sequence.
AmRtpStream::~AmRtpStream () [virtual]
Stops the stream and frees all resources.
References l_rtcp_sd, and l_sd.
Member Function Documentation
void AmRtpStream::bufferPacket (AmRtpPacket * p) [protected]
Insert an RTP packet to the buffer queue
References active, clearRTPTimeout(), force_receive_dtmf, handleSymmetricRtp(), mem, passive, receiving, recvDtmfPacket(), relay_enabled, relay_filter_dtmf, relay_raw, relay_stream, and session.
void AmRtpStream::changeSession (AmSession * _s) [inline]
Quick hack to assign existing stream to another session. The stream should not be reinitialised implicitly (it might be used for media traffic already).
References session.
Referenced by AudioStreamData::changeSession().
void AmRtpStream::clearRTPTimeout (struct timeval * recv_time) [protected]
Clear RTP timeout at time recv_time
References clearRTPTimeout(), and last_recv_time.
Referenced by AmRtpStream(), bufferPacket(), clearRTPTimeout(), AmSession::clearRTPTimeout(), and resume().
void AmRtpStream::disableRawRelay ()
disable raw UDP relaying through relay stream
References relay_raw.
void AmRtpStream::disableRtpRelay ()
disable RTP relaying through relay stream
References relay_enabled.
Referenced by AudioStreamData::setRelayPaused(), and AudioStreamData::setRelayStream().
void AmRtpStream::enableRawRelay ()
enable raw UDP relaying through relay stream
References relay_raw.
void AmRtpStream::enableRtpRelay ()
ensable RTP relaying through relay stream
References relay_enabled.
Referenced by AudioStreamData::setRelayPaused(), and AudioStreamData::setRelayStream().
int AmRtpStream::getDefaultPT () [protected]
Select a compatible default payload
Returns:
-1 if none available.
Referenced by init().
int AmRtpStream::getLocalPort ()
Gets RTP port number. If no RTP port in assigned, assigns a new one.
Returns:
local RTP port.
References l_port, and setLocalPort().
Referenced by getSdp().
int AmRtpStream::getLocalRtcpPort ()
Gets RTCP port number. If no RTP/RTCP port in assigned, assigns a new one.
Returns:
local RTCP port.
References l_rtcp_port, and setLocalPort().
int AmRtpStream::getLocalSocket ()
initializes and gets the socket descriptor for local socket
References l_rtcp_sd, and l_sd.
Referenced by resumeReceiving(), setLocalPort(), and stopReceiving().
bool AmRtpStream::getMonitorRTPTimeout () [inline]
getter for monitor_rtp_timeout
References monitor_rtp_timeout.
bool AmRtpStream::getOnHold ()
get whether RTP stream is on hold
References hold.
Referenced by AmSession::setOnHold(), and AudioStreamData::writeStream().
string AmRtpStream::getRHost ()
Gets remote host IP.
Returns:
remote host IP.
References r_host.
Referenced by AmSession::sid4dbg().
int AmRtpStream::getRPort ()
Gets remote RTP port.
Returns:
remote RTP port.
Referenced by AmSession::getRPort().
void AmRtpStream::getSdp (SdpMedia & m) [protected]
Sets generic parameters on SDP media
References getLocalPort(), hold, and receiving.
Referenced by getSdpAnswer(), and getSdpOffer().
void AmRtpStream::getSdpAnswer (unsigned int index, const SdpMedia & offer, SdpMedia & answer) [virtual]
Generate an answer for the given SDP media based on the stream capabilities.
Parameters:
index index of the SDP media within the SDP.
offer the remote offer.
answer the local answer to be filled/completed.
Reimplemented in AmRtpAudio.
References SdpMedia::calcAnswer(), getSdp(), payload_provider, and sdp_media_index.
void AmRtpStream::getSdpOffer (unsigned int index, SdpMedia & offer) [virtual]
Generate an SDP offer based on the stream capabilities.
Parameters:
index index of the SDP media within the SDP.
offer the local offer to be filled/completed.
Reimplemented in AmRtpAudio.
References AmPayloadProvider::getPayloads(), getSdp(), payload_provider, and sdp_media_index.
void AmRtpStream::handleSymmetricRtp (struct sockaddr_storage * recv_addr, bool rtcp) [protected]
handle symmetric RTP/RTCP - if in passive mode, update raddr from rp
References passive, r_saddr, and setRAddr().
Referenced by bufferPacket().
int AmRtpStream::hasLocalSocket ()
returns the socket descriptor for local socket (initialized or not)
References l_sd.
Referenced by resumeReceiving(), and stopReceiving().
int AmRtpStream::init (const AmSdp & local, const AmSdp & remote, bool force_passive_mode = false) [virtual]
Enables RTP stream.
Parameters:
local the SDP message generated by the local UA.
remote the SDP message generated by the remote UA.
Warning:
It is necessary to call getSdpOffer/getSdpAnswer prior to init(...)
so that the internal SDP media line index is set properly.
Reimplemented in AmRtpAudio.
References active, SdpConnection::address, amci_payload_t::codec_id, getDefaultPT(), AmPayloadProvider::getDynPayload(), hold, l_port, last_payload, mute, pause(), AmPayloadProvider::payload(), payload_provider, r_saddr, remote_telephone_event_pt, resume(), amci_payload_t::sample_rate, sdp_media_index, session, setLocalIP(), setLocalPort(), setPassiveMode(), setRAddr(), and AmSdp::telephoneEventPayload().
Referenced by AmRtpAudio::init().
void AmRtpStream::pause ()
Stops RTP stream receiving RTP packets internally (received packets will be dropped).
References receiving, and session.
Referenced by init().
int AmRtpStream::ping ()
ping the remote side, to open NATs and enable symmetric RTP
References l_if, l_sd, l_ssrc, r_saddr, and sequence.
void AmRtpStream::recvDtmfPacket (AmRtpPacket * p) [protected]
insert packet in DTMF queue if correct payload
References AmSession::postDtmfEvent(), and session.
Referenced by bufferPacket().
void AmRtpStream::resume ()
Resume a paused RTP stream internally (received packets will be processed).
References clearRTPTimeout(), mem, receiving, and session.
Referenced by init().
void AmRtpStream::resumeReceiving ()
(re-)insert into RTP receiver
References getLocalSocket(), hasLocalSocket(), and l_rtcp_sd.
Referenced by AudioStreamData::resumeStreamProcessing().
AmRtpPacket * AmRtpStream::reuseBufferedPacket () [protected]
Try to reuse oldest buffered packet for newly coming packet
void AmRtpStream::sendDtmf (int event, unsigned int duration_ms)
send a DTMF as RTP payload (RFC4733)
Parameters:
event event ID (e.g. key press), see rfc
duration_ms duration in milliseconds
References dtmf_sender, and AmDtmfSender::queueEvent().
Referenced by AudioStreamData::sendDtmf(), and AmSession::sendDtmf().
void AmRtpStream::setLocalIP (const string & ip)
This function must be called before setLocalPort, because setLocalPort will bind the socket and it will be not possible to change the IP later
Referenced by AmSession::getSdpAnswer(), AmSession::getSdpOffer(), and init().
void AmRtpStream::setLocalPort (unsigned short p = 0)
Initializes with a new random local port if 'p' is 0, else binds the given port, and sets own attributes properly.
References getLocalSocket(), l_if, l_port, l_rtcp_port, l_rtcp_sd, l_sd, and session.
Referenced by getLocalPort(), getLocalRtcpPort(), and init().
void AmRtpStream::setLogger (msg_logger * _logger)
set destination for logging all received/sent RTP and RTCP packets
void AmRtpStream::setMonitorRTPTimeout (bool m) [inline]
setter for monitor_rtp_timeout
References monitor_rtp_timeout.
void AmRtpStream::setOnHold (bool on_hold)
set the RTP stream on hold
References hold.
Referenced by AudioStreamData::initStream(), and AmSession::setOnHold().
void AmRtpStream::setPassiveMode (bool p)
Symmetric RTP & RTCP: passive mode ?
References passive.
Referenced by init().
void AmRtpStream::setRAddr (const string & addr, unsigned short port, unsigned short rtcp_port = 0)
Set remote IP & port.
References mute, r_host, and r_saddr.
Referenced by handleSymmetricRtp(), init(), and AudioStreamData::setRelayStream().
void AmRtpStream::setReceiving (bool r)
Set whether RTP stream will receive RTP packets internally (received packets will be dropped or not).
References receiving.
Referenced by AudioStreamData::initStream(), and AmSession::setReceiving().
void AmRtpStream::setRelayPayloads (const PayloadMask & _relay_payloads)
set relay payloads for RTP relaying
Referenced by AudioStreamData::setRelayStream().
void AmRtpStream::setRelayStream (AmRtpStream * stream)
set relay stream for RTP relaying
References relay_stream.
Referenced by AudioStreamData::setRelayStream().
void AmRtpStream::setRtpRelayFilterRtpDtmf (bool filter)
enable or disable filtering of RTP DTMF for relay
References relay_filter_dtmf.
void AmRtpStream::setRtpRelayTransparentSeqno (bool transparent)
enable or disable transparent RTP seqno for relay
References relay_transparent_seqno.
void AmRtpStream::setRtpRelayTransparentSSRC (bool transparent)
enable or disable transparent SSRC seqno for relay
References relay_transparent_ssrc.
void AmRtpStream::stopReceiving ()
remove from RTP receiver
References getLocalSocket(), hasLocalSocket(), and l_rtcp_sd.
Referenced by AudioStreamData::stopStreamProcessing().
Field Documentation
bool AmRtpStream::active [protected]
set to true if any data received
Referenced by bufferPacket(), AmRtpAudio::get(), and init().
bool AmRtpStream::begin_talk [protected]
marker flag
AmDtmfSender AmRtpStream::dtmf_sender [protected]
DTMF sender
Referenced by sendDtmf().
bool AmRtpStream::force_receive_dtmf
should we receive RFC-2833-style DTMF even when receiving is disabled?
Referenced by bufferPacket(), and AmSession::setForceDtmfReceiving().
bool AmRtpStream::hold [protected]
mute && port == 0
Referenced by getOnHold(), getSdp(), init(), and setOnHold().
int AmRtpStream::l_if [protected]
Local interface used for this stream (index into ::Ifs)
Referenced by ping(), and setLocalPort().
unsigned short AmRtpStream::l_port [protected]
Local port
Referenced by getLocalPort(), init(), and setLocalPort().
unsigned int AmRtpStream::l_rtcp_port [protected]
Local RTCP port
Referenced by getLocalRtcpPort(), and setLocalPort().
int AmRtpStream::l_rtcp_sd [protected]
Local RTCP socket
Referenced by getLocalSocket(), resumeReceiving(), setLocalPort(), stopReceiving(), and ~AmRtpStream().
int AmRtpStream::l_sd [protected]
Local socket
Referenced by getLocalSocket(), hasLocalSocket(), ping(), setLocalPort(), and ~AmRtpStream().
unsigned int AmRtpStream::l_ssrc [protected]
Local and remote SSRC information
Referenced by AmRtpStream(), and ping().
int AmRtpStream::last_payload [protected]
Payload of last received packet. Usefull to detect talk spurt, looking for comfort noise packets.
Referenced by init().
struct timeval AmRtpStream::last_recv_time [protected]
Timestamp of the last received RTP packet
Referenced by clearRTPTimeout().
PacketMem AmRtpStream::mem [protected]
Receive buffer, queue and mutex
Referenced by bufferPacket(), and resume().
bool AmRtpStream::monitor_rtp_timeout [protected]
do check rtp timeout
Referenced by getMonitorRTPTimeout(), and setMonitorRTPTimeout().
bool AmRtpStream::mute
Mute
Referenced by init(), AmRtpAudio::put(), AmSession::setMute(), and setRAddr().
bool AmRtpStream::passive [protected]
symmetric RTP & RTCP
Referenced by bufferPacket(), handleSymmetricRtp(), and setPassiveMode().
AmPayloadProvider* AmRtpStream::payload_provider [protected]
Payload provider
Referenced by AmRtpStream(), getSdpAnswer(), getSdpOffer(), and init().
string AmRtpStream::r_host [protected]
Remote host information
Referenced by getRHost(), and setRAddr().
struct sockaddr_storage AmRtpStream::r_saddr [protected]
Local and remote host addresses
Referenced by AmRtpStream(), handleSymmetricRtp(), init(), ping(), and setRAddr().
bool AmRtpStream::receiving [protected]
should we receive packets? if not -> drop
Referenced by bufferPacket(), AmRtpAudio::get(), getSdp(), pause(), resume(), and setReceiving().
bool AmRtpStream::relay_enabled [protected]
if relay_stream is initialized, received RTP is relayed there
Referenced by bufferPacket(), disableRtpRelay(), and enableRtpRelay().
bool AmRtpStream::relay_filter_dtmf [protected]
filter RTP DTMF (2833 / 4733) in relaying
Referenced by bufferPacket(), and setRtpRelayFilterRtpDtmf().
bool AmRtpStream::relay_raw [protected]
if true, packets are note parsed or checked
Referenced by bufferPacket(), disableRawRelay(), and enableRawRelay().
AmRtpStream* AmRtpStream::relay_stream [protected]
pointer to relay stream. NOTE: This may only be accessed in initialization or by the AmRtpReceiver thread while relaying!
Referenced by bufferPacket(), and setRelayStream().
bool AmRtpStream::relay_transparent_seqno [protected]
control transparency for RTP seqno in RTP relay mode
Referenced by setRtpRelayTransparentSeqno().
bool AmRtpStream::relay_transparent_ssrc [protected]
control transparency for RTP ssrc in RTP relay mode
Referenced by setRtpRelayTransparentSSRC().
auto_ptr<const SdpPayload> AmRtpStream::remote_telephone_event_pt [protected]
Payload type for telephone event
Referenced by init().
int AmRtpStream::sdp_media_index [protected]
SDP media slot number (n-th media line)
Referenced by getSdpAnswer(), getSdpOffer(), and init().
unsigned int AmRtpStream::sequence [protected]
RTP sequence number
Referenced by AmRtpStream(), and ping().
AmSession* AmRtpStream::session [protected]
Session owning this stream
Referenced by bufferPacket(), changeSession(), init(), pause(), recvDtmfPacket(), resume(), and setLocalPort().
The documentation for this class was generated from the following files:
AmRtpStream.h
AmRtpStream.cpp