SEMS: C2DCallerDialog Class Reference
C2DCallerDialog Class Reference
Public Member Functions
C2DCallerDialog (const AmSipRequest &req, const string &filename, const string &callee_uri, UACAuthCred *credentials=NULL)
void process (AmEvent *event)
void onInvite (const AmSipRequest &req)
void onInvite2xx (const AmSipReply &reply)
void onSessionStart ()
void createCalleeSession ()
UACAuthCred * getCredentials ()
void onB2BEvent (B2BEvent *)
void updateUACTransCSeq (unsigned int old_cseq, unsigned int new_cseq)
Member Function Documentation
void C2DCallerDialog::onB2BEvent (B2BEvent * ev) [virtual]
B2BEvent handler
Reimplemented from AmB2BCallerSession.
void C2DCallerDialog::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmB2BCallerSession.
References AmBasicSipDialog::reply(), and AmSession::setStopped().
void C2DCallerDialog::onInvite2xx (const AmSipReply & reply) [virtual]
2xx reply has been received for an INVITE transaction
Reimplemented from AmB2BCallerSession.
References AmB2BSession::est_invite_cseq.
void C2DCallerDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmAudioFile::open(), and AmSession::setReceiving().
void C2DCallerDialog::process (AmEvent * event) [virtual]
See also:
AmEventQueue
Reimplemented from AmB2BSession.
References AmMediaProcessor::removeSession().
void C2DCallerDialog::updateUACTransCSeq (unsigned int old_cseq, unsigned int new_cseq) [virtual]
See also:
AmSession
Reimplemented from AmB2BSession.
References AmB2BSession::est_invite_cseq.
The documentation for this class was generated from the following files:
Click2Dial.h
Click2Dial.cpp