SEMS: b2b_connectDialog Class Reference
b2b_connectDialog Class Reference
Public Member Functions
void onSessionStart ()
void onB2ABEvent (B2ABEvent *ev)
void process (AmEvent *ev)
void onDtmf (int event, int duration)
void onBye (const AmSipRequest &req)
void onInvite (const AmSipRequest &req)
void onCancel (const AmSipRequest &req)
Protected Member Functions
AmB2ABCalleeSession * createCalleeSession ()
Member Function Documentation
void b2b_connectDialog::onB2ABEvent (B2ABEvent * ev) [virtual]
B2ABEvent handler
Reimplemented from AmB2ABCallerSession.
References AmBasicSipDialog::getStatus(), onInvite(), AmBasicSipDialog::reply(), and AmSession::setStopped().
void b2b_connectDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmB2ABSession.
References AmSession::setStopped(), and AmB2ABCallerSession::terminateOtherLeg().
void b2b_connectDialog::onCancel (const AmSipRequest & req) [virtual]
onCancel will be called if a CANCEL for a running dialog has been received. At this point, the CANCEL transaction has been replied with 200.
A normal plug-in does not have to do anything special, as normal dialogs are immediatly replied with 200 or error code.
Note: You are still responsible for responding the initial transaction.
Reimplemented from AmSession.
References AmBasicSipDialog::getStatus(), AmBasicSipDialog::reply(), and AmSession::setStopped().
void b2b_connectDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
void b2b_connectDialog::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmSession.
References AmSession::getAppParam(), AmBasicSipDialog::getStatus(), AmB2ABSession::other_id, AmB2ABSession::recvd_req, and AmBasicSipDialog::reply().
Referenced by onB2ABEvent().
void b2b_connectDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
void b2b_connectDialog::process (AmEvent * event) [virtual]
See also:
AmEventQueue
Reimplemented from AmB2ABSession.
The documentation for this class was generated from the following files:
b2b_connect.h
b2b_connect.cpp