SEMS: PrecodedDialog Class Reference
PrecodedDialog Class Reference
Public Member Functions
PrecodedDialog (AmPrecodedFile *file_def)
void onSessionStart ()
void onBye (const AmSipRequest &req)
Member Function Documentation
void PrecodedDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::setStopped().
void PrecodedDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmSipDialog::bye(), AmSession::setReceiving(), and AmSession::setStopped().
The documentation for this class was generated from the following files:
PrecodedAnnounce.h
PrecodedAnnounce.cpp