SEMS: AnnRecorderFactory Class Reference
AnnRecorderFactory Class Reference
Factory for announcement sessions.
#include <AnnRecorder.h>
Public Member Functions
AnnRecorderFactory (const string &_app_name)
int onLoad ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
AmSession * onInvite (const AmSipRequest &req, const string &app_name, AmArg &session_params)
Static Public Attributes
static AmDynInvokeFactory * message_storage_fact = NULL
static string AnnouncePath
static string DefaultAnnounce
static bool SimpleMode = false
Detailed Description
Factory for announcement sessions.
Member Function Documentation
AmSession * AnnRecorderFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
AmSession * AnnRecorderFactory::onInvite (const AmSipRequest & req, const string & app_name, AmArg & session_params) [virtual]
Creates a dialog state on new UAC request.
Parameters:
session_params parameters passed to the new session by the caller.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Reimplemented from AmSessionFactory.
References AmUACAuth::enable(), and AmUACAuth::unpackCredentials().
int AnnRecorderFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AM_PROMPT_START, AmSessionFactory::configureModule(), AmPlugIn::getFactory4Di(), and AmConfig::ModConfigPath.
The documentation for this class was generated from the following files:
AnnRecorder.h
AnnRecorder.cpp