SEMS: ht_bucket< Value > Class Template Reference
ht_bucket< Value > Class Template Reference
Public Types
typedef list< Value * > value_list
Public Member Functions
ht_bucket (unsigned long id)
bool exist (Value *t)
void remove (Value *t)
unsigned long get_id () const
void dump () const
Protected Member Functions
value_list::iterator find (Value *t)
Protected Attributes
unsigned long id
value_list elmts
template<class Value>
class ht_bucket< Value >
Member Function Documentation
template<class Value> bool ht_bucket< Value >::exist (Value * t) [inline]
Caution: The bucket MUST be locked before you can do anything with it. Searches for the value ptr in this bucket. This is used to check if the value still exists.
Returns:
true if the value still exists.
Referenced by _trans_layer::cancel(), trans_ticket::get_trans(), _trans_layer::send_reply(), and _trans_layer::timer_expired().
template<class Value> value_list::iterator ht_bucket< Value >::find (Value * t) [inline, protected]
Finds a transaction ptr in this bucket. This is used to check if the transaction still exists.
Returns:
iterator pointing at the value.
Referenced by ht_bucket< sip_trans >::exist(), and ht_bucket< sip_trans >::remove().
template<class Value> unsigned long ht_bucket< Value >::get_id () const [inline]
Returns the bucket id, which should be an index into the corresponding hash table.
Referenced by _trans_layer::send_reply(), _trans_layer::send_request(), _trans_layer::timeout(), _trans_layer::timer_expired(), _trans_layer::try_next_ip(), _trans_layer::update_uac_reply(), and _trans_layer::update_uas_request().
template<class Value> void ht_bucket< Value >::remove (Value * t) [inline]
Remove the value from this bucket, if it was still present.
Referenced by trans_ticket::remove_trans(), _trans_layer::send_reply(), _trans_layer::timeout(), _trans_layer::timer_expired(), _trans_layer::update_uac_reply(), and _trans_layer::update_uas_request().
The documentation for this class was generated from the following file:
hash_table.h