SEMS: CallLeg Class Reference
CallLeg Class Reference
#include <CallLeg.h>
Data Structures
struct OtherLegInfo
struct StatusChangeCause
Public Types
enum CallStatus {
Disconnected, NoReply, Ringing, Connected,
Disconnecting
}
enum CallFailureReason { CallRefused, CallCanceled }
Public Member Functions
virtual void onB2BEvent (B2BEvent *ev)
virtual void disconnect (bool hold_remote, bool preserve_media_session=false)
virtual void stopCall (const StatusChangeCause &cause)
virtual void putOnHold ()
virtual void resumeHeld ()
virtual bool isOnHold ()
void addCallee (CallLeg *callee, const AmSipRequest &relayed_invite)
void addCallee (const string &session_tag, const AmSipRequest &relayed_invite)
void addCallee (const string &session_tag, const string &hdrs)
void addCallee (CallLeg *callee, const string &hdrs)
void replaceExistingLeg (const string &session_tag, const AmSipRequest &relayed_invite)
void replaceExistingLeg (const string &session_tag, const string &hdrs)
void debug ()
const char * getCallStatusStr ()
int readStreams (unsigned long long ts, unsigned char *buffer)
int writeStreams (unsigned long long ts, unsigned char *buffer)
CallLeg (AmSipDialog *p_dlg=NULL, AmSipSubscription *p_subs=NULL)
CallLeg (const CallLeg *caller, AmSipDialog *p_dlg=NULL, AmSipSubscription *p_subs=NULL)
virtual int onSdpCompleted (const AmSdp &local, const AmSdp &remote)
virtual bool getSdpOffer (AmSdp &offer)
virtual bool getSdpAnswer (const AmSdp &offer, AmSdp &answer)
virtual void onEarlySessionStart ()
virtual void onSessionStart ()
Protected Member Functions
virtual void setCallStatus (CallStatus new_status)
CallStatus getCallStatus ()
virtual void onInvite (const AmSipRequest &req)
virtual void onInvite2xx (const AmSipReply &reply)
virtual void onCancel (const AmSipRequest &req)
virtual void onBye (const AmSipRequest &req)
virtual void onRemoteDisappeared (const AmSipReply &reply)
virtual void onNoAck (unsigned int cseq)
virtual void onNoPrack (const AmSipRequest &req, const AmSipReply &rpl)
virtual void onRtpTimeout ()
virtual void onSessionTimeout ()
virtual void onOtherBye (const AmSipRequest &req)
virtual void onSipRequest (const AmSipRequest &req)
virtual void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmSipDialog::Status old_dlg_status)
virtual void onInitialReply (B2BSipReplyEvent *e)
virtual void createHoldRequest (AmSdp &sdp)=0
virtual void alterHoldRequest (AmSdp &sdp)
virtual void createResumeRequest (AmSdp &sdp)
virtual void alterResumeRequest (AmSdp &sdp)
virtual void holdRequested ()
virtual void holdAccepted ()
virtual void holdRejected ()
virtual void resumeRequested ()
virtual void resumeAccepted ()
virtual void resumeRejected ()
virtual void terminateOtherLeg ()
virtual void terminateLeg ()
void changeRtpMode (RTPRelayMode new_mode)
virtual void updateLocalSdp (AmSdp &sdp)
virtual double get491RetryTime ()
Friends
class Reinvite
class PutOnHold
class ResumeHeld
Detailed Description
composed AmB2BCalleeSession & AmB2BCallerSession represents indepenedently A or B leg of a call, old clases left for compatibility
Notes:
we use the relayEvent implementation from AmB2BSession - it can happen that we have no peer (i.e. we are a standalone call leg, for example parked one) => do not create other call leg automatically
we use onSystemEvent implementation from AmB2BSession - the other leg receives and handles the same shutdown event, right?
the role (A/B leg) can be changed during the CallLeg life and is understood just this way
"A leg is the call leg created when handling initial INVITE request"
It is used
as identification what part of media session is affected by operation
when CANCEL is being processed only the CANCEL of initial INVITE is important so it is explicitly verified that it is handled in A leg)
In other words - the B leg can create new 'b-like-legs' the same way the A leg does.
Member Enumeration Documentation
enum CallLeg::CallFailureReason
reason reported in onCallFailed method
enum CallLeg::CallStatus
B2B call status.
This status need not to be related directly to SIP dialog status in appropriate call legs - for example the B2B call status can be "Connected" though the legs have received BYE replies.
Constructor & Destructor Documentation
CallLeg::CallLeg (AmSipDialog * p_dlg = NULL, AmSipSubscription * p_subs = NULL)
creates A leg
CallLeg::CallLeg (const CallLeg * caller, AmSipDialog * p_dlg = NULL, AmSipSubscription * p_subs = NULL)
creates B leg using given session as A leg
References AmSession::getNewId(), AmB2BSession::getRtpRelayMode(), AmB2BSession::lowfi_payloads, and AmB2BSession::setRtpRelayMode().
Member Function Documentation
void CallLeg::addCallee (CallLeg * callee, const AmSipRequest & relayed_invite) [inline]
add given call leg as our B leg
void CallLeg::addCallee (const string & session_tag, const AmSipRequest & relayed_invite)
add given already existing session as our B leg
References AmSession::getLocalTag().
void CallLeg::addCallee (CallLeg * callee, const string & hdrs)
add given call leg as our B leg (only stored SDP is used, we don't need to have INVITE request. Can be used in A leg and B leg as well. Additional headers may be specified - these are used in outgoing INVITE to the callee's destination.
References AmB2BSession::established_body.
virtual void CallLeg::alterHoldRequest (AmSdp & sdp) [inline, protected, virtual]
called to alter B2B hold request (i.e. the request from other peer)
Reimplemented in SBCCallLeg.
virtual void CallLeg::alterResumeRequest (AmSdp & sdp) [inline, protected, virtual]
called to alter B2B hold request (i.e. the request from other peer)
void CallLeg::changeRtpMode (RTPRelayMode new_mode) [protected]
change RTP mode (and AmB2BMedia if needed) but do not send reINVITE
Changes the mode for all peer legs as well.
WARNING: really unsafe because possibly makes the object state inconsistent with sent SIP messages (sent/received SDPs).
WARNING: might require several events exchanged between call legs, the AmB2BMedia will be valid after them!
TODO: add parameter to trigger reINVITE
Reimplemented in SBCCallLeg.
References AmB2BSession::clearRtpReceiverRelay(), AmB2BSession::relayEvent(), AmB2BSession::rtp_relay_mode, and AmB2BSession::setRtpRelayMode().
void CallLeg::debug ()
generate debug information into log with overall call leg status
References AmSession::getLocalTag(), and AmB2BSession::rtp_relay_mode.
void CallLeg::disconnect (bool hold_remote, bool preserve_media_session = false) [virtual]
does all the job around disconnecting from the other leg (updates call status, disconnects RTP from the other, puts remote on hold (if requested)
The other leg is not affected by disconnect - it is neither terminated nor informed about the peer disconnection.
References AmB2BSession::clearRtpReceiverRelay(), AmB2BSession::est_invite_cseq, AmSession::getLocalTag(), AmB2BSession::getRtpRelayMode(), putOnHold(), and AmB2BSession::relayed_req.
Referenced by onB2BEvent().
virtual bool CallLeg::getSdpAnswer (const AmSdp & offer, AmSdp & answer) [inline, virtual]
Hook called when an SDP offer is required
Hook called when an SDP answer is required
Reimplemented from AmSession.
virtual bool CallLeg::getSdpOffer (AmSdp & offer) [inline, virtual]
Hook called when an SDP offer is required
Reimplemented from AmSession.
void CallLeg::onB2BEvent (B2BEvent * ev) [virtual]
B2BEvent handler
Reimplemented from AmB2BSession.
References disconnect(), resumeHeld(), and AmB2BSession::sip_relay_only.
void CallLeg::onBye (const AmSipRequest & req) [protected, virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
Reimplemented in SBCCallLeg.
References AmB2BSession::clearRtpReceiverRelay().
void CallLeg::onCancel (const AmSipRequest & req) [protected, virtual]
onCancel will be called if a CANCEL for a running dialog has been received. At this point, the CANCEL transaction has been replied with 200.
A normal plug-in does not have to do anything special, as normal dialogs are immediatly replied with 200 or error code.
Note: You are still responsible for responding the initial transaction.
Reimplemented from AmSession.
References stopCall().
virtual void CallLeg::onEarlySessionStart () [inline, virtual]
Hook called when an early session starts (SDP OA completed + dialog in early state)
Reimplemented from AmSession.
void CallLeg::onInvite (const AmSipRequest & req) [protected, virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmSession.
Reimplemented in SBCCallLeg.
References AmB2BSession::est_invite_cseq, and AmB2BSession::recvd_req.
void CallLeg::onInvite2xx (const AmSipReply & reply) [protected, virtual]
2xx reply has been received for an INVITE transaction
Reimplemented from AmB2BSession.
void CallLeg::onNoAck (unsigned int ack_cseq) [protected, virtual]
Hook called when a UAS INVITE transaction did not receive the ACK
Reimplemented from AmB2BSession.
void CallLeg::onNoPrack (const AmSipRequest & req, const AmSipReply & rpl) [protected, virtual]
Hook called when a UAS INVITE transaction did not receive the PRACK
Reimplemented from AmSession.
void CallLeg::onOtherBye (const AmSipRequest & req) [protected, virtual]
handle BYE on other leg
Reimplemented from AmB2BSession.
Reimplemented in SBCCallLeg.
void CallLeg::onRemoteDisappeared (const AmSipReply &) [protected, virtual]
remote side is unreachable - 408/481 reply received
Reimplemented from AmB2BSession.
Reimplemented in SBCCallLeg.
References AmB2BSession::clearRtpReceiverRelay().
void CallLeg::onRtpTimeout () [protected, virtual]
This callback is called if RTP timeout encountered
Reimplemented from AmB2BSession.
int CallLeg::onSdpCompleted (const AmSdp & offer, const AmSdp & answer) [virtual]
Hook called when an SDP OA transaction has been completed
Reimplemented from AmB2BSession.
References AmSession::getLocalTag().
virtual void CallLeg::onSessionStart () [inline, virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
void CallLeg::onSessionTimeout () [protected, virtual]
This callback is called if session timeout encountered (session timers)
Reimplemented from AmB2BSession.
void CallLeg::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmSipDialog::Status old_dlg_status) [protected, virtual]
Entry point for SIP Replies
Reimplemented from AmB2BSession.
Reimplemented in SBCCallLeg.
References AmB2BSession::est_invite_cseq, AmSession::getLocalTag(), AmMimeBody::getPayload(), AmMimeBody::hasContentType(), AmSdp::parse(), AmB2BSession::relayed_req, and terminateLeg().
void CallLeg::onSipRequest (const AmSipRequest & req) [protected, virtual]
Entry point for SIP Requests
Reimplemented from AmB2BSession.
Reimplemented in SBCCallLeg.
References AmSession::getLocalTag(), AmBasicSipDialog::getStatus(), AmBasicSipDialog::reply(), and stopCall().
void CallLeg::putOnHold () [virtual]
Put remote party on hold (may change RTP relay mode!). Note that this task is asynchronous so the remote is most probably NOT 'on hold' after calling this method
This method calls handleHoldReply(false) directly if an error occurs.
Referenced by disconnect().
int CallLeg::readStreams (unsigned long long ts, unsigned char * buffer) [virtual]
Read from all media streams.
To preserve current media processing scheme it is needed to read from all streams first and then write to them. This can be important for example in case of conferences where we need to have media from all streams ready for mixing them.
So the AmMediaProcessorThread first calls readStreams on all sessions and then writeStreams on all sessions.
Parameters:
ts timestamp for which the processing is currently running
buffer multi-purpose space given from outside (AmMediaProcessorThread)
Buffer given as parametr is usable for anything, originally was intended for data read from one stream before putting to another stream.
The reason for having this buffer as parameter is that buffer size for audio processing is quite large (2K here) and thus allocating it on stack on some architectures may be problematic.
On other hand having the buffer dynamically allocated for each media session would significantly increase memory consumption per call.
So for now it seems to be the simplest way just to give the buffer as parameter from AmMediaProcessorThread and reuse it in all sessions handled by this thread (processing is done sequentially one session after another).
Reimplemented from AmSession.
References AmB2BSession::getRtpRelayMode().
void CallLeg::replaceExistingLeg (const string & session_tag, const AmSipRequest & relayed_invite)
Replace given already existing session in a B2B call. We become new A leg there regardless if we are replacing original A or B leg.
References AmSession::getLocalTag(), and AmB2BSession::rtp_relay_mode.
void CallLeg::resumeHeld () [virtual]
resume call if the remote party is on hold
Referenced by onB2BEvent().
void CallLeg::stopCall (const StatusChangeCause & cause) [virtual]
Terminate the whole B2B call (if there is no other leg only this one is stopped).
References terminateLeg(), and terminateOtherLeg().
Referenced by onCancel(), onSipRequest(), and SBCCallLeg::process().
void CallLeg::terminateLeg () [protected, virtual]
Terminate our leg and forget the other.
Reimplemented from AmB2BSession.
Referenced by onSipReply(), and stopCall().
void CallLeg::terminateOtherLeg () [protected, virtual]
Terminate the other leg and forget it.
Reimplemented from AmB2BSession.
Referenced by stopCall().
void CallLeg::updateLocalSdp (AmSdp & sdp) [protected, virtual]
Called when SDP relayed from other leg should be sent to the remote party. Default implementation updates connection address and ports.
Reimplemented from AmB2BSession.
Reimplemented in SBCCallLeg.
References AmSession::getLocalTag().
int CallLeg::writeStreams (unsigned long long ts, unsigned char * buffer) [virtual]
Write to all media streams.
For the meaning of parameters see description of readStreams() method.
Reimplemented from AmSession.
References AmB2BSession::getRtpRelayMode().
The documentation for this class was generated from the following files:
CallLeg.h
CallLeg.cpp