SEMS: IvrFactory Class Reference
IvrFactory Class Reference
session factory for python IVR sessions
#include <Ivr.h>
Public Member Functions
IvrFactory (const string &_app_name)
int onLoad ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
void addDeferredThread (PyObject *pyCallable)
void setupSessionTimer (AmSession *s)
Detailed Description
session factory for python IVR sessions
Member Function Documentation
AmSession * IvrFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Load a script using the app_name. Note: there is no default script.
Implements AmSessionFactory.
int IvrFactory::onLoad () [virtual]
Loads python script path and default script file from configuration file
Implements AmPluginFactory.
References add2path(), AmSessionFactory::configureModule(), AmPlugIn::getFactory4Seh(), AmConfig::ModConfigPath, and AmPlugIn::registerFactory4App().
The documentation for this class was generated from the following files:
Ivr.h
Ivr.cpp