SEMS: AmB2ABSession Class Reference
AmB2ABSession Class Reference
Base class for Sessions in B2ABUA mode.
#include <AmB2ABSession.h>
Public Member Functions
AmB2ABSession (const string &other_local_tag)
void onBye (const AmSipRequest &req)
virtual void connectSession ()
void disconnectSession ()
Protected Member Functions
void clear_other ()
virtual void relayEvent (AmEvent *ev)
virtual void terminateLeg ()
virtual void terminateOtherLeg ()
virtual void onB2ABEvent (B2ABEvent *ev)
void process (AmEvent *event)
Protected Attributes
string other_id
AmSessionAudioConnector * connector
std::map< int, AmSipRequest > recvd_req
Detailed Description
Base class for Sessions in B2ABUA mode.
It has two legs: Callee- and caller-leg.
Member Function Documentation
void AmB2ABSession::connectSession () [virtual]
connect audio stream to the other session
References AmMediaProcessor::addSession(), AmSession::callgroup, connector, and AmSessionAudioConnector::connectSession().
Referenced by AmB2ABCallerSession::onB2ABEvent(), AmB2ABCalleeSession::onEarlySessionStart(), AmB2ABCalleeSession::onSessionStart(), and JukecallSession::process().
void AmB2ABSession::disconnectSession ()
reverse operation of connectSession
References connector, and AmSessionAudioConnector::disconnectSession().
Referenced by onBye(), and terminateLeg().
void AmB2ABSession::onB2ABEvent (B2ABEvent * ev) [protected, virtual]
B2ABEvent handler
Reimplemented in AmB2ABCalleeSession, AmB2ABCallerSession, PySemsB2ABCalleeDialog, and b2b_connectDialog.
References terminateLeg().
Referenced by process().
void AmB2ABSession::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
Reimplemented in b2b_connectDialog.
References disconnectSession(), AmSession::setStopped(), and terminateOtherLeg().
void AmB2ABSession::process (AmEvent * event) [protected, virtual]
See also:
AmEventQueue
Reimplemented from AmSession.
Reimplemented in CallBackDialog, ServiceLineCallerDialog, JukecallSession, b2b_connectDialog, and PySemsB2ABDialog.
References onB2ABEvent().
void AmB2ABSession::relayEvent (AmEvent * ev) [protected, virtual]
Relay one event to the other side.
Reimplemented in AmB2ABCallerSession.
References other_id, and AmSessionContainer::postEvent().
Referenced by AmB2ABCalleeSession::onB2ABEvent(), AmB2ABCalleeSession::onEarlySessionStart(), AmB2ABCalleeSession::onSessionStart(), AmB2ABCalleeSession::onSipReply(), and terminateOtherLeg().
void AmB2ABSession::terminateLeg () [protected, virtual]
Terminate our leg and forget the other.
References AmSipDialog::bye(), disconnectSession(), and AmSession::setStopped().
Referenced by onB2ABEvent(), and AmB2ABCallerSession::onB2ABEvent().
void AmB2ABSession::terminateOtherLeg () [protected, virtual]
Terminate the other leg and forget it.
Reimplemented in AmB2ABCallerSession.
References relayEvent().
Referenced by onBye().
Field Documentation
AmSessionAudioConnector* AmB2ABSession::connector [protected]
reference to the audio connector - caution: not owned by callee dialog!
Referenced by connectSession(), disconnectSession(), AmB2ABCallerSession::onBeforeDestroy(), and AmB2ABCalleeSession::onBeforeDestroy().
string AmB2ABSession::other_id [protected]
local tag of the other leg
Referenced by AmB2ABCalleeSession::onB2ABEvent(), b2b_connectDialog::onInvite(), relayEvent(), and AmB2ABCallerSession::relayEvent().
std::map<int,AmSipRequest> AmB2ABSession::recvd_req [protected]
Requests received for relaying
Referenced by b2b_connectDialog::onInvite().
The documentation for this class was generated from the following files:
AmB2ABSession.h
AmB2ABSession.cpp