SEMS: AmSessionAudioConnector Class Reference
AmSessionAudioConnector Class Reference
connects the audio of two sessions together
#include <AmB2ABSession.h>
Public Member Functions
AmSessionAudioConnector ()
void connectSession (AmSession *sess)
bool disconnectSession (AmSession *sess)
void block ()
void release ()
void waitReleased ()
Detailed Description
connects the audio of two sessions together
Constructor & Destructor Documentation
AmSessionAudioConnector::AmSessionAudioConnector () [inline]
create a connector, connect audio to sess
Member Function Documentation
void AmSessionAudioConnector::block ()
mark as in use by entity not owning it
References AmCondition< T >::set().
void AmSessionAudioConnector::connectSession (AmSession * sess)
connect audio to sess
References AmSession::getLocalTag().
Referenced by AmB2ABSession::connectSession().
bool AmSessionAudioConnector::disconnectSession (AmSession * sess)
disconnect session
Returns:
whether connector is still connected after disconnect
References AmSession::getLocalTag().
Referenced by AmB2ABSession::disconnectSession().
void AmSessionAudioConnector::release ()
mark as released by entity not owning it
References AmCondition< T >::set().
Referenced by AmB2ABCalleeSession::onBeforeDestroy().
void AmSessionAudioConnector::waitReleased ()
wait until released by everyone
References AmCondition< T >::wait_for().
Referenced by AmB2ABCallerSession::onBeforeDestroy().
The documentation for this class was generated from the following files:
AmB2ABSession.h
AmB2ABSession.cpp