SEMS: VoiceboxDialog Class Reference
VoiceboxDialog Class Reference
Public Types
enum VoiceboxCallState {
None, EnteringPin, Prompting, MsgAction,
PromptTurnover, Bye
}
Public Member Functions
VoiceboxDialog (const string &user, const string &domain, const string &pin, AmPromptCollection *prompts, PromptOptions prompt_options)
void onSessionStart ()
void onDtmf (int event, int duration)
void onBye (const AmSipRequest &req)
void process (AmEvent *ev)
Member Function Documentation
void VoiceboxDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmBasicSipDialog::reply(), and AmSession::setStopped().
void VoiceboxDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist(), and int2str().
void VoiceboxDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
void VoiceboxDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmSipDialog::bye(), and AmSession::setStopped().
The documentation for this class was generated from the following files:
VoiceboxDialog.h
VoiceboxDialog.cpp