SEMS: CallGenDialog Class Reference
CallGenDialog Class Reference
Public Member Functions
CallGenDialog (AmPromptCollection &prompts, int play_rand_digits, int call_time_base, int call_time_rand)
void onStart ()
void onEarlySessionStart ()
void onSessionStart ()
void onBye (const AmSipRequest &req)
void process (AmEvent *event)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
Member Function Documentation
void CallGenDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::setStopped().
void CallGenDialog::onEarlySessionStart () [virtual]
Hook called when an early session starts (SDP OA completed + dialog in early state)
Reimplemented from AmSession.
void CallGenDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist(), int2str(), and AmCachedAudioFile::loop.
void CallGenDialog::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_dlg_status) [virtual]
Entry point for SIP Replies
Reimplemented from AmSession.
References AmBasicSipDialog::getStatus(), and AmSession::setStopped().
void CallGenDialog::onStart () [virtual]
onStart will be called before everything else.
Reimplemented from AmSession.
void CallGenDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmSipDialog::bye(), AmArg::get(), and AmSession::setStopped().
The documentation for this class was generated from the following files:
CallGen.h
CallGen.cpp