SEMS: DSMCall Class Reference
DSMCall Class Reference
#include <DSMCall.h>
Public Member Functions
DSMCall (const DSMScriptConfig &config, AmPromptCollection *prompts, DSMStateDiagramCollection &diags, const string &startDiagName, UACAuthCred *credentials=NULL)
void onStart ()
void onInvite (const AmSipRequest &req)
void onOutgoingInvite (const string &headers)
void onRinging (const AmSipReply &reply)
void onEarlySessionStart ()
void onSessionStart ()
int onSdpCompleted (const AmSdp &offer, const AmSdp &answer)
void startSession ()
void onCancel (const AmSipRequest &cancel)
void onBye (const AmSipRequest &req)
void onDtmf (int event, int duration_msec)
void onBeforeDestroy ()
void onSessionTimeout ()
void onRtpTimeout ()
void onRemoteDisappeared (const AmSipReply &reply)
void onSipRequest (const AmSipRequest &req)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
bool getSdpOffer (AmSdp &offer)
bool getSdpAnswer (const AmSdp &offer, AmSdp &answer)
void onNoAck (unsigned int cseq)
void onSystemEvent (AmSystemEvent *ev)
void process (AmEvent *event)
UACAuthCred * getCredentials ()
void addPromptSet (const string &name, AmPromptCollection *prompt_set)
void setPromptSets (map< string, AmPromptCollection * > &new_prompt_sets)
void playPrompt (const string &name, bool loop=false, bool front=false)
void flushPlaylist ()
void addToPlaylist (AmPlaylistItem *item, bool front=false)
void playFile (const string &name, bool loop, bool front=false)
void playSilence (unsigned int length, bool front=false)
void playRingtone (int length, int on, int off, int f, int f2, bool front)
void recordFile (const string &name)
unsigned int getRecordLength ()
unsigned int getRecordDataSize ()
void stopRecord ()
void setInOutPlaylist ()
void setInputPlaylist ()
void setOutputPlaylist ()
void setPromptSet (const string &name)
void addSeparator (const string &name, bool front=false)
void connectMedia ()
void disconnectMedia ()
void mute ()
void unmute ()
void transferOwnership (DSMDisposable *d)
void releaseOwnership (DSMDisposable *d)
AmB2BCalleeSession * newCalleeSession ()
void B2BterminateOtherLeg ()
void B2BconnectCallee (const string &remote_party, const string &remote_uri, bool relayed_invite=false)
void B2BaddReceivedRequest (const AmSipRequest &req)
void B2BsetRelayEarlyMediaSDP (bool enabled)
void B2BsetHeaders (const string &hdr, bool replaceCRLF)
void B2BclearHeaders ()
void B2BaddHeader (const string &hdr)
void B2BremoveHeader (const string &hdr)
Protected Member Functions
void onOtherBye (const AmSipRequest &req)
bool onOtherReply (const AmSipReply &reply)
Detailed Description
implementation of the actual session in DSM
Member Function Documentation
void DSMCall::B2BaddHeader (const string & hdr) [virtual]
add a header to the headers of the outgoing INVITE
Implements DSMSession.
void DSMCall::B2BaddReceivedRequest (const AmSipRequest & req) [virtual]
insert request in list of received ones
Implements DSMSession.
References AmB2BSession::recvd_req.
void DSMCall::B2BclearHeaders () [virtual]
set headers of outgoing INVITE
Implements DSMSession.
void DSMCall::B2BconnectCallee (const string & remote_party, const string & remote_uri, bool relayed_invite = false) [virtual]
B2BUA functions
Implements DSMSession.
void DSMCall::B2BremoveHeader (const string & hdr) [virtual]
remove a header to the headers of the outgoing INVITE
Implements DSMSession.
void DSMCall::B2BsetHeaders (const string & hdr, bool replaceCRLF) [virtual]
set headers of outgoing INVITE
Implements DSMSession.
void DSMCall::B2BsetRelayEarlyMediaSDP (bool enabled) [virtual]
enable early media relay as reinvite
Implements DSMSession.
bool DSMCall::getSdpAnswer (const AmSdp & offer, AmSdp & answer) [virtual]
Hook called when an SDP offer is required
Hook called when an SDP answer is required
Reimplemented from AmSession.
References AmSession::getSdpAnswer().
bool DSMCall::getSdpOffer (AmSdp & offer) [virtual]
Hook called when an SDP offer is required
Reimplemented from AmSession.
References AmSession::getSdpOffer().
void DSMCall::onBeforeDestroy () [virtual]
called in the session thread before the session is destroyed, i.e. after the main event loop has finished
Reimplemented from AmSession.
void DSMCall::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmB2BCallerSession.
References AmB2BSession::clearRtpReceiverRelay().
void DSMCall::onCancel (const AmSipRequest & req) [virtual]
onCancel will be called if a CANCEL for a running dialog has been received. At this point, the CANCEL transaction has been replied with 200.
A normal plug-in does not have to do anything special, as normal dialogs are immediatly replied with 200 or error code.
Note: You are still responsible for responding the initial transaction.
Reimplemented from AmB2BCallerSession.
References AmBasicSipDialog::getStatus().
void DSMCall::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References int2str().
void DSMCall::onEarlySessionStart () [virtual]
Hook called when an early session starts (SDP OA completed + dialog in early state)
Reimplemented from AmSession.
References AmSession::getInput(), AmSession::getOutput(), and AmSession::setInput().
void DSMCall::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmB2BCallerSession.
References AmBasicSipDialog::getStatus(), and DSMStateEngine::onInvite().
void DSMCall::onNoAck (unsigned int ack_cseq) [virtual]
Hook called when a UAS INVITE transaction did not receive the ACK
Reimplemented from AmB2BSession.
void DSMCall::onOtherBye (const AmSipRequest & req) [protected, virtual]
handle BYE on other leg
Reimplemented from AmB2BSession.
bool DSMCall::onOtherReply (const AmSipReply & reply) [protected, virtual]
Reply received from other leg has been replied
Returns:
true if reply was processed (should be absorbed)
false if reply was not processed
Reimplemented from AmB2BSession.
References int2str().
void DSMCall::onOutgoingInvite (const string & headers) [virtual]
onOutgoingInvite will be called if an INVITE is sent in the session.
Reimplemented from AmSession.
References AmSession::accept_early_session, and DSMStateEngine::onInvite().
void DSMCall::onRemoteDisappeared (const AmSipReply &) [virtual]
remote side is unreachable - 408/481 reply received
Reimplemented from AmB2BCallerSession.
References int2str().
void DSMCall::onRinging (const AmSipReply & reply) [virtual]
onRinging will be called after 180 is received. If local audio is set up, session is added to media processor.
Reimplemented from AmSession.
References AmMimeBody::empty(), and int2str().
void DSMCall::onRtpTimeout () [virtual]
This callback is called if RTP timeout encountered
Reimplemented from AmB2BSession.
int DSMCall::onSdpCompleted (const AmSdp & offer, const AmSdp & answer) [virtual]
Hook called when an SDP OA transaction has been completed
Reimplemented from AmB2BSession.
References AmMimeBody::addPart(), AmMimeBody::hasContentType(), AmSdp::print(), and AmMimeBody::setPayload().
void DSMCall::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
void DSMCall::onSessionTimeout () [virtual]
This callback is called if session timeout encountered (session timers)
Reimplemented from AmB2BSession.
void DSMCall::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_dlg_status) [virtual]
Entry point for SIP Replies
Reimplemented from AmB2BSession.
References AmBasicSipDialog::getStatus(), int2str(), and AmSession::setStopped().
void DSMCall::onSipRequest (const AmSipRequest & req) [virtual]
Entry point for SIP Requests
Reimplemented from AmB2BSession.
References int2str().
void DSMCall::onStart () [virtual]
onStart will be called before everything else.
Reimplemented from AmSession.
void DSMCall::onSystemEvent (AmSystemEvent * ev) [virtual]
entry point for system events
Reimplemented from AmB2BCallerSession.
void DSMCall::process (AmEvent * event) [virtual]
See also:
AmEventQueue
Reimplemented from AmB2BSession.
References AmConfig::DeadRtpTime, AmArg::get(), and int2str().
void DSMCall::releaseOwnership (DSMDisposable * d) [virtual]
release ownership of object from this session instance
Implements DSMSession.
void DSMCall::transferOwnership (DSMDisposable * d) [virtual]
transfer ownership of object to this session instance
Implements DSMSession.
The documentation for this class was generated from the following files:
DSMCall.h
DSMCall.cpp