SEMS: AorBucket Class Reference
AorBucket Class Reference
#include <RegisterCache.h>
Public Member Functions
AorBucket (unsigned long id)
AorEntry * get (const string &aor)
void gbc (RegCacheStorageHandler *h, long int now, list< string > &alias_list)
void dump_elmt (const string &aor, const AorEntry *p_aor_entry) const
Detailed Description
Hash-table bucket: AoR -> AorEntry
Member Function Documentation
AorEntry * AorBucket::get (const string & aor)
Match and retrieve the cache entry associated with the AOR passed. aor: canonicalized AOR
Reimplemented from ht_map_bucket< string, AorEntry >.
Referenced by _RegisterCache::getAlias(), _RegisterCache::getAorAliasMap(), _RegisterCache::remove(), and _RegisterCache::update().
The documentation for this class was generated from the following files:
RegisterCache.h
RegisterCache.cpp