SEMS: AmSipDialog Class Reference
AmSipDialog Class Reference
implements the dialog state machine
#include <AmSipDialog.h>
Public Member Functions
AmSipDialog (AmSipDialogEventHandler *h=NULL)
bool getUACInvTransPending ()
AmSipRequest * getUASPendingInv ()
int onSdpCompleted ()
bool getSdpOffer (AmSdp &offer)
bool getSdpAnswer (const AmSdp &offer, AmSdp &answer)
AmOfferAnswer::OAState getOAState ()
void setOAState (AmOfferAnswer::OAState n_st)
void setOAEnabled (bool oa_enabled)
const AmSdp & getLocalSdp ()
const AmSdp & getRemoteSdp ()
void setRel100State (Am100rel::State rel100_state)
void uasTimeout (AmSipTimeoutEvent *to_ev)
int send_200_ack (unsigned int inv_cseq, const AmMimeBody *body=NULL, const string &hdrs="", int flags=0)
int bye (const string &hdrs="", int flags=0)
int cancel ()
int prack (const AmSipReply &reply1xx, const AmMimeBody *body, const string &hdrs)
int update (const AmMimeBody *body, const string &hdrs)
int reinvite (const string &hdrs, const AmMimeBody *body, int flags=0)
int invite (const string &hdrs, const AmMimeBody *body)
int refer (const string &refer_to, int expires=-1, const string &referred_by="")
int info (const string &hdrs, const AmMimeBody *body)
int transfer (const string &target)
int drop ()
Protected Member Functions
int onTxReply (const AmSipRequest &req, AmSipReply &reply, int &flags)
int onTxRequest (AmSipRequest &req, int &flags)
void onReplyTxed (const AmSipRequest &req, const AmSipReply &reply)
void onRequestTxed (const AmSipRequest &req)
bool onRxReqSanity (const AmSipRequest &req)
bool onRxReqStatus (const AmSipRequest &req)
bool onRxReplySanity (const AmSipReply &reply)
bool onRxReplyStatus (const AmSipReply &reply)
Protected Attributes
unsigned int pending_invites
AmSdp sdp_local
AmSdp sdp_remote
bool early_session_started
bool session_started
AmOfferAnswer oa
bool offeranswer_enabled
Am100rel rel100
Detailed Description
implements the dialog state machine
Member Function Documentation
int AmSipDialog::bye (const string & hdrs = "", int flags = 0)
Returns:
0 on success
References cancel(), getUACInvTransPending(), AmBasicSipDialog::reply(), send_200_ack(), and AmBasicSipDialog::sendRequest().
Referenced by AmSession::onCancel(), AnnRecorderDialog::onDtmf(), CallBackDialog::onInvite(), AmSession::onNoAck(), AmSession::onRemoteDisappeared(), AmOfferAnswer::onRequestIn(), AmSession::onRtpTimeout(), onRxReplyStatus(), PrecodedDialog::onSessionStart(), JukecallSession::onSessionStart(), AmSession::onSessionTimeout(), AnnounceTransferDialog::onSipReply(), AnnounceTransferDialog::onSipRequest(), EarlyRecordDialog::process(), CacheAnnounceDialog::process(), AnnouncementDialog::process(), RtmpSession::process(), DtmfTesterDialog::process(), AnnounceAuthDialog::process(), WebConferenceDialog::process(), VoiceboxDialog::process(), AnnRecorderDialog::process(), ConferenceDialog::process(), CallGenDialog::process(), AmSession::processingCycle(), AmB2ABSession::terminateLeg(), and AmB2BSession::terminateLeg().
int AmSipDialog::cancel ()
Returns:
0 on success
References AmBasicSipDialog::getStatus().
Referenced by bye().
bool AmSipDialog::getUACInvTransPending ()
Returns:
whether UAC INVITE transaction is pending
Referenced by bye(), AmB2BSession::onB2BEvent(), AmB2BSession::refresh(), and AmSession::refresh().
AmSipRequest * AmSipDialog::getUASPendingInv ()
Returns:
a pending UAS INVITE transaction or NULL
Referenced by RtmpSession::process().
int AmSipDialog::info (const string & hdrs, const AmMimeBody * body)
Returns:
0 on success
References AmBasicSipDialog::getStatus(), and AmBasicSipDialog::sendRequest().
int AmSipDialog::invite (const string & hdrs, const AmMimeBody * body)
Returns:
0 on success
References AmBasicSipDialog::getStatus(), and AmBasicSipDialog::sendRequest().
Referenced by AmSession::sendInvite().
void AmSipDialog::onReplyTxed (const AmSipRequest & req, const AmSipReply & reply) [protected, virtual]
Executed for replies sent by a local UA, after the reply has been successfuly sent.
Error code list from RFC 5057: those error codes terminate the dialog
Note: 408, 480 should only terminate the usage according to RFC 5057.
Reimplemented from AmBasicSipDialog.
void AmSipDialog::onRequestTxed (const AmSipRequest & req) [protected, virtual]
Executed for requests sent by a local UA, after the request has been successfuly sent.
Reimplemented from AmBasicSipDialog.
Referenced by send_200_ack().
bool AmSipDialog::onRxReplySanity (const AmSipReply & reply) [protected, virtual]
Basic sanity check on received replies
Returns:
true to continue processing, false otherwise
Reimplemented from AmBasicSipDialog.
bool AmSipDialog::onRxReplyStatus (const AmSipReply & reply) [protected, virtual]
Executed from onRxReply() to allow inherited classes to extend the basic behavior (deletes the transaction on final reply).
Returns:
true to continue processing, false otherwise
Error code list from RFC 5057: those error codes terminate the dialog
Note: 408, 480 should only terminate the usage according to RFC 5057.
Reimplemented from AmBasicSipDialog.
References bye(), send_200_ack(), and AmBasicSipDialog::sendRequest().
bool AmSipDialog::onRxReqSanity (const AmSipRequest & req) [protected, virtual]
Basic sanity check on received requests
Note: At this point in the processing, the request has not been inserted yet into the uas_trans container. Thus, reply_error() should be used instead of reply() method.
Returns:
true to continue processing, false otherwise
Reimplemented from AmBasicSipDialog.
References get_random(), AmOfferAnswer::getState(), int2str(), AmBasicSipDialog::onRxReqSanity(), onRxReqStatus(), AmBasicSipEventHandler::onSipRequest(), and AmBasicSipDialog::reply_error().
bool AmSipDialog::onRxReqStatus (const AmSipRequest & req) [protected, virtual]
Executed from onRxRequest() to allow inherited classes to extend the basic behavior.
Returns:
true to continue processing, false otherwise
Reimplemented from AmBasicSipDialog.
References AmOfferAnswer::onRequestIn(), and AmBasicSipDialog::reply().
Referenced by onRxReqSanity().
int AmSipDialog::onSdpCompleted ()
Calls onSdpCompleted on the session event handler and executes onSessionStart/onEarlySessionStart when required.
References AmBasicSipDialog::getStatus().
int AmSipDialog::onTxReply (const AmSipRequest & req, AmSipReply & reply, int & flags) [protected, virtual]
Executed for replies sent by a local UA, right before the reply is passed to the transaction layer.
Reimplemented from AmBasicSipDialog.
int AmSipDialog::onTxRequest (AmSipRequest & req, int & flags) [protected, virtual]
Executed for requests sent by a local UA, right before the request is passed to the transaction layer.
Reimplemented from AmBasicSipDialog.
References AmBasicSipDialog::onTxRequest().
Referenced by send_200_ack().
int AmSipDialog::prack (const AmSipReply & reply1xx, const AmMimeBody * body, const string & hdrs)
Returns:
0 on success
References AmBasicSipDialog::getStatus(), int2str(), and AmBasicSipDialog::sendRequest().
Referenced by AmSession::onInvite1xxRel().
int AmSipDialog::refer (const string & refer_to, int expires = -1, const string & referred_by = "")
Returns:
0 on success
References AmBasicSipDialog::getStatus(), int2str(), and AmBasicSipDialog::sendRequest().
Referenced by AnnounceTransferDialog::process().
int AmSipDialog::reinvite (const string & hdrs, const AmMimeBody * body, int flags = 0)
Returns:
0 on success
References AmBasicSipDialog::getStatus(), and AmBasicSipDialog::sendRequest().
Referenced by AmB2BSession::sendEstablishedReInvite(), and AmSession::sendReinvite().
int AmSipDialog::send_200_ack (unsigned int inv_cseq, const AmMimeBody * body = NULL, const string & hdrs = "", int flags = 0)
Returns:
0 on success
References AmBasicSipDialog::getContactHdr(), AmBasicSipDialog::getRoute(), AmBasicSipDialog::logger, onRequestTxed(), onTxRequest(), and AmConfig::Signature.
Referenced by bye(), AmSession::onInvite2xx(), onRxReplyStatus(), and AmB2BSession::relaySip().
int AmSipDialog::transfer (const string & target)
Returns:
0 on success
References AmBasicSipDialog::getStatus(), and AmBasicSipDialog::sendRequest().
int AmSipDialog::update (const AmMimeBody * body, const string & hdrs)
Returns:
0 on success
References AmBasicSipDialog::getStatus(), and AmBasicSipDialog::sendRequest().
Referenced by AmSession::sendUpdate().
The documentation for this class was generated from the following files:
AmSipDialog.h
AmSipDialog.cpp