SEMS: udp_trsp Class Reference
udp_trsp Class Reference
Public Member Functions
udp_trsp (udp_trsp_socket *sock)
Protected Member Functions
void run ()
void on_stop ()
Constructor & Destructor Documentation
udp_trsp::udp_trsp (udp_trsp_socket * sock)
See also:
transport
trsp_socket
Member Function Documentation
void udp_trsp::on_stop (void) [protected, virtual]
See also:
AmThread
Implements AmThread.
void udp_trsp::run () [protected, virtual]
See also:
AmThread
Implements AmThread.
References trsp_socket::get_ip(), trsp_socket::get_port(), and trsp_socket::get_sd().
The documentation for this class was generated from the following files:
udp_trsp.h
udp_trsp.cpp