SEMS: AmB2BCallerSession Class Reference
AmB2BCallerSession Class Reference
Caller leg of a B2B session.
#include <AmB2BSession.h>
Public Types
enum CalleeStatus { None = 0, NoReply, Ringing, Connected }
Public Member Functions
CalleeStatus getCalleeStatus ()
void setCalleeStatus (CalleeStatus c)
virtual AmB2BCalleeSession * newCalleeSession ()
void connectCallee (const string &remote_party, const string &remote_uri, bool relayed_invite=false)
const AmSipRequest & getOriginalRequest ()
void onInvite (const AmSipRequest &req)
void onInvite2xx (const AmSipReply &reply)
void onCancel (const AmSipRequest &req)
void onBye (const AmSipRequest &req)
void onRemoteDisappeared (const AmSipReply &reply)
void onSystemEvent (AmSystemEvent *ev)
void terminateLeg ()
void terminateOtherLeg ()
virtual void onB2BEvent (B2BEvent *ev)
AmSipRequest * getInviteReq ()
void set_sip_relay_early_media_sdp (bool r)
void initializeRTPRelay (AmB2BCalleeSession *callee_session)
Protected Member Functions
virtual void createCalleeSession ()
int relayEvent (AmEvent *ev)
Protected Attributes
AmSipRequest invite_req
bool sip_relay_early_media_sdp
Detailed Description
Caller leg of a B2B session.
Member Function Documentation
void AmB2BCallerSession::initializeRTPRelay (AmB2BCalleeSession * callee_session)
initialize RTP relay mode, if rtp_relay_enabled must be called *before* callee_session is started
References AmB2BSession::enable_dtmf_rtp_detection, AmB2BSession::enable_dtmf_rtp_filtering, AmB2BSession::enable_dtmf_transcoding, AmB2BSession::lowfi_payloads, AmB2BSession::rtp_relay_mode, and AmB2BSession::setRtpRelayMode().
void AmB2BCallerSession::onB2BEvent (B2BEvent * ev) [virtual]
B2BEvent handler
Reimplemented from AmB2BSession.
Reimplemented in C2DCallerDialog.
References AmMimeBody::empty(), AmB2BSession::established_body, AmB2BSession::onOtherReply(), sip_relay_early_media_sdp, AmB2BSession::sip_relay_only, terminateLeg(), terminateOtherLeg(), and AmB2BSession::updateSessionDescription().
void AmB2BCallerSession::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
Reimplemented in IvrDialog, DSMCall, EarlyAnnounceDialog, and MyCCDialog.
References AmB2BSession::clearRtpReceiverRelay().
void AmB2BCallerSession::onCancel (const AmSipRequest & req) [virtual]
onCancel will be called if a CANCEL for a running dialog has been received. At this point, the CANCEL transaction has been replied with 200.
A normal plug-in does not have to do anything special, as normal dialogs are immediatly replied with 200 or error code.
Note: You are still responsible for responding the initial transaction.
Reimplemented from AmSession.
Reimplemented in DSMCall, and EarlyAnnounceDialog.
References terminateLeg(), and terminateOtherLeg().
void AmB2BCallerSession::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmSession.
Reimplemented in IvrDialog, EarlyAnnounceDialog, DSMCall, C2DCallerDialog, and AnnounceCallerDialog.
References AmB2BSession::est_invite_cseq.
void AmB2BCallerSession::onInvite2xx (const AmSipReply & reply) [virtual]
2xx reply has been received for an INVITE transaction
Reimplemented from AmB2BSession.
Reimplemented in C2DCallerDialog.
References AmB2BSession::est_invite_cseq.
void AmB2BCallerSession::onRemoteDisappeared (const AmSipReply &) [virtual]
remote side is unreachable - 408/481 reply received
Reimplemented from AmB2BSession.
Reimplemented in DSMCall.
References AmB2BSession::clearRtpReceiverRelay().
void AmB2BCallerSession::onSystemEvent (AmSystemEvent * ev) [virtual]
entry point for system events
Reimplemented from AmSession.
Reimplemented in DSMCall.
References terminateOtherLeg().
int AmB2BCallerSession::relayEvent (AmEvent * ev) [protected, virtual]
Relay one event to the other side.
Returns:
0 on success
Reimplemented from AmB2BSession.
References AmSession::getLocalTag(), and AmSession::getStopped().
Referenced by EarlyAnnounceDialog::process().
void AmB2BCallerSession::terminateLeg () [virtual]
Terminate our leg and forget the other.
Reimplemented from AmB2BSession.
Referenced by onB2BEvent(), onCancel(), and MyCCDialog::process().
void AmB2BCallerSession::terminateOtherLeg () [virtual]
Terminate the other leg and forget it.
Reimplemented from AmB2BSession.
Referenced by onB2BEvent(), MyCCDialog::onBye(), onCancel(), onSystemEvent(), and MyCCDialog::process().
Field Documentation
bool AmB2BCallerSession::sip_relay_early_media_sdp [protected]
Tell if the session should relay early media SDPs to caller leg
Referenced by onB2BEvent().
The documentation for this class was generated from the following files:
AmB2BSession.h
AmB2BSession.cpp