SEMS: _RegisterCache Class Reference
_RegisterCache Class Reference
Public Member Functions
void setStorageHandler (RegCacheStorageHandler *h)
bool getAlias (const string &aor, const string &uri, const string &public_ip, RegBinding &out_binding)
void update (const string &alias, long int reg_expires, const AliasEntry &alias_update)
void update (long int reg_expires, const AliasEntry &alias_update)
bool updateAliasExpires (const string &alias, long int ua_expires)
void remove (const string &aor, const string &uri, const string &alias)
void remove (const string &aor)
bool getAorAliasMap (const string &aor, map< string, string > &alias_map)
bool findAliasEntry (const string &alias, AliasEntry &alias_entry)
bool findAEByContact (const string &contact_uri, const string &remote_ip, unsigned short remote_port, AliasEntry &ae)
bool throttleRegister (RegisterCacheCtx &ctx, const AmSipRequest &req, msg_logger *logger=NULL)
bool saveSingleContact (RegisterCacheCtx &ctx, const AmSipRequest &req, msg_logger *logger=NULL)
unsigned int getActiveRegs ()
Static Public Member Functions
static string canonicalize_aor (const string &aor)
static string compute_alias_hash (const string &aor, const string &contact_uri, const string &public_ip)
Protected Member Functions
void dispose ()
void run ()
void on_stop ()
AorBucket * getAorBucket (const string &aor)
AliasBucket * getAliasBucket (const string &alias)
ContactBucket * getContactBucket (const string &contact_uri, const string &remote_ip, unsigned short remote_port)
int parseAoR (RegisterCacheCtx &ctx, const AmSipRequest &req, msg_logger *logger)
int parseContacts (RegisterCacheCtx &ctx, const AmSipRequest &req, msg_logger *logger)
int parseExpires (RegisterCacheCtx &ctx, const AmSipRequest &req, msg_logger *logger)
void setAliasUATimer (AliasEntry *alias_e)
void removeAliasUATimer (AliasEntry *alias_e)
Member Function Documentation
string _RegisterCache::canonicalize_aor (const string & uri) [static]
From RFC 3261 (Section 10.3, step 5): "all URI parameters MUST be removed (including the user-param), and any escaped characters MUST be converted to their unescaped form"
bool _RegisterCache::findAEByContact (const string & contact_uri, const string & remote_ip, unsigned short remote_port, AliasEntry & ae)
Retrieve the alias entry related to the given contact-URI, remote-IP & port
References findAliasEntry(), and getContactBucket().
bool _RegisterCache::findAliasEntry (const string & alias, AliasEntry & alias_entry)
Retrieve the alias entry related to the given alias
References getAliasBucket().
Referenced by findAEByContact(), getAorAliasMap(), saveSingleContact(), and throttleRegister().
unsigned int _RegisterCache::getActiveRegs () [inline]
Statistics
bool _RegisterCache::getAlias (const string & aor, const string & uri, const string & public_ip, RegBinding & out_binding)
Match, retrieve the contact cache entry associated with the URI passed, and return the alias found in the cache entry.
Note: this function locks and unlocks the contact cache bucket.
aor: canonical Address-of-Record uri: Contact-URI
References AorBucket::get(), and getAorBucket().
Referenced by throttleRegister().
AliasBucket * _RegisterCache::getAliasBucket (const string & alias) [protected]
Returns the bucket associated with the alias given alias: Contact-user
Referenced by findAliasEntry(), and update().
bool _RegisterCache::getAorAliasMap (const string & aor, map< string, string > & alias_map)
Retrieve an alias map containing all entries related to a particular AOR. This is needed to support REGISTER with '*' contact.
Note: this function locks and unlocks the contact cache bucket.
aor: canonical Address-of-Record alias_map: alias -> contact
References findAliasEntry(), AorBucket::get(), and getAorBucket().
Referenced by saveSingleContact().
AorBucket * _RegisterCache::getAorBucket (const string & aor) [protected]
Returns the bucket associated with the passed contact-uri aor: canonicalized AOR
Referenced by getAlias(), getAorAliasMap(), remove(), and update().
ContactBucket * _RegisterCache::getContactBucket (const string & contact_uri, const string & remote_ip, unsigned short remote_port) [protected]
Returns the bucket associated with the contact-URI given
Referenced by findAEByContact(), and update().
void _RegisterCache::remove (const string & aor, const string & uri, const string & alias)
Remove contact cache entry and alias map entries.
Note: this function locks and unlocks the contact cache bucket and the alias map bucket.
aor: canonical Address-of-Record uri: Contact-URI alias:
References AorBucket::get(), getAorBucket(), and ht_map_bucket< Key, Value, ElmtAlloc, ElmtCompare >::remove().
bool _RegisterCache::saveSingleContact (RegisterCacheCtx & ctx, const AmSipRequest & req, msg_logger * logger = NULL)
Save a single REGISTER contact into cache
Returns false if failed:
if request is not a REGISTER.
more than one contact should be (un)registered.
If true has been returned, the request has already been replied with either an error or 200 (w/ contact).
Note: this function also handles binding query. (REGISTER w/o contacts)
References findAliasEntry(), getAorAliasMap(), int2str(), AmBasicSipDialog::reply_error(), str2i(), and update().
bool _RegisterCache::throttleRegister (RegisterCacheCtx & ctx, const AmSipRequest & req, msg_logger * logger = NULL)
Throttle REGISTER requests
Returns false if REGISTER should be forwarded:
if registrar binding should be renewed.
if source IP or port do not match the saved IP & port.
if the request unregisters any contact.
if request is not a REGISTER
References findAliasEntry(), getAlias(), long2str(), AmBasicSipDialog::reply_error(), and str2long().
void _RegisterCache::update (const string & alias, long int reg_expires, const AliasEntry & alias_update)
Update contact cache entry and alias map entries.
Note: this function locks and unlocks the contact cache bucket and the alias map bucket.
aor: canonical Address-of-Record uri: Contact-URI alias:
References AorBucket::get(), getAliasBucket(), getAorBucket(), getContactBucket(), and ht_map_bucket< Key, Value, ElmtAlloc, ElmtCompare >::insert().
Referenced by saveSingleContact().
The documentation for this class was generated from the following files:
RegisterCache.h
RegisterCache.cpp