SEMS: trsp_socket Class Reference
trsp_socket Class Reference
Public Types
enum socket_options { force_via_address = (1 << 0), force_outbound_if = (1 << 1), use_raw_sockets = (1 << 2), no_transport_in_contact = (1 << 3) }
Public Member Functions
trsp_socket (unsigned short if_num, unsigned int opts, unsigned int sys_if_idx=0, int sd=0)
virtual int bind (const string &address, unsigned short port)=0
virtual const char * get_transport () const =0
const char * get_ip () const
unsigned short get_port () const
void set_public_ip (const string &ip)
const char * get_advertised_ip () const
int get_sd () const
unsigned short get_if () const
virtual bool is_reliable () const
bool is_opt_set (unsigned int mask) const
void copy_addr_to (sockaddr_storage *sa) const
bool match_addr (sockaddr_storage *other_addr) const
virtual int send (const sockaddr_storage *sa, const char *msg, const int msg_len, unsigned int flags)=0
Static Public Attributes
static int log_level_raw_msgs = L_DBG
Protected Attributes
int sd
sockaddr_storage addr
string ip
unsigned short port
string public_ip
unsigned short if_num
unsigned int sys_if_idx
unsigned int socket_options
Member Function Documentation
virtual int trsp_socket::bind (const string & address, unsigned short port) [pure virtual]
Binds the transport socket to an address
Returns:
-1 if error(s) occured.
Implemented in tcp_server_socket, and udp_trsp_socket.
void trsp_socket::copy_addr_to (sockaddr_storage * sa) const
Copy the internal address into the given one (sa).
Referenced by _trans_layer::cancel(), sip_trans::retransmit(), _trans_layer::send_non_200_ack(), _trans_layer::send_reply(), _trans_layer::send_request(), _trans_layer::timer_expired(), and _trans_layer::try_next_ip().
const char * trsp_socket::get_advertised_ip () const
Getter for advertised IP address
Returns:
either bound IP or public IP
References get_ip().
unsigned short trsp_socket::get_if () const
Getter for the interface number
Referenced by _trans_layer::register_transport(), and _trans_layer::try_next_ip().
const char * trsp_socket::get_ip () const
Getter for IP address
Referenced by get_advertised_ip(), udp_trsp::run(), and tcp_trsp::run().
unsigned short trsp_socket::get_port () const
Getter for the port number
Referenced by udp_trsp::run(), and tcp_trsp::run().
int trsp_socket::get_sd () const
Getter for the socket descriptor
Referenced by udp_trsp::run(), and tcp_trsp::run().
virtual const char* trsp_socket::get_transport () const [pure virtual]
Getter for the transport name
Implemented in tcp_server_socket, tcp_trsp_socket, and udp_trsp_socket.
Referenced by _trans_layer::register_transport(), and _trans_layer::send_reply().
bool trsp_socket::is_opt_set (unsigned int mask) const
Checks for socket options
Referenced by _trans_layer::send_reply().
virtual bool trsp_socket::is_reliable () const [inline, virtual]
Is the transport reliable?
Reimplemented in tcp_server_socket, and tcp_trsp_socket.
Referenced by _trans_layer::send_reply(), _trans_layer::try_next_ip(), _trans_layer::update_uac_reply(), and _trans_layer::update_uas_request().
bool trsp_socket::match_addr (sockaddr_storage * other_addr) const
Match with the given address
Returns:
true if address matches
virtual int trsp_socket::send (const sockaddr_storage * sa, const char * msg, const int msg_len, unsigned int flags) [pure virtual]
Sends a message.
Returns:
-1 if error(s) occured.
Implemented in tcp_server_socket, tcp_trsp_socket, and udp_trsp_socket.
Referenced by sip_trans::retransmit(), _trans_layer::send_non_200_ack(), _trans_layer::send_reply(), and _trans_layer::send_sl_reply().
void trsp_socket::set_public_ip (const string & ip)
Setter for public IP address
The documentation for this class was generated from the following files:
transport.h
transport.cpp