SEMS: AnswerMachineDialog Class Reference
AnswerMachineDialog Class Reference
Public Member Functions
AnswerMachineDialog (const string &user, const string &sender, const string &domain, const string &email, const string &announce_file, const string &uid, const string &did, FILE *announce_fp, int vm_mode, const EmailTmplDict &template_variables, const EmailTemplate *tmpl)
void process (AmEvent *event)
void onSessionStart ()
void onBye (const AmSipRequest &req)
void onDtmf (int event, int duration_msec)
Friends
class AnswerMachineFactory
Member Function Documentation
void AnswerMachineDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmBasicSipDialog::reply(), and AmSession::setStopped().
void AnswerMachineDialog::onDtmf (int event, int duration) [inline, virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
void AnswerMachineDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References add2path(), AmSession::getLocalTag(), AmAudioFile::open(), and AmSession::setReceiving().
void AnswerMachineDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmArg::get().
The documentation for this class was generated from the following files:
AnswerMachine.h
AnswerMachine.cpp