SEMS: AmMediaSession Class Reference
AmMediaSession Class Reference
#include <AmMediaProcessor.h>
Public Member Functions
virtual int readStreams (unsigned long long ts, unsigned char *buffer)=0
virtual int writeStreams (unsigned long long ts, unsigned char *buffer)=0
virtual void processDtmfEvents ()=0
virtual void clearAudio ()=0
virtual void clearRTPTimeout ()=0
virtual void onMediaProcessingStarted ()
virtual void onMediaProcessingTerminated ()
virtual bool isProcessingMedia ()
virtual bool isDetached ()
Detailed Description
Interface for basic media session processing.
Media processor stores set of objects implementing this interface and periodically triggers media processing on each of them.
First it calls readStreams() method on all managed media sessions to read from all streams first and then calls writeStreams() to send data out in all these sessions.
Once audio processing of all media sessions is done, media processor walks through them once more and calls processDtmfEvents() on them to handle DTMF events detected when reading data from media streams.
Member Function Documentation
virtual void AmMediaSession::clearAudio () [pure virtual]
Reset all media processing elements.
Called as part of cleanup when removing session from media processor upon an processing error (either readStreams() or writeStreams() returning error).
Implemented in AmB2BMedia, AmSession, and WebConferenceDialog.
virtual void AmMediaSession::clearRTPTimeout () [pure virtual]
Reset timeouts of all RTP streams related to this media session.
Called during initialization when session starts to be processed by media processor.
Implemented in AmSession, and AmB2BMedia.
virtual bool AmMediaSession::isDetached () [inline, virtual]
Indicates if the object is used by media processor.
Seems to be duplicate to isProcessingMedia(). It was kept to reduce number of changes in existing code.
References isProcessingMedia().
virtual bool AmMediaSession::isProcessingMedia () [inline, virtual]
Indicates if the object is used by media processor.
Returns value of internal variable for distinguishing if the object is already added into media processor. It should be avoided to insert one session into media processor multiple times.
Note that using default implementation of onMediaProcessingStarted and onMediaProcessingTerminated is required for proper function.
Referenced by isDetached(), AmSession::onSdpCompleted(), AmSession::startMediaProcessing(), AmB2BMedia::stop(), and AmSession::stopMediaProcessing().
virtual void AmMediaSession::onMediaProcessingStarted () [inline, virtual]
Callback function called when a session is added to media processor.
Default implementation sets internal variable usable for detection if the object is in use by AmMediaProcessorThread.
References AmCondition< T >::set().
Referenced by AmMediaProcessor::addSession().
virtual void AmMediaSession::processDtmfEvents () [pure virtual]
Handle events in DTMF event queue.
DTMF events should be detected from RTP stream when reading data (see readStreams()) and put into an event queue for later processing to avoid blocking of audio processing for too long time.
This DTMF event queue should be processed then, within this method, which is triggered by AmMediaProcessorThread once reading/writing from media streams is finished.
Implemented in AmSession, and AmB2BMedia.
virtual int AmMediaSession::readStreams (unsigned long long ts, unsigned char * buffer) [pure virtual]
Read from all media streams.
To preserve current media processing scheme it is needed to read from all streams first and then write to them. This can be important for example in case of conferences where we need to have media from all streams ready for mixing them.
So the AmMediaProcessorThread first calls readStreams on all sessions and then writeStreams on all sessions.
Parameters:
ts timestamp for which the processing is currently running
buffer multi-purpose space given from outside (AmMediaProcessorThread)
Buffer given as parametr is usable for anything, originally was intended for data read from one stream before putting to another stream.
The reason for having this buffer as parameter is that buffer size for audio processing is quite large (2K here) and thus allocating it on stack on some architectures may be problematic.
On other hand having the buffer dynamically allocated for each media session would significantly increase memory consumption per call.
So for now it seems to be the simplest way just to give the buffer as parameter from AmMediaProcessorThread and reuse it in all sessions handled by this thread (processing is done sequentially one session after another).
Implemented in AmSession, AmB2BMedia, CallLeg, and WebConferenceDialog.
virtual int AmMediaSession::writeStreams (unsigned long long ts, unsigned char * buffer) [pure virtual]
Write to all media streams.
For the meaning of parameters see description of readStreams() method.
Implemented in AmSession, AmB2BMedia, and CallLeg.
The documentation for this class was generated from the following file:
AmMediaProcessor.h