SEMS: SBCFactory Class Reference
SBCFactory Class Reference
Public Member Functions
DECLARE_MODULE_INSTANCE (SBCFactory)
SBCFactory (const string &_app_name)
int onLoad ()
void setCallLegCreator (CallLegCreator *clc)
CallLegCreator * getCallLegCreator ()
void setSimpleRelayCreator (SimpleRelayCreator *src)
SimpleRelayCreator * getSimpleRelayCreator ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
void onOoDRequest (const AmSipRequest &req)
AmDynInvoke * getInstance ()
void invoke (const string &method, const AmArg &args, AmArg &ret)
Data Fields
AmConfigReader cfg
AmSessionEventHandlerFactory * session_timer_fact
AmDynInvokeFactory * gui_fact
RegexMapper regex_mappings
AmEventQueueProcessor subnot_processor
Member Function Documentation
AmSession * SBCFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
References AmPlugIn::getFactory4Seh().
int SBCFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References explode(), AmPlugIn::getFactory4Seh(), AmPlugIn::load(), AmConfig::ModConfigPath, AmConfig::PlugInPath, read_regex_mapping(), AmPlugIn::registerApplication(), and AmPlugIn::registerDIInterface().
void SBCFactory::onOoDRequest (const AmSipRequest & req) [virtual]
Method to receive any out-of-dialog request other than INVITE and REFER
Warning: This method should not make any expensive processing as it would block the thread posting the event!
Reimplemented from AmSessionFactory.
References AmBasicSipDialog::reply_error(), and SBCSimpleRelay::start().
The documentation for this class was generated from the following files:
SBC.h
SBC.cpp