SEMS: AnnounceB2BFactory Class Reference
AnnounceB2BFactory Class Reference
Factory for AnnounceB2B sessions.
#include <AnnounceB2B.h>
Public Member Functions
AnnounceB2BFactory (const string &_app_name)
int onLoad ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
Static Public Attributes
static string AnnouncePath
static string AnnounceFile
Detailed Description
Factory for AnnounceB2B sessions.
Member Function Documentation
AmSession * AnnounceB2BFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
References file_exists().
int AnnounceB2BFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AmSessionFactory::configureModule(), file_exists(), and AmConfig::ModConfigPath.
The documentation for this class was generated from the following files:
AnnounceB2B.h
AnnounceB2B.cpp