SEMS: CallBackDialog Class Reference
CallBackDialog Class Reference
Public Member Functions
CallBackDialog (AmPromptCollection &prompts, UACAuthCred *cred)
void process (AmEvent *ev)
void onInvite (const AmSipRequest &req)
void onSessionStart ()
void onDtmf (int event, int duration)
UACAuthCred * getCredentials ()
AmB2ABCalleeSession * createCalleeSession ()
Member Function Documentation
void CallBackDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist(), and int2str().
void CallBackDialog::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmSession.
References AmSipDialog::bye(), and AmSession::setStopped().
void CallBackDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist().
void CallBackDialog::process (AmEvent * event) [virtual]
See also:
AmEventQueue
Reimplemented from AmB2ABSession.
The documentation for this class was generated from the following files:
CallBack.h
CallBack.cpp