SEMS: AmMediaProcessor Class Reference
AmMediaProcessor Class Reference
Media processing thread manager.
#include <AmMediaProcessor.h>
Public Types
enum { InsertSession, RemoveSession, SoftRemoveSession, ClearSession }
Public Member Functions
void init ()
void addSession (AmMediaSession *s, const string &callgroup)
void removeSession (AmMediaSession *s)
void clearSession (AmMediaSession *s)
void softRemoveSession (AmMediaSession *s)
void changeCallgroup (AmMediaSession *s, const string &new_callgroup)
void stop ()
Static Public Member Functions
static AmMediaProcessor * instance ()
static void dispose ()
Detailed Description
Media processing thread manager.
This class implements the manager that assigns and removes the Sessions to the various MediaProcessorThreads, according to their call group. This class contains the API for the MediaProcessor.
Member Enumeration Documentation
anonymous enum
InsertSession : inserts the session to the processor RemoveSession : remove the session from the processor SoftRemoveSession : remove the session from the processor but leave it attached ClearSession : remove the session from processor and clear audio
Member Function Documentation
void AmMediaProcessor::addSession (AmMediaSession * s, const string & callgroup)
Add session s to processor
References AmMediaSession::onMediaProcessingStarted().
Referenced by AmB2BMedia::addToMediaProcessor(), AmB2BMedia::addToMediaProcessorUnsafe(), changeCallgroup(), AmB2ABSession::connectSession(), and AmSession::startMediaProcessing().
void AmMediaProcessor::changeCallgroup (AmMediaSession * s, const string & new_callgroup)
Change the callgroup of a session (use with caution)
References addSession().
Referenced by AmSession::changeCallgroup().
void AmMediaProcessor::clearSession (AmMediaSession * s)
Remove session s from processor and clear its audio
void AmMediaProcessor::removeSession (AmMediaSession * s)
Remove session s from processor
Referenced by MyCCDialog::onOtherReply(), AnnounceCallerDialog::process(), C2DCallerDialog::process(), AmB2BMedia::stop(), and AmSession::stopMediaProcessing().
void AmMediaProcessor::softRemoveSession (AmMediaSession * s)
Remove session s from processor but don't signal that to the session
The documentation for this class was generated from the following files:
AmMediaProcessor.h
AmMediaProcessor.cpp