SEMS: AmSdp Class Reference
AmSdp Class Reference
The SDP parser class.
#include <AmSdp.h>
Public Member Functions
AmSdp (const AmSdp &p_sdp_msg)
int parse (const char *_sdp_msg)
void print (string &body) const
const SdpPayload * telephoneEventPayload () const
bool operator== (const AmSdp &other) const
void clear ()
Data Fields
unsigned int version
SdpOrigin origin
string sessionName
string uri
SdpConnection conn
std::vector< SdpAttribute > attributes
std::vector< SdpMedia > media
SdpOrigin l_origin
Detailed Description
The SDP parser class.
Member Function Documentation
void AmSdp::clear ()
Clear all parsed values.
Referenced by parse().
bool AmSdp::operator== (const AmSdp & other) const
Test if remote UA supports 'telefone_event'.
int AmSdp::parse (const char * _sdp_msg)
Parse the SDP message passed as an argument.
Returns:
!=0 if error encountered.
References SdpConnection::address, and clear().
Referenced by UrlCatcherFactory::onInvite(), CallLeg::onSipReply(), and AmB2BSession::updateLocalBody().
void AmSdp::print (string & body) const
Prints the current SDP structure into a proper SDP message.
References SdpConnection::address, and int2str().
Referenced by DSMCall::onSdpCompleted(), IvrDialog::onSdpCompleted(), AmSession::onSdpCompleted(), and AmB2BSession::updateLocalBody().
const SdpPayload * AmSdp::telephoneEventPayload () const
get telephone event payload
Referenced by AmRtpStream::init().
The documentation for this class was generated from the following files:
AmSdp.h
AmSdp.cpp