SEMS: RegistrationAgentFactory Class Reference
RegistrationAgentFactory Class Reference
Public Member Functions
RegistrationAgentFactory (const string &_app_name)
int onLoad ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
void postEvent (AmEvent *ev)
Member Function Documentation
AmSession * RegistrationAgentFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
int RegistrationAgentFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AmSessionFactory::configureModule(), int2str(), AmConfig::ModConfigPath, and AmThread::start().
The documentation for this class was generated from the following files:
RegistrationAgent.h
RegistrationAgent.cpp