SEMS: CallBackFactory Class Reference
CallBackFactory Class Reference
Public Member Functions
CallBackFactory (const string &_app_name)
AmSession * onInvite (const AmSipRequest &, const string &app_name, const map< string, string > &app_params)
AmSession * onInvite (const AmSipRequest &req, const string &app_name, AmArg &session_params)
int onLoad ()
void run ()
void on_stop ()
Static Public Attributes
static string gw_user
static string gw_domain
static string auth_user
static string auth_pwd
static string DigitsDir
static PlayoutType m_PlayoutType = ADAPTIVE_PLAYOUT
Member Function Documentation
AmSession * CallBackFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
AmSession * CallBackFactory::onInvite (const AmSipRequest & req, const string & app_name, AmArg & session_params) [virtual]
Creates a dialog state on new UAC request.
Parameters:
session_params parameters passed to the new session by the caller.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Reimplemented from AmSessionFactory.
References AmUACAuth::enable().
int CallBackFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AM_PROMPT_START, AmSessionFactory::configureModule(), int2str(), AmConfig::ModConfigPath, AmPromptCollection::setPrompt(), and AmThread::start().
The documentation for this class was generated from the following files:
CallBack.h
CallBack.cpp