SEMS: ServiceLineFactory Class Reference
ServiceLineFactory Class Reference
Public Member Functions
ServiceLineFactory (const string &_app_name)
int onLoad ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
Static Public Attributes
static string AnnouncePath
static string AnnounceFile
static string callee_numbers [10]
static string GWDomain
static string GWUser
static string GWDisplayname
static string GWAuthuser
static string GWAuthrealm
static string GWAuthpwd
Member Function Documentation
AmSession * ServiceLineFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
References file_exists().
int ServiceLineFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AmSessionFactory::configureModule(), file_exists(), int2str(), and AmConfig::ModConfigPath.
The documentation for this class was generated from the following files:
ServiceLine.h
ServiceLine.cpp