SEMS: PySemsFactory Class Reference
PySemsFactory Class Reference
Factory for PySems sessions.
#include <PySems.h>
Public Member Functions
PySemsFactory (const string &_app_name)
int onLoad ()
AmSession * onInvite (const AmSipRequest &req)
Detailed Description
Factory for PySems sessions.
Member Function Documentation
AmSession * PySemsFactory::onInvite (const AmSipRequest & req)
Load a script using user name from URI. Note: there is no default script.
int PySemsFactory::onLoad () [virtual]
Loads python script path and default script file from configuration file
Implements AmPluginFactory.
References add2path(), AmSessionFactory::configureModule(), AmConfig::ModConfigPath, and AmPlugIn::registerFactory4App().
The documentation for this class was generated from the following files:
PySems.h
PySems.cpp