SEMS: AnswerMachineFactory Class Reference
AnswerMachineFactory Class Reference
Public Member Functions
AnswerMachineFactory (const string &_app_name)
int onLoad ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
Static Public Attributes
static string EmailAddress
static string RecFileExt
static string AnnouncePath
static string DefaultAnnounce
static int MaxRecordTime
static AmDynInvokeFactory * MessageStorage = 0
static bool SaveEmptyMsg = true
static bool TryPersonalGreeting = false
static int DefaultVMMode = MODE_VOICEMAIL
static bool SimpleMode = false
static vector< string > MailHeaderVariables
static string SmtpServerAddress = SMTP_ADDRESS_IP
static unsigned int SmtpServerPort = SMTP_PORT
Member Function Documentation
AmSession * AnswerMachineFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
References add2path(), file_exists(), and get_header_keyvalue().
int AnswerMachineFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References add2path(), AmSessionFactory::configureModule(), explode(), AmPlugIn::getFactory4Di(), AmConfig::ModConfigPath, SmtpServerAddress, SmtpServerPort, and AmThread::start().
Field Documentation
string AnswerMachineFactory::SmtpServerAddress = SMTP_ADDRESS_IP [static]
After server start, IP of the SMTP server.
Referenced by onLoad().
unsigned int AnswerMachineFactory::SmtpServerPort = SMTP_PORT [static]
SMTP server port.
Referenced by onLoad().
The documentation for this class was generated from the following files:
AnswerMachine.h
AnswerMachine.cpp