SEMS: EarlyAnnounceFactory Class Reference
EarlyAnnounceFactory Class Reference
Factory for early_announce sessions.
#include <EarlyAnnounce.h>
Public Types
enum ContB2B { Always = 0, Never, AppParam }
Public Member Functions
EarlyAnnounceFactory (const string &_app_name)
int onLoad ()
AmSession * onInvite (const AmSipRequest &req, const string &app_name, const map< string, string > &app_params)
Static Public Attributes
static string AnnouncePath
static string AnnounceFile
static ContB2B ContinueB2B
Detailed Description
Factory for early_announce sessions.
Member Function Documentation
AmSession * EarlyAnnounceFactory::onInvite (const AmSipRequest & req, const string & app_name, const map< string, string > & app_params) [virtual]
Creates a dialog state on new UAS request.
Returns:
0 if the request is not acceptable.
Warning: This method should not make any expensive processing as it would block the server.
Implements AmSessionFactory.
References file_exists(), and get_header_keyvalue().
int EarlyAnnounceFactory::onLoad () [virtual]
Enables the plug-in to initialize whatever it needs. Ex. load the configuration.
Returns:
0 everything was ok.
1 on error.
Implements AmPluginFactory.
References AmSessionFactory::configureModule(), file_exists(), and AmConfig::ModConfigPath.
Field Documentation
EarlyAnnounceFactory::ContB2B EarlyAnnounceFactory::ContinueB2B [static]
Initial value:
  EarlyAnnounceFactory::Never
The documentation for this class was generated from the following files:
EarlyAnnounce.h
EarlyAnnounce.cpp