SEMS: PinAuthConferenceDialog Class Reference
PinAuthConferenceDialog Class Reference
Public Types
enum PinAuthConferenceState { None, EnteringPin, EnteringConference, InConference }
Public Member Functions
PinAuthConferenceDialog (AmPromptCollection &prompts)
void process (AmEvent *ev)
void onSessionStart ()
void onDtmf (int event, int duration)
void onBye (const AmSipRequest &req)
Member Function Documentation
void PinAuthConferenceDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::setStopped().
void PinAuthConferenceDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist(), and int2str().
void PinAuthConferenceDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist().
void PinAuthConferenceDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist().
The documentation for this class was generated from the following files:
PinAuthConference.h
PinAuthConference.cpp