SEMS: WebConferenceDialog Class Reference
WebConferenceDialog Class Reference
Public Types
enum WebConferenceState {
None = 0, EnteringPin, EnteringConference, InConference,
InConferenceRinging, InConferenceEarly, PlayErrorFinish
}
Public Member Functions
WebConferenceDialog (AmPromptCollection &prompts, WebConferenceFactory *my_f, UACAuthCred *cred)
WebConferenceDialog (AmPromptCollection &prompts, WebConferenceFactory *my_f, const string &room)
void process (AmEvent *ev)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
void onInvite (const AmSipRequest &req)
void onSessionStart ()
void onEarlySessionStart ()
void onRinging (const AmSipReply &rep)
void onDtmf (int event, int duration)
void onBye (const AmSipRequest &req)
void onSessionTimeout ()
void onRtpTimeout ()
UACAuthCred * getCredentials ()
virtual int readStreams (unsigned long long ts, unsigned char *buffer)
virtual bool isAudioSet ()
virtual void clearAudio ()
Member Function Documentation
void WebConferenceDialog::clearAudio () [virtual]
Clears input & ouput (no need to lock)
Reimplemented from AmSession.
References AmAudio::close(), AmSession::lockAudio(), and AmSession::unlockAudio().
bool WebConferenceDialog::isAudioSet () [virtual]
checks if input/output is set, might be overidden!
Reimplemented from AmSession.
References AmSession::lockAudio(), and AmSession::unlockAudio().
void WebConferenceDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::getLocalTag().
void WebConferenceDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist(), and int2str().
void WebConferenceDialog::onEarlySessionStart () [virtual]
Hook called when an early session starts (SDP OA completed + dialog in early state)
Reimplemented from AmSession.
void WebConferenceDialog::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmSession.
References get_header_param().
void WebConferenceDialog::onRinging (const AmSipReply & reply) [virtual]
onRinging will be called after 180 is received. If local audio is set up, session is added to media processor.
Reimplemented from AmSession.
void WebConferenceDialog::onRtpTimeout () [virtual]
This callback is called if RTP timeout encountered
Reimplemented from AmSession.
void WebConferenceDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist(), AmSession::getLocalTag(), and AmSession::setMute().
void WebConferenceDialog::onSessionTimeout () [virtual]
This callback is called if session timeout encountered (session timers)
Reimplemented from AmSession.
void WebConferenceDialog::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_dlg_status) [virtual]
Entry point for SIP Replies
Reimplemented from AmSession.
References AmSession::getLocalTag(), AmBasicSipDialog::getStatus(), int2str(), and AmSession::setStopped().
void WebConferenceDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmPromptCollection::addToPlaylist(), AmSipDialog::bye(), AmArg::get(), AmSession::getLocalTag(), AmSession::setStopped(), and AmSession::setTimer().
int WebConferenceDialog::readStreams (unsigned long long ts, unsigned char * buffer) [virtual]
Read from all media streams.
To preserve current media processing scheme it is needed to read from all streams first and then write to them. This can be important for example in case of conferences where we need to have media from all streams ready for mixing them.
So the AmMediaProcessorThread first calls readStreams on all sessions and then writeStreams on all sessions.
Parameters:
ts timestamp for which the processing is currently running
buffer multi-purpose space given from outside (AmMediaProcessorThread)
Buffer given as parametr is usable for anything, originally was intended for data read from one stream before putting to another stream.
The reason for having this buffer as parameter is that buffer size for audio processing is quite large (2K here) and thus allocating it on stack on some architectures may be problematic.
On other hand having the buffer dynamically allocated for each media session would significantly increase memory consumption per call.
So for now it seems to be the simplest way just to give the buffer as parameter from AmMediaProcessorThread and reuse it in all sessions handled by this thread (processing is done sequentially one session after another).
Reimplemented from AmSession.
References AmRtpAudio::get(), AmAudio::get(), AmSession::lockAudio(), AmAudio::put(), and AmSession::unlockAudio().
The documentation for this class was generated from the following files:
WebConferenceDialog.h
WebConferenceDialog.cpp