SEMS: AmDtmfEvent Class Reference
AmDtmfEvent Class Reference
Base class for DTMF events.
#include <AmDtmfDetector.h>
Public Member Functions
AmDtmfEvent (int event, int duration)
int event () const
int duration () const
Protected Member Functions
AmDtmfEvent (int id)
Protected Attributes
int m_event
int m_duration_msec
Detailed Description
Base class for DTMF events.
Constructor & Destructor Documentation
AmDtmfEvent::AmDtmfEvent (int id) [inline, protected]
Constructor
Member Function Documentation
int AmDtmfEvent::duration () const [inline]
Duration of keypress in miliseconds
References m_duration_msec.
Referenced by AmSession::process().
int AmDtmfEvent::event () const [inline]
Code of the key
References m_event.
Referenced by AmSession::process(), and AmRtpDtmfDetector::process().
Field Documentation
int AmDtmfEvent::m_duration_msec [protected]
Duration of keypress in miliseconds
Referenced by AmRtpDtmfEvent::AmRtpDtmfEvent(), and duration().
int AmDtmfEvent::m_event [protected]
Code of the key
Referenced by AmRtpDtmfEvent::AmRtpDtmfEvent(), and event().
The documentation for this class was generated from the following file:
AmDtmfDetector.h