SEMS: EarlyRecordDialog Class Reference
EarlyRecordDialog Class Reference
Public Member Functions
EarlyRecordDialog (UACAuthCred *credentials)
void onEarlySessionStart ()
void onSessionStart ()
void onBye (const AmSipRequest &req)
UACAuthCred * getCredentials ()
Protected Member Functions
void process (AmEvent *event)
Member Function Documentation
void EarlyRecordDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmSession::setStopped().
void EarlyRecordDialog::onEarlySessionStart () [virtual]
Hook called when an early session starts (SDP OA completed + dialog in early state)
Reimplemented from AmSession.
References AmSession::getLocalTag(), AmAudioFile::open(), AmSession::setInput(), and AmSession::setMute().
void EarlyRecordDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmAudioFile::close(), AmSession::getLocalTag(), and AmAudioFile::open().
void EarlyRecordDialog::process (AmEvent * ev) [protected, virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmSipDialog::bye(), and AmSession::setStopped().
The documentation for this class was generated from the following files:
EarlyRecord.h
EarlyRecord.cpp