SEMS: AmPayloadProvider Class Reference
AmPayloadProvider Class Reference
#include <AmPlugIn.h>
Public Member Functions
virtual amci_payload_t * payload (int payload_id) const =0
virtual int getDynPayload (const string &name, int rate, int encoding_param) const =0
virtual void getPayloads (vector< SdpPayload > &pl_vec) const =0
Detailed Description
Interface that a payload provider needs to implement
Member Function Documentation
virtual int AmPayloadProvider::getDynPayload (const string & name, int rate, int encoding_param) const [pure virtual]
Payload lookup function by name & rate
Parameters:
name Payload ID.
Returns:
-1 if failed, else the internal payload id.
Implemented in AmPlugIn, and AmPrecodedFile.
Referenced by AmRtpStream::init().
virtual void AmPayloadProvider::getPayloads (vector< SdpPayload > & pl_vec) const [pure virtual]
List all the payloads available for a media type
Implemented in AmPlugIn, and AmPrecodedFile.
Referenced by AmRtpStream::getSdpOffer().
virtual amci_payload_t* AmPayloadProvider::payload (int payload_id) const [pure virtual]
Payload lookup function.
Parameters:
payload_id Payload ID.
Returns:
NULL if failed .
Implemented in AmPlugIn, and AmPrecodedFile.
Referenced by SdpMedia::calcAnswer(), and AmRtpStream::init().
The documentation for this class was generated from the following file:
AmPlugIn.h