SEMS: ConferenceDialog Class Reference
ConferenceDialog Class Reference
session logic implementation of conference sessions
#include <Conference.h>
Public Member Functions
ConferenceDialog (const string &conf_id, AmConferenceChannel *dialout_channel=0)
void process (AmEvent *ev)
void onStart ()
void onDtmf (int event, int duration)
void onInvite (const AmSipRequest &req)
void onSessionStart ()
void onBye (const AmSipRequest &req)
void onSipRequest (const AmSipRequest &req)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
Detailed Description
session logic implementation of conference sessions
Member Function Documentation
void ConferenceDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmSession.
References AmConferenceChannel::get(), and AmSession::setStopped().
void ConferenceDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
References AmSession::getLocalTag(), and AmSessionContainer::postEvent().
void ConferenceDialog::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmSession.
References file_exists(), get_header_keyvalue(), and AmBasicSipDialog::getStatus().
void ConferenceDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
References AmSessionContainer::postEvent().
void ConferenceDialog::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_dlg_status) [virtual]
Entry point for SIP Replies
Reimplemented from AmSession.
References AmConferenceChannel::get(), AmBasicSipDialog::getStatus(), AmSessionContainer::postEvent(), and AmSession::setStopped().
void ConferenceDialog::onSipRequest (const AmSipRequest & req) [virtual]
Entry point for SIP Requests
Reimplemented from AmSession.
References get_header_keyvalue(), AmBasicSipDialog::getStatus(), and AmBasicSipDialog::sendRequest().
void ConferenceDialog::onStart () [virtual]
onStart will be called before everything else.
Reimplemented from AmSession.
void ConferenceDialog::process (AmEvent * ev) [virtual]
See also:
AmEventHandler
Reimplemented from AmSession.
References AmSipDialog::bye(), AmConferenceChannel::get(), and AmSession::setStopped().
The documentation for this class was generated from the following files:
Conference.h
Conference.cpp