SEMS: AmB2BCalleeSession Class Reference
AmB2BCalleeSession Class Reference
Callee leg of a B2B session.
#include <AmB2BSession.h>
Public Member Functions
AmB2BCalleeSession (const string &other_local_tag)
AmB2BCalleeSession (const AmB2BCallerSession *caller)
virtual void onB2BEvent (B2BEvent *ev)
Detailed Description
Callee leg of a B2B session.
Member Function Documentation
void AmB2BCalleeSession::onB2BEvent (B2BEvent * ev) [virtual]
B2BEvent handler
Reimplemented from AmB2BSession.
References AmB2BSession::est_invite_cseq, AmSession::getLocalTag(), AmB2BSession::relayed_req, AmB2BSession::saveSessionDescription(), AmBasicSipDialog::sendRequest(), AmSession::setStopped(), and AmB2BSession::updateLocalBody().
The documentation for this class was generated from the following files:
AmB2BSession.h
AmB2BSession.cpp