SEMS: IvrDialog Class Reference
IvrDialog Class Reference
python IVR wrapper for session base implementation
#include <Ivr.h>
Public Member Functions
void setPyPtrs (PyObject *mod, PyObject *dlg)
int transfer (const string &target)
int refer (const string &target, int expires)
int drop ()
void onInvite (const AmSipRequest &req)
int onSdpCompleted (const AmSdp &offer, const AmSdp &answer)
void onSessionStart ()
void onBye (const AmSipRequest &req)
void onDtmf (int event, int duration_msec)
void onOtherBye (const AmSipRequest &req)
bool onOtherReply (const AmSipReply &r)
void onSipReply (const AmSipRequest &req, const AmSipReply &reply, AmBasicSipDialog::Status old_dlg_status)
void onSipRequest (const AmSipRequest &r)
void onRtpTimeout ()
void connectCallee (const string &remote_party, const string &remote_uri, const string &from_party, const string &from_uri)
Data Fields
AmPlaylist playlist
Detailed Description
python IVR wrapper for session base implementation
Member Function Documentation
void IvrDialog::onBye (const AmSipRequest & req) [virtual]
onBye is called whenever a BYE request is received.
Reimplemented from AmB2BCallerSession.
void IvrDialog::onDtmf (int event, int duration) [virtual]
DTMF event handler for apps to use
Reimplemented from AmSession.
void IvrDialog::onInvite (const AmSipRequest & req) [virtual]
onInvite will be called if an INVITE or re-INVITE has been received for the session.
Reimplemented from AmB2BCallerSession.
void IvrDialog::onOtherBye (const AmSipRequest & req) [virtual]
handle BYE on other leg
Reimplemented from AmB2BSession.
bool IvrDialog::onOtherReply (const AmSipReply & reply) [virtual]
Reply received from other leg has been replied
Returns:
true if reply was processed (should be absorbed)
false if reply was not processed
Reimplemented from AmB2BSession.
void IvrDialog::onRtpTimeout () [virtual]
This callback is called if RTP timeout encountered
Reimplemented from AmB2BSession.
int IvrDialog::onSdpCompleted (const AmSdp & offer, const AmSdp & answer) [virtual]
Hook called when an SDP OA transaction has been completed
Reimplemented from AmB2BSession.
References AmMimeBody::addPart(), AmMimeBody::hasContentType(), AmSdp::print(), and AmMimeBody::setPayload().
void IvrDialog::onSessionStart () [virtual]
Hook called when the session creation is completed (INV trans replied with 200)
Reimplemented from AmSession.
void IvrDialog::onSipReply (const AmSipRequest & req, const AmSipReply & reply, AmBasicSipDialog::Status old_dlg_status) [virtual]
Entry point for SIP Replies
Reimplemented from AmB2BSession.
void IvrDialog::onSipRequest (const AmSipRequest & req) [virtual]
Entry point for SIP Requests
Reimplemented from AmB2BSession.
The documentation for this class was generated from the following files:
Ivr.h
Ivr.cpp