SEMS: trans_ticket Class Reference
trans_ticket Class Reference
Public Member Functions
trans_ticket (sip_trans *t, trans_bucket *bucket)
trans_ticket (const trans_ticket &ticket)
void lock_bucket () const
void unlock_bucket () const
const sip_trans * get_trans () const
void remove_trans ()
Friends
class _trans_layer
Member Function Documentation
const sip_trans * trans_ticket::get_trans () const
Get the transaction pointer Note: the transaction bucket must be locked before
References ht_bucket< Value >::exist().
void trans_ticket::lock_bucket () const
Locks the transaction bucket before accessing the transaction pointer.
Referenced by AmBasicSipDialog::termUacTrans().
void trans_ticket::remove_trans ()
Remove the transaction Note: the transaction bucket must be locked before
References ht_bucket< Value >::remove().
Referenced by AmBasicSipDialog::termUacTrans().
void trans_ticket::unlock_bucket () const
Unlocks the transaction bucket after accessing the transaction pointer.
Referenced by AmBasicSipDialog::termUacTrans().
The documentation for this class was generated from the following files:
trans_layer.h
trans_layer.cpp