SEMS: SBCCallProfile Struct Reference
SBCCallProfile Struct Reference
Data Structures
struct CodecPreferences
struct Contact
class HoldSettings
struct TranscoderSettings
Public Member Functions
bool has_logger ()
msg_logger * get_logger (const AmSipRequest &req)
void set_logger_path (const std::string path)
const string & get_logger_path ()
bool readFromConfiguration (const string &name, const string profile_file_name)
bool operator== (const SBCCallProfile &rhs) const
string print () const
int refuse (ParamReplacerCtx &ctx, const AmSipRequest &req) const
int apply_a_routing (ParamReplacerCtx &ctx, const AmSipRequest &req, AmBasicSipDialog &dlg) const
int apply_b_routing (ParamReplacerCtx &ctx, const AmSipRequest &req, AmBasicSipDialog &dlg) const
int apply_common_fields (ParamReplacerCtx &ctx, AmSipRequest &req) const
bool evaluateOutboundInterface ()
bool evaluate (ParamReplacerCtx &ctx, const AmSipRequest &req)
bool evaluateRTPRelayInterface ()
bool evaluateRTPRelayAlegInterface ()
void eval_sst_config (ParamReplacerCtx &ctx, const AmSipRequest &req, AmConfigReader &sst_cfg)
void replace_cc_values (ParamReplacerCtx &ctx, const AmSipRequest &req, AmArg *values)
void eval_cc_list (ParamReplacerCtx &ctx, const AmSipRequest &req)
void fix_append_hdrs (ParamReplacerCtx &ctx, const AmSipRequest &req)
void fix_reg_contact (ParamReplacerCtx &ctx, const AmSipRequest &req, AmUriParser &contact) const
string retarget (const string &alias, AmBasicSipDialog &dlg) const
string retarget (const string &alias)
Data Fields
string md5hash
string profile_file
string ruri
string ruri_host
string from
string to
Contact contact
string callid
string dlg_contact_params
string bleg_dlg_contact_params
bool transparent_dlg_id
bool dlg_nat_handling
bool keep_vias
bool bleg_keep_vias
string outbound_proxy
bool force_outbound_proxy
string aleg_outbound_proxy
bool aleg_force_outbound_proxy
string next_hop
bool next_hop_1st_req
bool patch_ruri_next_hop
bool next_hop_fixed
string aleg_next_hop
bool allow_subless_notify
vector< FilterEntry > headerfilter
vector< FilterEntry > messagefilter
bool anonymize_sdp
vector< FilterEntry > sdpfilter
vector< FilterEntry > aleg_sdpfilter
bool have_aleg_sdpfilter
vector< FilterEntry > sdpalinesfilter
vector< FilterEntry > mediafilter
string sst_enabled
bool sst_enabled_value
string sst_aleg_enabled
AmConfigReader sst_a_cfg
AmConfigReader sst_b_cfg
string fix_replaces_inv
string fix_replaces_ref
bool auth_enabled
UACAuthCred auth_credentials
bool auth_aleg_enabled
UACAuthCred auth_aleg_credentials
bool uas_auth_bleg_enabled
UACAuthCred uas_auth_bleg_credentials
CCInterfaceListT cc_interfaces
SBCVarMapT cc_vars
ReplyTranslationMap reply_translations
string append_headers
string append_headers_req
string aleg_append_headers_req
string refuse_with
string rtprelay_enabled
bool rtprelay_enabled_value
string force_symmetric_rtp
string aleg_force_symmetric_rtp
bool force_symmetric_rtp_value
bool aleg_force_symmetric_rtp_value
bool msgflags_symmetric_rtp
bool rtprelay_transparent_seqno
bool rtprelay_transparent_ssrc
bool rtprelay_dtmf_filtering
bool rtprelay_dtmf_detection
string rtprelay_interface
int rtprelay_interface_value
string aleg_rtprelay_interface
int aleg_rtprelay_interface_value
int rtprelay_bw_limit_rate
int rtprelay_bw_limit_peak
list< atomic_int * > aleg_rtp_counters
list< atomic_int * > bleg_rtp_counters
string outbound_interface
int outbound_interface_value
string aleg_outbound_interface
int aleg_outbound_interface_value
struct
SBCCallProfile::TranscoderSettings transcoder
struct
SBCCallProfile::CodecPreferences codec_prefs
bool contact_hiding
string contact_hiding_prefix
string contact_hiding_vars
bool reg_caching
unsigned int min_reg_expires
unsigned int max_ua_expires
class SBCCallProfile::HoldSettings hold_settings
int max_491_retry_time
bool log_rtp
bool log_sip
Member Function Documentation
string SBCCallProfile::retarget (const string & alias, AmBasicSipDialog & dlg) const
Reg-cache lookup:
searches for alias in the reg-cache.
sets next-hop & outbound_interface on the given dialog
Returns:
retargeted R-URI
References int2str(), and AmBasicSipDialog::setOutboundInterface().
Referenced by SBCCallLeg::onInvite().
string SBCCallProfile::retarget (const string & alias)
Reg-cache lookup:
searches for alias in the reg-cache.
sets next-hop & outbound_interface in this profile
Returns:
retargeted R-URI
References int2str().
The documentation for this struct was generated from the following files:
SBCCallProfile.h
SBCCallProfile.cpp