SEMS: AmContentType Struct Reference
AmContentType Struct Reference
Data Structures
struct Param
Public Types
typedef list< Param * > Params
Public Member Functions
AmContentType (const AmContentType &ct)
const AmContentType & operator= (const AmContentType &r_ct)
int parse (const string &ct)
int parseParams (const char *c, const char *end)
void setType (const string &t)
void setSubType (const string &st)
bool isType (const string &t) const
bool isSubType (const string &st) const
bool hasContentType (const string &content_type) const
string getStr () const
string getHdr () const
void clearParams ()
void resetBoundary ()
Data Fields
string type
string subtype
Params params
Param * mp_boundary
Member Function Documentation
void AmContentType::clearParams ()
Clear and free param list
string AmContentType::getHdr () const
get content-type with parameters
References getStr().
Referenced by AmMimeBody::getCTHdr().
string AmContentType::getStr () const
get content-type without any parameters
Referenced by AmMimeBody::getCTStr(), and getHdr().
void AmContentType::resetBoundary ()
set a random boundary string
References get_random(), and int2hex().
The documentation for this struct was generated from the following files:
AmMimeBody.h
AmMimeBody.cpp