SEMS: SdpMedia Struct Reference
SdpMedia Struct Reference
m=... line in SDP
#include <AmSdp.h>
Public Types
enum Direction { DirBoth = 0, DirActive = 1, DirPassive = 2, DirUndefined = 3 }
Public Member Functions
bool operator== (const SdpMedia &other) const
string debugPrint () const
void calcAnswer (const AmPayloadProvider *payload_prov, SdpMedia &answer) const
Static Public Member Functions
static string type2str (int type)
Data Fields
int type
unsigned int port
unsigned int nports
int transport
SdpConnection conn
Direction dir
string fmt
bool send
bool recv
std::vector< SdpPayload > payloads
std::vector< SdpAttribute > attributes
Detailed Description
m=... line in SDP
Member Function Documentation
void SdpMedia::calcAnswer (const AmPayloadProvider * payload_prov, SdpMedia & answer) const
Checks which payloads are compatible with the payload provider, inserts them into the answer, compute send/recv attributes and direction according to the offer.
References amci_payload_t::advertised_sample_rate, amci_payload_t::name, AmPayloadProvider::payload(), and amci_payload_t::payload_id.
Referenced by AmRtpStream::getSdpAnswer().
string SdpMedia::debugPrint () const
pretty print
References int2str().
The documentation for this struct was generated from the following files:
AmSdp.h
AmSdp.cpp