SEMS: AmUriParser Struct Reference
AmUriParser Struct Reference
Public Member Functions
bool isEqual (const AmUriParser &c) const
bool parse_contact (const string &line, size_t pos, size_t &end)
bool parse_nameaddr (const string &line)
bool parse_uri ()
bool parse_params (const string &line, int &pos)
void dump () const
string uri_str () const
string canon_uri_str () const
string nameaddr_str () const
string print ()
Static Public Member Functions
static string add_param_to_param_list (const string &param_name, const string &param_value, const string &param_list)
Data Fields
string display_name
string uri
string uri_user
string uri_host
string uri_port
string uri_headers
string uri_param
map< string, string > params
Member Function Documentation
string AmUriParser::add_param_to_param_list (const string & param_name, const string & param_value, const string & param_list) [static]
param_string is semicolon separated list of parameters with or without value. method can be used to add/replace param for uri and user parameters
bool AmUriParser::parse_contact (const string & line, size_t pos, size_t & end)
parse nameaddr from pos
Returns:
true on success
end of current nameaddr
Referenced by AmSIPRegistration::onSipReply().
bool AmUriParser::parse_nameaddr (const string & line)
parse a name-addr
Returns:
true on success
bool AmUriParser::parse_params (const string & line, int & pos)
parse params in param map
bool AmUriParser::parse_uri ()
Returns:
true on success
parse uri into user, host, port, param
Referenced by VoiceboxFactory::onInvite(), and SBCCallLeg::onInvite().
The documentation for this struct was generated from the following files:
AmUriParser.h
AmUriParser.cpp